Calc and compare pathway scores on patient level

# Header

In [1]:
setwd('/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/github')
source('codes/functions.R')

Loading required package: SeuratObject

Loading required package: sp


Attaching package: ‘SeuratObject’


The following objects are masked from ‘package:base’:

    intersect, t



Attaching package: ‘dplyr’


The following object is masked from ‘package:gridExtra’:

    combine


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘anndata’


The following object is masked from ‘package:SeuratObject’:

    Layers

# Module score

In [3]:
pb = qs::qread('data/06_pb/pb_donor_celltypelevel3.qs')

pb

An object of class Seurat
28202 features across 1341 samples within 5 assays
Active assay: RNA (27879 features, 0 variable features)
 3 layers present: counts, data, scale.data
 4 other assays present: prediction.score.celltype.l1, prediction.score.celltype.l2, prediction.score.celltype.l3, impADT

In [4]:
unique(pb@meta.data$celltype_level3)

 [1] "Naive B"               "Mature B"              "Memory B"
 [4] "Plasmablast"           "Naive CD4T"            "Central Memory CD4T"
 [7] "Cytotoxic CD4T"        "Effector Memory CD4T"  "Treg"
[10] "Naive CD8T"            "Central Memory CD8T"   "Effector Memory CD8T"
[13] "Double Negative T"     "γδ T"                  "MAIT"
[16] "cDC1"                  "cDC2"                  "pDC"
[19] "Classical Monocyte"    "Intermediate Monocyte" "Nonclassical Monocyte"
[22] "Cytotoxic Monocyte"    "CD56-dim NK"           "CD56-bright NK"
[25] "Proliferating NK"

In [5]:
gset <- parse_gmt("data/11_genesets/immport_allgenelist.gmt")
gset

$`Activation of innate immune response`
  [1] "AIM2"        "ALPK1"       "AP3B1"       "BCL10"       "BECN1"
  [6] "BTK"         "CASP1"       "CASP6"       "CD14"        "CD274"
 [11] "CD300LF"     "CGAS"        "CHUK"        "CLEC4E"      "CLEC6A"
 [16] "CLEC7A"      "CLPB"        "COLEC10"     "COLEC11"     "COLEC12"
 [21] "CREBBP"      "CTSS"        "CYLD"        "DHX58"       "ECSIT"
 [26] "EP300"       "EPG5"        "FCN1"        "FCN2"        "FCN3"
 [31] "FFAR2"       "FOSL1"       "FYN"         "GBP2"        "GBP5"
 [36] "HAVCR2"      "HCK"         "HEXIM1"      "HMGB1"       "HSP90AA1"
 [41] "HSPD1"       "IFI16"       "IFIH1"       "IKBKB"       "INAVA"
 [46] "IPO5"        "IRAK1"       "IRAK2"       "IRAK3"       "IRAK4"
 [51] "IRF3"        "IRF7"        "IRGM"        "ITCH"        "KIR2DS2"
 [56] "KLRC1"       "KLRC2"       "KLRC3"       "KLRC4"       "KLRC4-KLRK1"
 [61] "KLRD1"       "KLRK1"       "LACC1"       "LBP"         "LILRA2"
 [66] "LRRC19"      "LSM14A"      "LY96"        "LYN"         "MAP2K6"
 [71] "MAP3K7"      "MAPKAPK2"    "MAPKAPK3"    "MATR3"       "MAVS"
 [76] "MBL2"        "MEFV"        "MNDA"        "MYD88"       "NAGLU"
 [81] "NAIP"        "NFKBIA"      "NFKBIZ"      "NLRC4"       "NLRP1"
 [86] "NLRP10"      "NLRP3"       "NMI"         "NOD1"        "NOD2"
 [91] "NONO"        "NR1H4"       "OAS1"        "OAS3"        "OTULIN"
 [96] "PAK1"        "PAK2"        "PAK3"        "PHB1"        "PHB2"
[101] "PIK3AP1"     "PLCG2"       "PQBP1"       "PRKCE"       "PRKDC"
[106] "PSPC1"       "PYCARD"      "PYHIN1"      "RAB11FIP2"   "RBM14"
[111] "REG3G"       "RELA"        "RFTN1"       "RIGI"        "RIPK2"
[116] "RNF135"      "RNF144A"     "RNF34"       "RPS6KA3"     "S100A14"
[121] "SCIMP"       "SFPQ"        "SIN3A"       "SRC"         "STING1"
[126] "SYK"         "TBK1"        "TICAM1"      "TICAM2"      "TIFA"
[131] "TIFAB"       "TIRAP"       "TLR1"        "TLR10"       "TLR2"
[136] "TLR3"        "TLR4"        "TLR5"        "TLR6"        "TLR7"
[141] "TLR8"        "TLR9"        "TMEM126A"    "TNF"         "TNFAIP3"
[146] "TNIP1"       "TNIP2"       "TNIP3"       "TOMM70"      "TRAF3"
[151] "TRAF3IP3"    "TRAF6"       "TRIL"        "TRIM25"      "TRIM5"
[156] "TYROBP"      "UNC93B1"     "XIAP"        "XRCC5"       "XRCC6"
[161] "YWHAE"       "ZBP1"        "ZCCHC3"      "ZNFX1"

$`Adaptive immune memory response`
[1] "CD27"  "CD70"  "EBAG9"

$`Adaptive immune memory response involving T cells and B cells`
[1] "CD27"  "CD70"  "EBAG9"

$`Adaptive immune response based on somatic recombination of immune receptors built from immunoglobulin superfamily domains`
  [1] "ADA"        "ADAM17"     "AIRE"       "B2M"        "BACH2"
  [6] "BCL10"      "BCL3"       "BCL6"       "BTN3A2"     "BTN3A3"
 [11] "C4BPA"      "CARD9"      "CD19"       "CD27"       "CD40"
 [16] "CD46"       "CD70"       "CD74"       "CD81"       "CD8A"
 [21] "CLEC4G"     "CR1"        "CR1L"       "CR2"        "CSF2RB"
 [26] "CTSC"       "CTSH"       "CXCL13"     "EBAG9"      "EBI3"
 [31] "EMP2"       "EXO1"       "FCER1A"     "FCER1G"     "FCGR1A"
 [36] "FCGR1BP"    "FCGR2A"     "FCGR2B"     "FCGR2C"     "FCGR3A"
 [41] "FCGR3B"     "FCMR"       "FOXP3"      "GNL1"       "GZMM"
 [46] "HLA-A"      "HLA-DRB1"   "HLA-G"      "HPRT1"      "HRAS"
 [51] "IGHD"       "IGHG1"      "IGHV1-18"   "IGHV1-24"   "IGHV1-3"
 [56] "IGHV1-38-4" "IGHV1-45"   "IGHV1-58"   "IGHV1-69"   "IGHV1-69-2"
 [61] "IGHV1-69D"  "IGHV1-8"    "IGHV2-26"   "IGHV2-5"    "IGHV2-70"
 [66] "IGHV2-70D"  "IGHV3-11"   "IGHV3-13"   "IGHV3-15"   "IGHV3-16"
 [71] "IGHV3-20"   "IGHV3-21"   "IGHV3-23"   "IGHV3-30"   "IGHV3-30-3"
 [76] "IGHV3-30-5" "IGHV3-33"   "IGHV3-35"   "IGHV3-38"   "IGHV3-38-3"
 [81] "IGHV3-43"   "IGHV3-43D"  "IGHV3-48"   "IGHV3-49"   "IGHV3-53"
 [86] "IGHV3-64"   "IGHV3-64D"  "IGHV3-66"   "IGHV3-7"    "IGHV3-72"
 [91] "IGHV3-73"   "IGHV3-74"   "IGHV3-9"    "IGHV4-28"   "IGHV4-30-4"
 [96] "IGHV4-31"   "IGHV4-34"   "IGHV4-38-2" "IGHV4-39"   "IGHV4-4"
[101] "IGHV4-59"   "IGHV4-61"   "IGHV5-10-1" "IGHV5-51"   "IGHV6-1"
[106] "IGHV7-4-1"  "IGHV7-81"   "IGHV8-51-1" "IGKC"       "IGLC1"
[111] "IGLC2"      "IGLC3"      "IGLC6"      "IGLC7"      "IGLL1"
[116] "IGLL5"      "IL12B"      "IL13RA2"    "IL17RA"     "IL18"
[121] "IL18BP"     "IL21R"      "IL2RB"      "IL4R"       "IL7R"
[126] "IL9"        "IL9R"       "INPP5D"     "IRF7"       "JAG1"
[131] "KLHL6"      "MEF2C"      "MICA"       "MPL"        "MSH2"
[136] "MYD88"      "MYO1G"      "NFKB2"      "NFKBIZ"     "NOTCH1"
[141] "P2RX7"      "PHB1"       "PPP3CB"     "PRF1"       "PRKCD"
[146] "PSG9"       "SCART1"     "SLA2"       "STAT3"      "TAP2"
[151] "TCIRG1"     "TGFB1"      "TLR4"       "TLR8"       "TNFSF13B"
[156] "TRA"        "TRAF3IP2"   "TRAF6"      "TRB"        "TREX1"
[161] "UNC13D"     "ZP3"

$`Advanced glycosylation endproduct receptor signaling`
 [1] "AGER"    "APP"     "CAPZA1"  "CAPZA2"  "DDOST"   "HMGB1"   "LGALS3"
 [8] "MAPK1"   "MAPK3"   "PRKCSH"  "S100A12" "S100B"   "SAA1"

$`Alpha-beta T cell activation`
 [1] "ABL1"    "ADA"     "ANXA1"   "ARMC5"   "ASCL2"   "ATF2"    "ATP7A"
 [8] "BATF"    "BCL11B"  "BCL3"    "BCL6"    "BRAF"    "CARD11"  "CBLB"
[15] "CD247"   "CD28"    "CD3D"    "CD3E"    "CD3G"    "CD83"    "CDH26"
[22] "CLEC2B"  "CLEC4A"  "CLEC4G"  "DOCK2"   "ELF4"    "ENTPD7"  "EOMES"
[29] "FOSL2"   "FOXP1"   "FOXP3"   "FUT7"    "GATA3"   "GLI3"    "GPR18"
[36] "GPR183"  "HLA-A"   "HLA-E"   "HLX"     "HMGB1"   "IL12B"   "IL15"
[43] "IL18R1"  "IL21"    "IL2RG"   "IL4R"    "IL6"     "INS"     "IRF1"
[50] "ITCH"    "ITK"     "KLRF1"   "KMT2A"   "LEF1"    "MEN1"    "MYB"
[57] "NDFIP1"  "NFKBIZ"  "NKG7"    "NKX2-3"  "PDP2"    "PLA2G2D" "PRKCQ"
[64] "PRR7"    "PSMB11"  "PTGER4"  "PTPRC"   "RC3H1"   "RC3H2"   "RELB"
[71] "RIPK2"   "RORA"    "RORC"    "RPL22"   "RSAD2"   "SASH3"   "SEMA4A"
[78] "SHH"     "STAT4"   "STOML2"  "TCIRG1"  "TMEM98"  "TNFSF4"  "TNFSF8"
[85] "TRAC"    "TRBC1"   "TRBC2"   "WDFY4"   "ZBTB7B"

$`Alpha-protein kinase 1 signaling pathway`
 [1] "ALPK1"  "MAP3K7" "RPS27A" "TAB1"   "TAB2"   "TAB3"   "TIFA"   "TRAF6"
 [9] "UBA52"  "UBB"    "UBC"

$`Antibacterial innate immune response`
 [1] "DEFB136"  "MARCHF2"  "MIRLET7B" "MPEG1"    "NFKB1"    "NOD2"
 [7] "RASGRP4"  "SLC15A2"  "TFEB"     "UMOD"

$`Antibody-dependent cellular cytotoxicity`
[1] "FCGR1A"  "FCGR1BP" "FCGR2A"  "FCGR2B"  "FCGR2C"  "FCGR3A"  "FCGR3B"
[8] "IGHG1"

$`Antifungal innate immune response`
 [1] "BCL10"    "CARD9"    "CLEC4A"   "CLEC4C"   "CLEC4D"   "CLEC4E"
 [7] "CLEC6A"   "CLEC7A"   "CX3CR1"   "DEFB106A" "DEFB106B" "DEFB114"
[13] "DEFB119"  "DEFB136"  "DEFB4A"   "PLCG2"    "RARRES2"  "RNASE8"

$`Antigen processing and presentation`
  [1] "ACE"      "AP3B1"    "AP3D1"    "ARL8B"    "ATG5"     "B2M"
  [7] "CD1A"     "CD1B"     "CD1C"     "CD1D"     "CD1E"     "CD209"
 [13] "CD74"     "CD8A"     "CLEC4A"   "CLEC4M"   "CTSD"     "CTSE"
 [19] "CTSF"     "CTSH"     "CTSL"     "CTSS"     "CTSV"     "DNM2"
 [25] "ERAP1"    "ERAP2"    "EXT1"     "FCER1G"   "FCER2"    "FCGR1A"
 [31] "FCGR2B"   "GBA1"     "HFE"      "HLA-A"    "HLA-B"    "HLA-C"
 [37] "HLA-DMA"  "HLA-DMB"  "HLA-DOA"  "HLA-DOB"  "HLA-DPA1" "HLA-DPB1"
 [43] "HLA-DQA1" "HLA-DQA2" "HLA-DQB1" "HLA-DQB2" "HLA-DRA"  "HLA-DRB1"
 [49] "HLA-DRB3" "HLA-DRB4" "HLA-DRB5" "HLA-E"    "HLA-F"    "HLA-G"
 [55] "HLA-H"    "ICAM1"    "IDE"      "IFI30"    "IKBKB"    "KDM5D"
 [61] "LGMN"     "LNPEP"    "MARCHF1"  "MARCHF8"  "MFSD6"    "MICA"
 [67] "MICB"     "MPEG1"    "MR1"      "PIKFYVE"  "PSMB8"    "PSME1"
 [73] "RAB10"    "RAB27A"   "RAB32"    "RAB33A"   "RAB34"    "RAB35"
 [79] "RAB3B"    "RAB3C"    "RAB4A"    "RAB5B"    "RAB6A"    "RAB8B"
 [85] "RAET1E"   "RAET1G"   "RAET1L"   "RELB"     "RFTN1"    "SAR1B"
 [91] "SLC11A1"  "TAP1"     "TAP2"     "TAPBP"    "TRAF6"    "TREX1"
 [97] "ULBP1"    "ULBP2"    "ULBP3"    "UNC93B1"  "WDFY4"

$`Antigen receptor-mediated signaling pathway`
  [1] "ABL1"     "ADA"      "BANK1"    "BAX"      "BCAR1"    "BCL10"
  [7] "BCL2"     "BLK"      "BLNK"     "BMX"      "BRAF"     "BTK"
 [13] "BTN1A1"   "BTN2A1"   "BTN2A2"   "BTN2A3P"  "BTN3A1"   "BTN3A2"
 [19] "BTN3A3"   "BTNL10P"  "BTNL2"    "BTNL3"    "BTNL8"    "BTNL9"
 [25] "CACNB3"   "CACNB4"   "CBLB"     "CD19"     "CD247"    "CD276"
 [31] "CD28"     "CD2AP"    "CD38"     "CD3D"     "CD3E"     "CD3G"
 [37] "CD79A"    "CD79B"    "CD8A"     "CD8B"     "CRKL"     "CSK"
 [43] "CTLA4"    "DENND1B"  "EIF2B1"   "EIF2B2"   "EIF2B3"   "EIF2B4"
 [49] "EIF2B5"   "ERMAP"    "FCHO1"    "FOSL2"    "FOXP3"    "FYB1"
 [55] "FYB2"     "FYN"      "GATA3"    "GRB2"     "HHLA2"    "HLA-A"
 [61] "HLA-DPB1" "HLA-DQB1" "HLA-DRB1" "HLA-DRB3" "HRAS"     "ICOSLG"
 [67] "IGHA1"    "IGHA2"    "IGHD"     "IGHE"     "IGHG1"    "IGHG2"
 [73] "IGHG3"    "IGHG4"    "IGHM"     "IGKC"     "IGLC1"    "IGLC3"
 [79] "IGLC6"    "IGLC7"    "IKBKB"    "IKBKG"    "INPP5D"   "ITK"
 [85] "KHDRBS1"  "KLHL6"    "LAT"      "LAT2"     "LAX1"     "LCK"
 [91] "LCP2"     "LIME1"    "LYN"      "MALT1"    "MAP3K7"   "MAPK1"
 [97] "MEF2C"    "MNDA"     "MOG"      "MS4A1"    "NCKAP1L"  "NFAM1"
[103] "NFATC2"   "NFKB1"    "NFKBIA"   "NFKBID"   "NFKBIZ"   "PDE4B"
[109] "PDE4D"    "PIK3CA"   "PIK3CD"   "PLCG1"    "PLCG2"    "PLEKHA1"
[115] "PRAM1"    "PRKCB"    "PRKD2"    "PSEN1"    "PTPN22"   "PTPN6"
[121] "PTPRC"    "PTPRJ"    "RBCK1"    "RC3H1"    "RC3H2"    "RFTN1"
[127] "RIPK2"    "RNF31"    "SH2B2"    "SHB"      "SKAP1"    "SLA2"
[133] "SLC39A6"  "SOS1"     "SPG21"    "SPPL3"    "STK11"    "STOML2"
[139] "SYK"      "TEC"      "THEMIS"   "THEMIS2"  "THY1"     "TMIGD2"
[145] "TNFRSF21" "TRAC"     "TRAF6"    "TRBC1"    "TRBC2"    "TRDC"
[151] "TRGC1"    "TRGC2"    "TXK"      "UBE2N"    "VAV3"     "VTCN1"
[157] "WNK1"     "ZAP70"    "ZC3H12A"

$`Antimicrobial humoral response`
  [1] "ANG"      "AZU1"     "BCL3"     "BPIFA1"   "CAMP"     "CCL1"
  [7] "CCL11"    "CCL13"    "CCL14"    "CCL15"    "CCL16"    "CCL17"
 [13] "CCL18"    "CCL19"    "CCL2"     "CCL20"    "CCL21"    "CCL22"
 [19] "CCL23"    "CCL24"    "CCL25"    "CCL26"    "CCL3"     "CCL3L1"
 [25] "CCL3L3"   "CCL4"     "CCL4L1"   "CCL5"     "CCL7"     "CCL8"
 [31] "COLEC11"  "CST9"     "CST9L"    "CST9LP1"  "CTSG"     "CX3CL1"
 [37] "CXCL1"    "CXCL10"   "CXCL11"   "CXCL13"   "CXCL14"   "CXCL2"
 [43] "CXCL3"    "CXCL5"    "CXCL6"    "CXCL8"    "CXCL9"    "DEFA1"
 [49] "DEFA1B"   "DEFA3"    "DEFA4"    "DEFA5"    "DEFA6"    "DEFB1"
 [55] "DEFB118"  "DEFB126"  "DEFB127"  "DEFB4A"   "DMBT1"    "F2"
 [61] "FAM3A"    "FAU"      "FGA"      "FGB"      "GALP"     "GAPDH"
 [67] "GNLY"     "H2BC10"   "H2BC11"   "H2BC12"   "H2BC12L"  "H2BC21"
 [73] "H2BC4"    "H2BC6"    "H2BC7"    "H2BC8"    "HLA-A"    "HLA-E"
 [79] "HMGN2"    "HRG"      "IGHA1"    "IGHA2"    "IGHE"     "IGHG1"
 [85] "IGHG2"    "IGHG3"    "IGHG4"    "IGHM"     "IGKV3-20" "IL36RN"
 [91] "JCHAIN"   "KRT6A"    "LEAP2"    "LTF"      "LYZ"      "MUC7"
 [97] "NCR3LG1"  "PF4"      "PF4V1"    "PGLYRP1"  "PGLYRP3"  "PGLYRP4"
[103] "PI3"      "PLA2G1B"  "PLA2G6"   "PPBP"     "PRSS2"    "PRSS3"
[109] "PRTN3"    "RARRES2"  "REG1A"    "REG1B"    "REG3A"    "REG3G"
[115] "RNASE3"   "RNASE4"   "RNASE6"   "RNASE7"   "ROMO1"    "RPL30"
[121] "RPL39"    "RPS19"    "S100A12"  "S100A7"   "S100A9"   "SEMG1"
[127] "SEMG2"    "SLC11A1"  "SLPI"     "SPAG11A"  "SPAG11B"  "SPON2"
[133] "SPRR2A"   "TF"       "TSLP"     "WFDC10A"  "WFDC10B"  "WFDC11"
[139] "WFDC12"   "WFDC13"   "WFDC2"    "WFDC3"    "WFDC5"    "WFDC9"
[145] "XCL1"     "XCL2"

$`Antimicrobial peptides`
 [1] "ART1"        "ATOX1"       "ATP7A"       "BPI"         "BPIFA1"
 [6] "BPIFA2"      "BPIFB1"      "BPIFB2"      "BPIFB4"      "BPIFB6"
[11] "CAMP"        "CCR2"        "CCR6"        "CD4"         "CHGA"
[16] "CLU"         "CTSG"        "DCD"         "DEFA1"       "DEFA1B"
[21] "DEFA3"       "DEFA4"       "DEFA5"       "DEFA6"       "DEFB1"
[26] "DEFB103A"    "DEFB103B"    "DEFB104A"    "DEFB104B"    "DEFB105A"
[31] "DEFB105B"    "DEFB106A"    "DEFB106B"    "DEFB107A"    "DEFB107B"
[36] "DEFB108B"    "DEFB110"     "DEFB113"     "DEFB114"     "DEFB115"
[41] "DEFB116"     "DEFB118"     "DEFB119"     "DEFB121"     "DEFB123"
[46] "DEFB124"     "DEFB125"     "DEFB126"     "DEFB127"     "DEFB128"
[51] "DEFB129"     "DEFB130A"    "DEFB130B"    "DEFB131A"    "DEFB132"
[56] "DEFB134"     "DEFB135"     "DEFB136"     "DEFB4A"      "DEFB4B"
[61] "ELANE"       "EPPIN"       "EPPIN-WFDC6" "GNLY"        "HTN1"
[66] "HTN3"        "ITLN1"       "LCN2"        "LEAP2"       "LTF"
[71] "LYZ"         "PDZD11"      "PGLYRP1"     "PGLYRP2"     "PGLYRP3"
[76] "PGLYRP4"     "PI3"         "PLA2G2A"     "PRSS2"       "PRSS3"
[81] "PRTN3"       "REG3A"       "REG3G"       "RNASE3"      "RNASE6"
[86] "RNASE7"      "RNASE8"      "S100A7"      "S100A7A"     "S100A8"
[91] "S100A9"      "SEMG1"       "SLC11A1"     "TLR1"        "TLR2"

$`Antiviral innate immune response`
 [1] "AKAP1"   "ATAD3A"  "CARD8"   "CLPB"    "CXCL10"  "DHX15"   "DHX16"
 [8] "DHX58"   "DUS2"    "EIF2AK2" "HCFC2"   "IFIH1"   "IFIT1"   "IFIT2"
[15] "IFIT3"   "MARCHF2" "MAVS"    "MBL2"    "MORC3"   "MX1"     "NCK1"
[22] "NLRP1"   "NLRP6"   "NMB"     "NMBR"    "OAS1"    "PDE12"   "PHB1"
[29] "PHB2"    "PRKRA"   "RELA"    "RIGI"    "RNF135"  "RPSA"    "SENP7"
[36] "SMARCA5" "STING1"  "TBK1"    "TNF"     "TRAF6"   "TRIM25"  "TRIM31"
[43] "TRIM6"   "TRIM65"  "TRIM7"   "UAP1"    "UBE2N"   "UBE2W"   "USP18"
[50] "USP20"   "USP44"   "ZBP1"    "ZDHHC1"  "ZDHHC11"

$`Antiviral mechanism by IFN-stimulated genes`
  [1] "AAAS"       "ABCE1"      "ADAR"       "ARIH1"      "BECN1"
  [6] "CDK1"       "CENPS"      "CENPS-CORT" "CENPX"      "CHUK"
 [11] "DHX9"       "DNAJC3"     "DUS2"       "EIF2AK2"    "EIF2S1"
 [16] "EIF2S2"     "EIF2S3"     "EIF4A1"     "EIF4A2"     "EIF4A3"
 [21] "EIF4E"      "EIF4E2"     "EIF4E3"     "EIF4G1"     "EIF4G2"
 [26] "EIF4G3"     "FAAP100"    "FAAP20"     "FAAP24"     "FANCA"
 [31] "FANCB"      "FANCC"      "FANCE"      "FANCF"      "FANCG"
 [36] "FANCL"      "FANCM"      "FLNA"       "FLNB"       "HERC5"
 [41] "HSPA1A"     "HSPA1B"     "HSPA1L"     "HSPA2"      "HSPA8"
 [46] "IFIT1"      "IKBKB"      "IKBKG"      "ILF2"       "ILF3"
 [51] "IRF3"       "ISG15"      "JAK1"       "KPNA1"      "KPNA2"
 [56] "KPNA3"      "KPNA4"      "KPNA5"      "KPNA7"      "KPNB1"
 [61] "MAP2K6"     "MAPK3"      "MAPT"       "MAVS"       "MX1"
 [66] "MX2"        "NCK1"       "NDC1"       "NEDD4"      "NPM1"
 [71] "NUP107"     "NUP133"     "NUP153"     "NUP155"     "NUP160"
 [76] "NUP188"     "NUP205"     "NUP210"     "NUP214"     "NUP35"
 [81] "NUP37"      "NUP42"      "NUP43"      "NUP50"      "NUP54"
 [86] "NUP58"      "NUP62"      "NUP85"      "NUP88"      "NUP93"
 [91] "NUP98"      "OAS1"       "OAS2"       "OAS3"       "OASL"
 [96] "PDE12"      "PIN1"       "PLCG1"      "POM121"     "PPM1B"
[101] "PPP2CA"     "PPP2CB"     "PPP2R1A"    "PPP2R1B"    "PPP2R5A"
[106] "PRKRA"      "PTPN2"      "RAE1"       "RANBP2"     "RIGI"
[111] "RNASEL"     "RPS27A"     "SEC13"      "SEH1L"      "SNCA"
[116] "SPHK1"      "STAT1"      "STAT3"      "SUMO1"      "TARBP2"
[121] "TP53"       "TPR"        "TRIM25"     "TUBA1A"     "TUBA1B"
[126] "TUBA1C"     "TUBA3C"     "TUBA3D"     "TUBA3E"     "TUBA4A"
[131] "TUBA8"      "TUBAL3"     "TUBB1"      "TUBB2A"     "TUBB2B"
[136] "TUBB3"      "TUBB4A"     "TUBB4B"     "TUBB6"      "TUBB8"
[141] "UBA52"      "UBA7"       "UBB"        "UBC"        "UBE2E1"
[146] "UBE2I"      "UBE2L6"     "UBE2N"      "USP18"

$`B cell activation`
  [1] "ABL1"     "ADA"      "ADAM17"   "ADGRG3"   "AICDA"    "AKAP17A"
  [7] "AQP8"     "ATAD5"    "BANK1"    "BATF"     "BAX"      "BCL2"
 [13] "BCL3"     "BCL6"     "BLNK"     "BST2"     "BTK"      "C17orf99"
 [19] "CARD11"   "CASP8"    "CCR6"     "CD180"    "CD19"     "CD22"
 [25] "CD38"     "CD40"     "CD40LG"   "CD70"     "CD79A"    "CD79B"
 [31] "CD86"     "CDH17"    "CEBPG"    "CHRNA4"   "CHRNB2"   "CLCF1"
 [37] "CMTM7"    "CR2"      "CTPS1"    "CXCR5"    "DCAF1"    "DCLRE1C"
 [43] "DLL1"     "DNAJB9"   "DOCK10"   "DOCK11"   "EP300"    "EPHB2"
 [49] "ERCC1"    "EXO1"     "EXOSC3"   "EXOSC6"   "EZH2"     "FCGR2B"
 [55] "FCRL1"    "FLT3"     "FNIP1"    "FOSL2"    "FOXP3"    "FZD9"
 [61] "GAPT"     "GPR183"   "GPS2"     "HDAC4"    "HDAC5"    "HDAC9"
 [67] "HHEX"     "HSPD1"    "ICOSLG"   "IFNA1"    "IFNA10"   "IFNA13"
 [73] "IFNA14"   "IFNA16"   "IFNA17"   "IFNA2"    "IFNA21"   "IFNA4"
 [79] "IFNA5"    "IFNA6"    "IFNA7"    "IFNA8"    "IFNB1"    "IFNE"
 [85] "IFNK"     "IFNW1"    "IGBP1"    "IKZF3"    "IL10"     "IL11"
 [91] "IL21"     "IL2RG"    "IL4"      "IL6"      "IL7"      "IL7R"
 [97] "IL9"      "IRF2BP2"  "IRF8"     "ITFG2"    "ITGA4"    "ITGB1"
[103] "ITM2A"    "JAK3"     "KIT"      "KLF6"     "LAT2"     "LAX1"
[109] "LEF1"     "LFNG"     "LGALS1"   "LIG4"     "LRRC8A"   "LYL1"
[115] "MALT1"    "MEF2C"    "MFNG"     "MIR19A"   "MLH1"     "MS4A1"
[121] "MSH2"     "MSH6"     "NBN"      "NFAM1"    "NFKBIZ"   "NHEJ1"
[127] "NKX2-3"   "NOTCH2"   "NTRK1"    "ONECUT1"  "PAX5"     "PHB1"
[133] "PHB2"     "PHF14"    "PIK3CD"   "PIK3R1"   "PIK3R2"   "PIK3R3"
[139] "PLCG2"    "PLCL2"    "POU2AF1"  "PRKCB"    "PRKCD"    "PRKDC"
[145] "PTK2B"    "PTPN2"    "PTPRC"    "PTPRJ"    "RABL3"    "RAG1"
[151] "RAG2"     "RASGRP1"  "RBPJ"     "RNF168"   "RNF8"     "SANBR"
[157] "SASH3"    "SHB"      "SKAP2"    "SLC25A5"  "SLC39A7"  "SP3"
[163] "ST3GAL1"  "STAT5B"   "STAT6"    "SWAP70"   "SYK"      "SYVN1"
[169] "TBC1D10C" "TCF3"     "TCIRG1"   "TICAM1"   "TLR4"     "TNFSF13B"
[175] "TOP2B"    "TPD52"    "TRAF3IP2" "TXLNA"    "UNG"      "VCAM1"
[181] "WNT3A"    "YY1"      "ZAP70"    "ZBTB1"    "ZBTB7A"

$`B cell costimulation`
[1] "CD320"     "TNFRSF13C" "TNFSF13B"

$`B cell differentiation`
  [1] "ABL1"     "ADA"      "ADAM17"   "ADGRG3"   "AICDA"    "AQP8"
  [7] "BCL3"     "BCL6"     "BLNK"     "C17orf99" "CARD11"   "CD19"
 [13] "CD40LG"   "CD79A"    "CD79B"    "CDH17"    "CEBPG"    "CLCF1"
 [19] "CMTM7"    "CR2"      "DCAF1"    "DCLRE1C"  "DLL1"     "DNAJB9"
 [25] "DOCK10"   "DOCK11"   "EP300"    "EZH2"     "FCGR2B"   "FLT3"
 [31] "FNIP1"    "FOSL2"    "FZD9"     "GPR183"   "GPS2"     "HDAC4"
 [37] "HDAC5"    "HDAC9"    "HHEX"     "IFNA1"    "IFNA10"   "IFNA13"
 [43] "IFNA14"   "IFNA16"   "IFNA17"   "IFNA2"    "IFNA21"   "IFNA4"
 [49] "IFNA5"    "IFNA6"    "IFNA7"    "IFNA8"    "IFNB1"    "IFNE"
 [55] "IFNK"     "IFNW1"    "IKZF3"    "IL10"     "IL11"     "IL21"
 [61] "IL2RG"    "IL4"      "IL6"      "IL9"      "IRF2BP2"  "IRF8"
 [67] "ITFG2"    "ITGA4"    "ITGB1"    "ITM2A"    "JAK3"     "KIT"
 [73] "KLF6"     "LFNG"     "LGALS1"   "LRRC8A"   "LYL1"     "MALT1"
 [79] "MFNG"     "MS4A1"    "MSH2"     "NFAM1"    "NFKBIZ"   "NHEJ1"
 [85] "NKX2-3"   "NOTCH2"   "NTRK1"    "ONECUT1"  "PAX5"     "PHF14"
 [91] "PIK3CD"   "PIK3R1"   "PIK3R2"   "PIK3R3"   "PLCG2"    "PLCL2"
 [97] "POU2AF1"  "PRKDC"    "PTK2B"    "PTPN2"    "PTPRC"    "PTPRJ"
[103] "RABL3"    "RAG1"     "RAG2"     "RBPJ"     "SLC25A5"  "SLC39A7"
[109] "SP3"      "ST3GAL1"  "STAT5B"   "SYK"      "SYVN1"    "TCF3"
[115] "TCIRG1"   "TNFSF13B" "TOP2B"    "TPD52"    "TRAF3IP2" "VCAM1"
[121] "YY1"      "ZBTB1"    "ZBTB7A"

$`B cell receptor apoptotic signaling pathway`
[1] "BAX"    "NFKBIZ"

$`B cell selection`
[1] "BAK1"     "BAX"      "BTK"      "TRAF3IP2"

$`Butyrophilin (BTN) family interactions`
 [1] "BTN1A1" "BTN2A1" "BTN2A2" "BTN3A1" "BTN3A2" "BTN3A3" "BTNL2"  "BTNL8"
 [9] "BTNL9"  "CD209"  "PPL"    "XDH"

$`Cell activation involved in immune response`
  [1] "ABL1"     "ADA"      "AICDA"    "APBB1IP"  "APP"      "ASCL2"
  [7] "ATAD5"    "ATP7A"    "BATF"     "BCL3"     "BCL6"     "C17orf99"
 [13] "CCR6"     "CD180"    "CD19"     "CD1C"     "CD244"    "CD40LG"
 [19] "CD74"     "CDH17"    "CLEC4D"   "CLEC4E"   "CX3CR1"   "DLL1"
 [25] "DNASE1"   "DNASE1L3" "DOCK10"   "DOCK11"   "DOCK2"    "DYSF"
 [31] "EIF2AK4"  "ENPP3"    "ENTPD7"   "EOMES"    "ERCC1"    "EXO1"
 [37] "EXOSC3"   "EXOSC6"   "F2RL1"    "FCER1G"   "FCGR2B"   "FGL2"
 [43] "FOXP1"    "FOXP3"    "GAPT"     "GATA3"    "GBF1"     "GPR183"

In [6]:
for (term in names(gset)){
    
pb <- AddModuleScore(
  pb, 
  features = gset[term], 
  name = term, 
  assay = "RNA"
) 
    
}

Warning message:
“The following features are not present in the object: FCN3, KIR2DS2, KLRC4-KLRK1, MBL2, NR1H4, PHB1, REG3G, RIGI, S100A14, STING1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: FCGR1BP, FCGR2C, IGHV1-38-4, IGHV1-8, IGHV3-30-3, IGHV3-30-5, IGHV3-38-3, IGHV3-43D, IGHV3-9, IGHV4-30-4, IGHV4-38-2, IGHV8-51-1, IGLL5, IL9, PHB1, TRA, TRB, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: INS, PSMB11, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: DEFB136, MARCHF2, MIRLET7B, UMOD, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: FCGR1BP, FCGR2C, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: DEFB106A, DEFB106B, DEFB114, DEFB119, DEFB136, DEFB4A, RNASE8, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CLEC4M, GBA1, HLA-DRB3, HLA-DRB4, HLA-H, KDM5D, MARCHF1, MARCHF8, RAET1L, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: BTN2A3P, BTNL10P, FYB2, HLA-DRB3, VTCN1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: BPIFA1, CCL11, CCL13, CCL21, CCL3L3, CCL4L1, CST9, CST9L, CST9LP1, CX3CL1, DEFA1, DEFA1B, DEFA4, DEFA5, DEFA6, DEFB118, DEFB126, DEFB127, DEFB4A, DMBT1, FGA, FGB, GALP, H2BC10, H2BC11, H2BC12, H2BC12L, H2BC21, H2BC4, H2BC6, H2BC7, H2BC8, HRG, IL36RN, KRT6A, MUC7, PGLYRP3, PGLYRP4, PRTN3, REG1A, REG3A, REG3G, RNASE7, S100A7, SEMG1, SEMG2, SPAG11A, SPAG11B, SPRR2A, WFDC10A, WFDC11, WFDC12, WFDC13, WFDC9, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: BPIFA1, BPIFA2, BPIFB1, BPIFB2, BPIFB4, BPIFB6, DCD, DEFA1, DEFA1B, DEFA4, DEFA5, DEFA6, DEFB103A, DEFB103B, DEFB104A, DEFB104B, DEFB105A, DEFB105B, DEFB106A, DEFB106B, DEFB107A, DEFB108B, DEFB110, DEFB113, DEFB114, DEFB115, DEFB116, DEFB118, DEFB119, DEFB121, DEFB123, DEFB125, DEFB126, DEFB127, DEFB128, DEFB129, DEFB130A, DEFB130B, DEFB131A, DEFB132, DEFB134, DEFB135, DEFB136, DEFB4A, DEFB4B, EPPIN, EPPIN-WFDC6, HTN1, HTN3, PGLYRP3, PGLYRP4, PLA2G2A, PRTN3, REG3A, REG3G, RNASE7, RNASE8, S100A7, S100A7A, SEMG1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: MARCHF2, MBL2, PHB1, RIGI, STING1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CENPS-CORT, RIGI, TUBAL3, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CHRNA4, IFNA1, IFNA10, IFNA13, IFNA14, IFNA16, IFNA17, IFNA2, IFNA21, IFNA4, IFNA5, IFNA6, IFNA7, IFNA8, IFNB1, IFNE, IFNW1, IL9, MIR19A, PHB1, SANBR, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IFNA1, IFNA10, IFNA13, IFNA14, IFNA16, IFNA17, IFNA2, IFNA21, IFNA4, IFNA5, IFNA6, IFNA7, IFNA8, IFNB1, IFNE, IFNW1, IL9, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IFNA1, IFNA10, IFNA13, IFNA14, IFNA16, IFNA17, IFNA2, IFNA21, IFNA4, IFNA5, IFNA6, IFNA7, IFNA8, IFNB1, IFNE, IFNW1, IL33, KARS1, SANBR, TCIM, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: PRTN3, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: ASB10, ASB18, CBLL2, FGA, FGB, FGG, GPR75-ASB3, KBTBD13, PEDS1-UBE2V1, PSMB11, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: C8A, C8B, CFHR5, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: C8A, C8B, MBL2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: C8A, C8B, CFHR1, CFHR2, CFHR4, CFHR5, FCN3, MASP1, MBL2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: FCN3, MASP1, MBL2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: C4B_2, C8A, C8B, CFHR1, CFHR2, CFHR4, CFHR5, CPN2, CRP, FCN3, MASP1, MBL2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: GPR32, GPR32P1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: HLA-DRB3, HLA-DRB4, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: MUC15, MUC21, MUC5AC, MUC7, PEDS1-UBE2V1, PRKACG, PSMB11, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: STING1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: KIR2DS1, KIR2DS2, KIR2DS4, KIR2DS5, KIR3DS1, KLRC4-KLRK1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IFNA1, IFNA10, IFNA13, IFNA14, IFNA16, IFNA17, IFNA2, IFNA21, IFNA4, IFNA5, IFNA6, IFNA7, IFNA8, IFNB1, RIGI, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: PEDS1-UBE2V1, PSMB11, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: MYH2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CSH1, GH2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: BPIFA1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: TRA, TRB, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CD300LG, COL3A1, KIR2DL2, KIR2DS1, KIR2DS2, KLRC4-KLRK1, LILRA3, LOC102725035, LOC107987462, SIGLEC8, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: FCGR1BP, FCGR2C, IL1F10, IL25, IL36B, IL36RN, IL37, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: FCN3, KIR2DS2, KLRC4-KLRK1, MBL2, S100A14, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: FCN3, KIR2DS2, KLRC4-KLRK1, MBL2, NR1H4, PHB1, REG3G, RIGI, S100A14, STING1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: BPIFB1, DEFA1, DEFA1B, DEFA4, DEFA5, DEFA6, H2BC10, H2BC11, H2BC12, H2BC12L, H2BC21, H2BC4, H2BC6, H2BC7, H2BC8, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IFNA1, IFNA10, IFNA13, IFNA14, IFNA16, IFNA17, IFNA2, IFNA21, IFNA4, IFNA5, IFNA6, IFNA7, IFNA8, IFNB1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: HLA-DRB3, HLA-DRB4, TRIM29, TRIM48, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CCL3L3, CCL4L1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IL25, PEDS1-UBE2V1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IL1F10, IL33, IL36B, IL36RN, IL37, PEDS1-UBE2V1, PSMB11, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IFNL2, IFNL3, IL20RA, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IL9, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CCL11, MMP3, SOX2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CNTFR, IL31, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: H3C1, H3C10, H3C11, H3C12, H3C13, H3C14, H3C15, H3C2, H3C3, H3C4, H3C6, H3C7, H3C8, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IFNA1, IFNA10, IFNA13, IFNA14, IFNA16, IFNA17, IFNA2, IFNA21, IFNA4, IFNA5, IFNA6, IFNA7, IFNA8, IFNB1, IFNE, IFNW1, IL33, KARS1, SANBR, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CX3CL1, IL33, MIR181C, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CX3CL1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CCL11, CCL13, CCL21, CCL3L3, CCL4L1, CD300H, CX3CL1, DEFA1, DEFA1B, DEFB104A, DEFB104B, GPR15LG, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: GPR15LG, GRP, PLA2G3, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CHST3, FOXN1, GPR15LG, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: FCGR1BP, FCGR2C, KLRC4-KLRK1, TRA, TRB, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: FCGR1BP, FCGR2C, IGHV1-38-4, IGHV1-8, IGHV3-30-3, IGHV3-30-5, IGHV3-38-3, IGHV3-43D, IGHV3-9, IGHV4-30-4, IGHV4-38-2, IGHV8-51-1, IGLL5, IL9, KLRC4-KLRK1, TRA, TRB, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CX3CL1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IFNA1, IFNA10, IFNA13, IFNA14, IFNA16, IFNA17, IFNA2, IFNA21, IFNA4, IFNA5, IFNA6, IFNA7, IFNA8, IFNB1, IFNE, IFNW1, SANBR, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CCL21, EFNB3, KLRC4-KLRK1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IFNA1, IFNA10, IFNA13, IFNA14, IFNA16, IFNA17, IFNA2, IFNA21, IFNA4, IFNA5, IFNA6, IFNA7, IFNA8, IFNB1, IFNE, IFNW1, IL9, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CAPZA3, HLA-DRB3, HLA-DRB4, KIF2B, KIF4B, TUBAL3, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CCL21, CX3CL1, DEFA1, DEFA1B, DEFB104A, DEFB104B, GBA1, GPR15LG, H2BC1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CX3CL1, IL33, ITGB6, KARS1, MIR181C, PLA2G3, PRG3, UBD, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CCL11, CCL13, CCL3L3, CCL4L1, CD300H, CX3CL1, DEFB104A, DEFB104B, GP2, PRTN3, UMOD, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IFNA1, IFNA10, IFNA13, IFNA14, IFNA16, IFNA17, IFNA2, IFNA21, IFNA4, IFNA5, IFNA6, IFNA7, IFNA8, IFNB1, IFNE, IFNW1, KIR3DS1, KLRC4-KLRK1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: KLRC4-KLRK1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: KLRC4-KLRK1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: MIR34A, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: ZNRF4, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: ADIPOQ, APCS, CARTPT, CLDN18, IAPP, IFNA2, IFNB1, MIR125B1, MIR21, MIR221, MIR222, MIR30B, MIR486-1, PGLYRP3, SFRP1, SNAI2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: FOXF1, IFNA2, IFNB1, IL33, INS, MIR302A, PGLYRP3, SERPINB4, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: COL3A1, DRD2, GPX1, IFNA2, IFNB1, IL33, INS, MIR105-1, MIR181B1, MIR19A, MIR19B1, MIR21, MIR302E, MIR6869, MMP12, NPY5R, OTOP1, PGLYRP3, SERPINB4, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: GAL, IFNA2, IFNB1, MARCHF7, MIR125A, MIR130A, MIR181C, MIR185, MIR21, MIR27A, MIR30B, PGLYRP3, PLA2G2A, PLA2G2E, SFRP1, TAFA3, VTCN1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: BMP5, CCL21, CXCL12, IL33, KLRC4-KLRK1, MICOS10-NBL1, MIR128-1, MIR146A, MIR223, MIR24-1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: INS, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: BPIFB1, MIR140, MIR146A, MIR149, MIR200B, MIR200C, MIR20A, MIR708, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: MIR17, MIR19A, NLRP2B, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: ACP3, CALML5, CEACAM6, CRISP3, DEFA1, DEFA1B, DEFA4, DSG1, FLG2, IRAG2, LILRA3, LOC102725035, LOC107987462, MMP8, NME1-NME2, OLFM4, PKP1, PRG3, PRTN3, S100A7, SERPINA3, SERPINB12, SERPINB3, STING1, TMED7-TICAM2, TMT1A, TTR, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: PEDS1-UBE2V1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CRP, MBL2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: BPIFB1, DEFA1, DEFA1B, DEFA4, DEFA5, DEFA6, H2BC10, H2BC11, H2BC12, H2BC12L, H2BC21, H2BC4, H2BC6, H2BC7, H2BC8, IFNL2, UMOD, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: PRTN3, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IGKV2-40, IGKV6D-41, IGLV11-55, IGLV3-32, IGLV5-39, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CSH1, GH2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: PRKACG, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: ATP6V1B1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: PSMB11, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: SANBR, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: KLRC4-KLRK1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IFNA1, IFNA10, IFNA13, IFNA14, IFNA16, IFNA17, IFNA2, IFNA21, IFNA4, IFNA5, IFNA6, IFNA7, IFNA8, IFNB1, IFNE, IFNW1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CCL21, EFNB3, KLRC4-KLRK1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: GBA1, PSMB11, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: TRA, TRB, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: TRA, TRB, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: HLA-DRB3, HLA-DRB4, PEDS1-UBE2V1, PSMB11, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: PSMB11, TNFSF12-TNFSF13, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: APOB, FGA, FGB, FGG, PEDS1-UBE2V1, SFTPA2, TASL, TMED7-TICAM2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: IL33, not searching for symbol synonyms”

In [7]:
gset <- parse_gmt("data/11_genesets/h.all.v2024.1.Hs.symbols.gmt")
gset

$HALLMARK_ADIPOGENESIS
  [1] "ABCA1"    "ABCB8"    "ACAA2"    "ACADL"    "ACADM"    "ACADS"
  [7] "ACLY"     "ACO2"     "ACOX1"    "ADCY6"    "ADIG"     "ADIPOQ"
 [13] "ADIPOR2"  "AGPAT3"   "AIFM1"    "AK2"      "ALDH2"    "ALDOA"
 [19] "ANGPT1"   "ANGPTL4"  "APLP2"    "APOE"     "ARAF"     "ARL4A"
 [25] "ATL2"     "ATP1B3"   "ATP5PO"   "BAZ2A"    "BCKDHA"   "BCL2L13"
 [31] "BCL6"     "C3"       "CAT"      "CAVIN1"   "CAVIN2"   "CCNG2"
 [37] "CD151"    "CD302"    "CD36"     "CDKN2C"   "CHCHD10"  "CHUK"
 [43] "CIDEA"    "CMBL"     "CMPK1"    "COL15A1"  "COL4A1"   "COQ3"
 [49] "COQ5"     "COQ9"     "COX6A1"   "COX7B"    "COX8A"    "CPT2"
 [55] "CRAT"     "CS"       "CYC1"     "CYP4B1"   "DBT"      "DDT"
 [61] "DECR1"    "DGAT1"    "DHCR7"    "DHRS7"    "DHRS7B"   "DLAT"
 [67] "DLD"      "DNAJB9"   "DNAJC15"  "DRAM2"    "ECH1"     "ECHS1"
 [73] "ELMOD3"   "ELOVL6"   "ENPP2"    "EPHX2"    "ESRRA"    "ESYT1"
 [79] "ETFB"     "FABP4"    "FAH"      "FZD4"     "G3BP2"    "GADD45A"
 [85] "GBE1"     "GHITM"    "GPAM"     "GPAT4"    "GPD2"     "GPHN"
 [91] "GPX3"     "GPX4"     "GRPEL1"   "HADH"     "HIBCH"    "HSPB8"
 [97] "IDH1"     "IDH3A"    "IDH3G"    "IFNGR1"   "IMMT"     "ITGA7"
[103] "ITIH5"    "ITSN1"    "JAGN1"    "LAMA4"    "LEP"      "LIFR"
[109] "LIPE"     "LPCAT3"   "LPL"      "LTC4S"    "MAP4K3"   "MCCC1"
[115] "MDH2"     "ME1"      "MGLL"     "MGST3"    "MIGA2"    "MRAP"
[121] "MRPL15"   "MTARC2"   "MTCH2"    "MYLK"     "NABP1"    "NDUFA5"
[127] "NDUFAB1"  "NDUFB7"   "NDUFS3"   "NKIRAS1"  "NMT1"     "OMD"
[133] "ORM1"     "PDCD4"    "PEMT"     "PEX14"    "PFKFB3"   "PFKL"
[139] "PGM1"     "PHLDB1"   "PHYH"     "PIM3"     "PLIN2"    "POR"
[145] "PPARG"    "PPM1B"    "PPP1R15B" "PRDX3"    "PREB"     "PTCD3"
[151] "PTGER3"   "QDPR"     "RAB34"    "REEP5"    "REEP6"    "RETN"
[157] "RETSAT"   "RIOK3"    "RMDN3"    "RNF11"    "RREB1"    "RTN3"
[163] "SAMM50"   "SCARB1"   "SCP2"     "SDHB"     "SDHC"     "SLC19A1"
[169] "SLC1A5"   "SLC25A1"  "SLC25A10" "SLC27A1"  "SLC5A6"   "SLC66A3"
[175] "SNCG"     "SOD1"     "SORBS1"   "SOWAHC"   "SPARCL1"  "SQOR"
[181] "SSPN"     "STAT5A"   "STOM"     "SUCLG1"   "SULT1A1"  "TALDO1"
[187] "TANK"     "TKT"      "TOB1"     "TST"      "UBC"      "UBQLN1"
[193] "UCK1"     "UCP2"     "UQCR10"   "UQCR11"   "UQCRC1"   "UQCRQ"
[199] "VEGFB"    "YWHAG"

$HALLMARK_ALLOGRAFT_REJECTION
  [1] "AARS1"    "ABCE1"    "ABI1"     "ACHE"     "ACVR2A"   "AKT1"
  [7] "APBB1"    "B2M"      "BCAT1"    "BCL10"    "BCL3"     "BRCA1"
 [13] "C2"       "CAPG"     "CARTPT"   "CCL11"    "CCL13"    "CCL19"
 [19] "CCL2"     "CCL22"    "CCL4"     "CCL5"     "CCL7"     "CCND2"
 [25] "CCND3"    "CCR1"     "CCR2"     "CCR5"     "CD1D"     "CD2"
 [31] "CD247"    "CD28"     "CD3D"     "CD3E"     "CD3G"     "CD4"
 [37] "CD40"     "CD40LG"   "CD47"     "CD7"      "CD74"     "CD79A"
 [43] "CD80"     "CD86"     "CD8A"     "CD8B"     "CD96"     "CDKN2A"
 [49] "CFP"      "CRTAM"    "CSF1"     "CSK"      "CTSS"     "CXCL13"
 [55] "CXCL9"    "CXCR3"    "DARS1"    "DEGS1"    "DYRK3"    "EGFR"
 [61] "EIF3A"    "EIF3D"    "EIF3J"    "EIF4G3"   "EIF5A"    "ELANE"
 [67] "ELF4"     "EREG"     "ETS1"     "F2"       "F2R"      "FAS"
 [73] "FASLG"    "FCGR2B"   "FGR"      "FLNA"     "FYB1"     "GALNT1"
 [79] "GBP2"     "GCNT1"    "GLMN"     "GPR65"    "GZMA"     "GZMB"
 [85] "HCLS1"    "HDAC9"    "HIF1A"    "HLA-A"    "HLA-DMA"  "HLA-DMB"
 [91] "HLA-DOA"  "HLA-DOB"  "HLA-DQA1" "HLA-DRA"  "HLA-E"    "HLA-G"
 [97] "ICAM1"    "ICOSLG"   "IFNAR2"   "IFNG"     "IFNGR1"   "IFNGR2"
[103] "IGSF6"    "IKBKB"    "IL10"     "IL11"     "IL12A"    "IL12B"
[109] "IL12RB1"  "IL13"     "IL15"     "IL16"     "IL18"     "IL18RAP"
[115] "IL1B"     "IL2"      "IL27RA"   "IL2RA"    "IL2RB"    "IL2RG"
[121] "IL4"      "IL4R"     "IL6"      "IL7"      "IL9"      "INHBA"
[127] "INHBB"    "IRF4"     "IRF7"     "IRF8"     "ITGAL"    "ITGB2"
[133] "ITK"      "JAK2"     "KLRD1"    "KRT1"     "LCK"      "LCP2"
[139] "LIF"      "LTB"      "LY75"     "LY86"     "LYN"      "MAP3K7"
[145] "MAP4K1"   "MBL2"     "MMP9"     "MRPL3"    "MTIF2"    "NCF4"
[151] "NCK1"     "NCR1"     "NLRP3"    "NME1"     "NOS2"     "NPM1"
[157] "PF4"      "PRF1"     "PRKCB"    "PRKCG"    "PSMB10"   "PTPN6"
[163] "PTPRC"    "RARS1"    "RIPK2"    "RPL39"    "RPL3L"    "RPL9"
[169] "RPS19"    "RPS3A"    "RPS9"     "SIT1"     "SOCS1"    "SOCS5"
[175] "SPI1"     "SRGN"     "ST8SIA4"  "STAB1"    "STAT1"    "STAT4"
[181] "TAP1"     "TAP2"     "TAPBP"    "TGFB1"    "TGFB2"    "THY1"
[187] "TIMP1"    "TLR1"     "TLR2"     "TLR3"     "TLR6"     "TNF"
[193] "TPD52"    "TRAF2"    "TRAT1"    "UBE2D1"   "UBE2N"    "WARS1"
[199] "WAS"      "ZAP70"

$HALLMARK_ANDROGEN_RESPONSE
  [1] "ABCC4"    "ABHD2"    "ACSL3"    "ACTN1"    "ADAMTS1"  "ADRM1"
  [7] "AKAP12"   "AKT1"     "ALDH1A3"  "ANKH"     "APPBP2"   "ARID5B"
 [13] "AZGP1"    "B2M"      "B4GALT1"  "BMPR1B"   "CAMKK2"   "CCND1"
 [19] "CCND3"    "CDC14B"   "CDK6"     "CENPN"    "DBI"      "DHCR24"
 [25] "DNAJB9"   "ELK4"     "ELL2"     "ELOVL5"   "FADS1"    "FKBP5"
 [31] "GNAI3"    "GPD1L"    "GSR"      "GUCY1A1"  "H1-0"     "HERC3"
 [37] "HMGCR"    "HMGCS1"   "HOMER2"   "HPGD"     "HSD17B14" "IDI1"
 [43] "INPP4B"   "INSIG1"   "IQGAP2"   "ITGAV"    "KLK2"     "KLK3"
 [49] "KRT19"    "KRT8"     "LIFR"     "LMAN1"    "MAF"      "MAK"
 [55] "MAP7"     "MERTK"    "MYL12A"   "NCOA4"    "NDRG1"    "NGLY1"
 [61] "NKX3-1"   "PA2G4"    "PDLIM5"   "PGM3"     "PIAS1"    "PLPP1"
 [67] "PMEPA1"   "PTK2B"    "PTPN21"   "RAB4A"    "RPS6KA3"  "RRP12"
 [73] "SAT1"     "SCD"      "SEC24D"   "SELENOP"  "SGK1"     "SLC26A2"
 [79] "SLC38A2"  "SMS"      "SORD"     "SPCS3"    "SPDEF"    "SRF"
 [85] "SRP19"    "STEAP4"   "STK39"    "TARP"     "TMEM50A"  "TMPRSS2"
 [91] "TNFAIP8"  "TPD52"    "TSC22D1"  "UAP1"     "UBE2I"    "UBE2J1"
 [97] "VAPA"     "XRCC5"    "XRCC6"    "ZBTB10"   "ZMIZ1"

$HALLMARK_ANGIOGENESIS
 [1] "APOH"     "APP"      "CCND2"    "COL3A1"   "COL5A2"   "CXCL6"
 [7] "FGFR1"    "FSTL1"    "ITGAV"    "JAG1"     "JAG2"     "KCNJ8"
[13] "LPL"      "LRPAP1"   "LUM"      "MSX1"     "NRP1"     "OLR1"
[19] "PDGFA"    "PF4"      "PGLYRP1"  "POSTN"    "PRG2"     "PTK2"
[25] "S100A4"   "SERPINA5" "SLCO2A1"  "SPP1"     "STC1"     "THBD"
[31] "TIMP1"    "TNFRSF21" "VAV2"     "VCAN"     "VEGFA"    "VTN"

$HALLMARK_APICAL_JUNCTION
  [1] "ACTA1"     "ACTB"      "ACTC1"     "ACTG1"     "ACTG2"     "ACTN1"
  [7] "ACTN2"     "ACTN3"     "ACTN4"     "ADAM15"    "ADAM23"    "ADAM9"
 [13] "ADAMTS5"   "ADRA1B"    "AKT2"      "AKT3"      "ALOX15B"   "AMH"
 [19] "AMIGO1"    "AMIGO2"    "ARHGEF6"   "ARPC2"     "ATP1A3"    "B4GALT1"
 [25] "BAIAP2"    "BMP1"      "CADM2"     "CADM3"     "CALB2"     "CAP1"
 [31] "CD209"     "CD274"     "CD276"     "CD34"      "CD86"      "CD99"
 [37] "CDH1"      "CDH11"     "CDH15"     "CDH3"      "CDH4"      "CDH6"
 [43] "CDH8"      "CDK8"      "CDSN"      "CERCAM"    "CLDN11"    "CLDN14"
 [49] "CLDN15"    "CLDN18"    "CLDN19"    "CLDN4"     "CLDN5"     "CLDN6"
 [55] "CLDN7"     "CLDN8"     "CLDN9"     "CNN2"      "CNTN1"     "COL16A1"
 [61] "COL17A1"   "COL9A1"    "CRAT"      "CRB3"      "CTNNA1"    "CTNND1"
 [67] "CX3CL1"    "DHX16"     "DLG1"      "DMP1"      "DSC1"      "DSC3"
 [73] "EGFR"      "EPB41L2"   "EVL"       "EXOC4"     "FBN1"      "FLNC"
 [79] "FSCN1"     "FYB1"      "GAMT"      "GNAI1"     "GNAI2"     "GRB7"
 [85] "GTF2F1"    "HADH"      "HRAS"      "ICAM1"     "ICAM2"     "ICAM4"
 [91] "ICAM5"     "IKBKG"     "INPPL1"    "INSIG1"    "IRS1"      "ITGA10"
 [97] "ITGA2"     "ITGA3"     "ITGA9"     "ITGB1"     "ITGB4"     "JAM3"
[103] "JUP"       "KCNH2"     "KRT31"     "LAMA3"     "LAMB3"     "LAMC2"
[109] "LAYN"      "LDLRAP1"   "LIMA1"     "MADCAM1"   "MAP3K20"   "MAP4K2"
[115] "MAPK11"    "MAPK13"    "MAPK14"    "MDK"       "MMP2"      "MMP9"
[121] "MPZL1"     "MPZL2"     "MSN"       "MVD"       "MYH10"     "MYH9"
[127] "MYL12B"    "MYL9"      "NECTIN1"   "NECTIN2"   "NECTIN3"   "NECTIN4"
[133] "NEGR1"     "NEXN"      "NF1"       "NF2"       "NFASC"     "NHERF4"
[139] "NLGN2"     "NLGN3"     "NRAP"      "NRTN"      "NRXN2"     "PALS1"
[145] "PARD6G"    "PARVA"     "PBX2"      "PCDH1"     "PECAM1"    "PFN1"
[151] "PIK3CB"    "PIK3R3"    "PKD1"      "PLCG1"     "PPP2R2C"   "PTEN"
[157] "PTK2"      "PTPRC"     "RAC2"      "RASA1"     "RHOF"      "RRAS"
[163] "RSU1"      "SDC3"      "SGCE"      "SHC1"      "SHROOM2"   "SIRPA"
[169] "SKAP2"     "SLC30A3"   "SLIT2"     "SORBS3"    "SPEG"      "SRC"
[175] "STX4"      "SYK"       "SYMPK"     "TAOK2"     "TGFBI"     "THBS3"
[181] "THY1"      "TIAL1"     "TJP1"      "TMEM8B"    "TNFRSF11B" "TRAF1"
[187] "TRO"       "TSC1"      "TSPAN4"    "TUBG1"     "VASP"      "VAV2"
[193] "VCAM1"     "VCAN"      "VCL"       "VWF"       "WASL"      "WNK4"
[199] "YWHAH"     "ZYX"

$HALLMARK_APICAL_SURFACE
 [1] "ADAM10"   "ADIPOR2"  "AFAP1L2"  "AKAP7"    "APP"      "ATP6V0A4"
 [7] "ATP8B1"   "B4GALT1"  "BRCA1"    "CD160"    "CROCC"    "CRYBG1"
[13] "CX3CL1"   "DCBLD2"   "EFNA5"    "EPHB4"    "FLOT2"    "GAS1"
[19] "GATA3"    "GHRL"     "GSTM3"    "HSPB1"    "IL2RB"    "IL2RG"
[25] "LYN"      "LYPD3"    "MAL"      "MDGA1"    "NCOA6"    "NTNG1"
[31] "PCSK9"    "PKHD1"    "PLAUR"    "RHCG"     "RTN4RL1"  "SCUBE1"
[37] "SHROOM2"  "SLC22A12" "SLC2A4"   "SLC34A3"  "SRPX"     "SULF2"
[43] "THY1"     "TMEM8B"

$HALLMARK_APOPTOSIS
  [1] "ADD1"      "AIFM3"     "ANKH"      "ANXA1"     "APP"       "ATF3"
  [7] "AVPR1A"    "BAX"       "BCAP31"    "BCL10"     "BCL2L1"    "BCL2L10"
 [13] "BCL2L11"   "BCL2L2"    "BGN"       "BID"       "BIK"       "BIRC3"
 [19] "BMF"       "BMP2"      "BNIP3L"    "BRCA1"     "BTG2"      "BTG3"
 [25] "CASP1"     "CASP2"     "CASP3"     "CASP4"     "CASP6"     "CASP7"
 [31] "CASP8"     "CASP9"     "CAV1"      "CCNA1"     "CCND1"     "CCND2"
 [37] "CD14"      "CD2"       "CD38"      "CD44"      "CD69"      "CDC25B"
 [43] "CDK2"      "CDKN1A"    "CDKN1B"    "CFLAR"     "CLU"       "CREBBP"
 [49] "CTH"       "CTNNB1"    "CYLD"      "DAP"       "DAP3"      "DCN"
 [55] "DDIT3"     "DFFA"      "DIABLO"    "DNAJA1"    "DNAJC3"    "DNM1L"
 [61] "DPYD"      "EBP"       "EGR3"      "EMP1"      "ENO2"      "ERBB2"
 [67] "ERBB3"     "EREG"      "ETF1"      "F2"        "F2R"       "FAS"
 [73] "FASLG"     "FDXR"      "FEZ1"      "GADD45A"   "GADD45B"   "GCH1"
 [79] "GNA15"     "GPX1"      "GPX3"      "GPX4"      "GSN"       "GSR"
 [85] "GSTM1"     "GUCY2D"    "H1-0"      "HGF"       "HMGB2"     "HMOX1"
 [91] "HSPB1"     "IER3"      "IFITM3"    "IFNB1"     "IFNGR1"    "IGF2R"
 [97] "IGFBP6"    "IL18"      "IL1A"      "IL1B"      "IL6"       "IRF1"
[103] "ISG20"     "JUN"       "KRT18"     "LEF1"      "LGALS3"    "LMNA"
[109] "LUM"       "MADD"      "MCL1"      "MGMT"      "MMP2"      "NEDD9"
[115] "NEFH"      "PAK1"      "PDCD4"     "PDGFRB"    "PEA15"     "PLAT"
[121] "PLCB2"     "PLPPR4"    "PMAIP1"    "PPP2R5B"   "PPP3R1"    "PPT1"
[127] "PRF1"      "PSEN1"     "PSEN2"     "PTK2"      "RARA"      "RELA"
[133] "RETSAT"    "RHOB"      "RHOT2"     "RNASEL"    "ROCK1"     "SAT1"
[139] "SATB1"     "SC5D"      "SLC20A1"   "SMAD7"     "SOD1"      "SOD2"
[145] "SPTAN1"    "SQSTM1"    "TAP1"      "TGFB2"     "TGFBR3"    "TIMP1"
[151] "TIMP2"     "TIMP3"     "TNF"       "TNFRSF12A" "TNFSF10"   "TOP2A"
[157] "TSPO"      "TXNIP"     "VDAC2"     "WEE1"      "XIAP"

$HALLMARK_BILE_ACID_METABOLISM
  [1] "ABCA1"    "ABCA2"    "ABCA3"    "ABCA4"    "ABCA5"    "ABCA6"
  [7] "ABCA8"    "ABCA9"    "ABCD1"    "ABCD2"    "ABCD3"    "ABCG4"
 [13] "ABCG8"    "ACSL1"    "ACSL5"    "AGXT"     "AKR1D1"   "ALDH1A1"
 [19] "ALDH8A1"  "ALDH9A1"  "AMACR"    "APOA1"    "AQP9"     "AR"
 [25] "ATXN1"    "BBOX1"    "BCAR3"    "BMP6"     "CAT"      "CH25H"
 [31] "CROT"     "CYP27A1"  "CYP39A1"  "CYP46A1"  "CYP7A1"   "CYP7B1"
 [37] "CYP8B1"   "DHCR24"   "DIO1"     "DIO2"     "EFHC1"    "EPHX2"
 [43] "FADS1"    "FADS2"    "FDXR"     "GC"       "GCLM"     "GNMT"
 [49] "GNPAT"    "GSTK1"    "HACL1"    "HAO1"     "HSD17B11" "HSD17B4"
 [55] "HSD17B6"  "HSD3B1"   "HSD3B7"   "IDH1"     "IDH2"     "IDI1"
 [61] "ISOC1"    "KLF1"     "LCK"      "LIPE"     "LONP2"    "MLYCD"
 [67] "NEDD4"    "NPC1"     "NR0B2"    "NR1H4"    "NR1I2"    "NR3C2"
 [73] "NUDT12"   "OPTN"     "PAOX"     "PECR"     "PEX1"     "PEX11A"
 [79] "PEX11G"   "PEX12"    "PEX13"    "PEX16"    "PEX19"    "PEX26"
 [85] "PEX6"     "PEX7"     "PFKM"     "PHYH"     "PIPOX"    "PNPLA8"
 [91] "PRDX5"    "PXMP2"    "RBP1"     "RETSAT"   "RXRA"     "RXRG"
 [97] "SCP2"     "SERPINA6" "SLC22A18" "SLC23A1"  "SLC23A2"  "SLC27A2"
[103] "SLC27A5"  "SLC29A1"  "SLC35B2"  "SLCO1A2"  "SOAT2"    "SOD1"
[109] "SULT1B1"  "SULT2B1"  "TFCP2L1"  "TTR"

$HALLMARK_CHOLESTEROL_HOMEOSTASIS
 [1] "ABCA2"     "ACAT2"     "ACSS2"     "ACTG1"     "ADH4"      "ALCAM"
 [7] "ALDOC"     "ANTXR2"    "ANXA13"    "ANXA5"     "ATF3"      "ATF5"
[13] "ATXN2"     "AVPR1A"    "CBS"       "CD9"       "CHKA"      "CLU"
[19] "CPEB2"     "CTNNB1"    "CXCL16"    "CYP51A1"   "DHCR7"     "EBP"
[25] "ECH1"      "ERRFI1"    "ETHE1"     "FABP5"     "FADS2"     "FASN"
[31] "FBXO6"     "FDFT1"     "FDPS"      "GLDC"      "GNAI1"     "GPX8"
[37] "GSTM2"     "GUSB"      "HMGCR"     "HMGCS1"    "HSD17B7"   "IDI1"
[43] "JAG1"      "LDLR"      "LGALS3"    "LGMN"      "LPL"       "LSS"
[49] "MAL2"      "MVD"       "MVK"       "NFIL3"     "NIBAN1"    "NSDHL"
[55] "PCYT2"     "PDK3"      "PLAUR"     "PLSCR1"    "PMVK"      "PNRC1"
[61] "PPARG"     "S100A11"   "SC5D"      "SCD"       "SEMA3B"    "SQLE"
[67] "SREBF2"    "STARD4"    "STX5"      "TM7SF2"    "TMEM97"    "TNFRSF12A"
[73] "TP53INP1"  "TRIB3"

$HALLMARK_COAGULATION
  [1] "A2M"      "ACOX2"    "ADAM9"    "ANG"      "ANXA1"    "APOA1"
  [7] "APOC1"    "APOC2"    "APOC3"    "ARF4"     "BMP1"     "C1QA"
 [13] "C1R"      "C1S"      "C2"       "C3"       "C8A"      "C8B"
 [19] "C8G"      "C9"       "CAPN2"    "CAPN5"    "CASP9"    "CD9"
 [25] "CFB"      "CFD"      "CFH"      "CFI"      "CLU"      "COMP"
 [31] "CPB2"     "CPN1"     "CPQ"      "CRIP2"    "CSRP1"    "CTSB"
 [37] "CTSE"     "CTSH"     "CTSK"     "CTSO"     "CTSV"     "DCT"
 [43] "DPP4"     "DUSP14"   "DUSP6"    "F10"      "F11"      "F12"
 [49] "F13B"     "F2"       "F2RL2"    "F3"       "F8"       "F9"
 [55] "FBN1"     "FGA"      "FGG"      "FN1"      "FURIN"    "FYN"
 [61] "GDA"      "GNB2"     "GNG12"    "GP1BA"    "GP9"      "GSN"
 [67] "HMGCS2"   "HNF4A"    "HPN"      "HRG"      "HTRA1"    "ISCU"
 [73] "ITGA2"    "ITGB3"    "ITIH1"    "KLF7"     "KLK8"     "KLKB1"
 [79] "LAMP2"    "LEFTY2"   "LGMN"     "LRP1"     "LTA4H"    "MAFF"
 [85] "MASP2"    "MBL2"     "MEP1A"    "MMP1"     "MMP10"    "MMP11"
 [91] "MMP14"    "MMP15"    "MMP2"     "MMP3"     "MMP7"     "MMP8"
 [97] "MMP9"     "MSRB2"    "MST1"     "OLR1"     "P2RY1"    "PDGFB"
[103] "PECAM1"   "PEF1"     "PF4"      "PLAT"     "PLAU"     "PLEK"
[109] "PLG"      "PREP"     "PROC"     "PROS1"    "PROZ"     "PRSS23"
[115] "RABIF"    "RAC1"     "RAPGEF3"  "RGN"      "S100A1"   "S100A13"
[121] "SERPINA1" "SERPINB2" "SERPINC1" "SERPINE1" "SERPING1" "SH2B2"
[127] "SIRT2"    "SPARC"    "TF"       "TFPI2"    "THBD"     "THBS1"
[133] "TIMP1"    "TIMP3"    "TMPRSS6"  "USP11"    "VWF"      "WDR1"

$HALLMARK_COMPLEMENT
  [1] "ACTN2"    "ADAM9"    "ADRA2B"   "AKAP10"   "ANG"      "ANXA5"
  [7] "APOA4"    "APOBEC3F" "APOBEC3G" "APOC1"    "ATOX1"    "BRPF3"
 [13] "C1QA"     "C1QC"     "C1R"      "C1S"      "C2"       "C3"
 [19] "C4BPB"    "C9"       "CA2"      "CALM1"    "CALM3"    "CASP1"
 [25] "CASP10"   "CASP3"    "CASP4"    "CASP5"    "CASP7"    "CASP9"
 [31] "CBLB"     "CCL5"     "CD36"     "CD40LG"   "CD46"     "CD55"
 [37] "CD59"     "CDA"      "CDH13"    "CDK5R1"   "CEBPB"    "CFB"
 [43] "CFH"      "CLU"      "COL4A2"   "CP"       "CPM"      "CPQ"
 [49] "CR1"      "CR2"      "CSRP1"    "CTSB"     "CTSC"     "CTSD"
 [55] "CTSH"     "CTSL"     "CTSO"     "CTSS"     "CTSV"     "CXCL1"
 [61] "DGKG"     "DGKH"     "DOCK10"   "DOCK4"    "DOCK9"    "DPP4"
 [67] "DUSP5"    "DUSP6"    "DYRK2"    "EHD1"     "ERAP2"    "F10"
 [73] "F2"       "F3"       "F5"       "F7"       "F8"       "FCER1G"
 [79] "FCN1"     "FDX1"     "FN1"      "FYN"      "GATA3"    "GCA"
 [85] "GMFB"     "GNAI2"    "GNAI3"    "GNB2"     "GNB4"     "GNG2"
 [91] "GNGT2"    "GP1BA"    "GP9"      "GPD2"     "GRB2"     "GZMA"
 [97] "GZMB"     "GZMK"     "HNF4A"    "HPCAL4"   "HSPA1A"   "HSPA5"
[103] "IL6"      "IRF1"     "IRF2"     "IRF7"     "ITGAM"    "ITIH1"
[109] "JAK2"     "KCNIP2"   "KCNIP3"   "KIF2A"    "KLK1"     "KLKB1"
[115] "KYNU"     "L3MBTL4"  "LAMP2"    "LAP3"     "LCK"      "LCP2"
[121] "LGALS3"   "LGMN"     "LIPA"     "LRP1"     "LTA4H"    "LTF"
[127] "LYN"      "MAFF"     "ME1"      "MMP12"    "MMP13"    "MMP14"
[133] "MMP15"    "MMP8"     "MSRB1"    "MT3"      "NOTCH4"   "OLR1"
[139] "PCLO"     "PCSK9"    "PDGFB"    "PDP1"     "PFN1"     "PHEX"
[145] "PIK3CA"   "PIK3CG"   "PIK3R5"   "PIM1"     "PLA2G4A"  "PLA2G7"
[151] "PLAT"     "PLAUR"    "PLEK"     "PLG"      "PLSCR1"   "PPP2CB"
[157] "PPP4C"    "PRCP"     "PRDM4"    "PREP"     "PRKCD"    "PRSS3"
[163] "PRSS36"   "PSEN1"    "PSMB9"    "RABIF"    "RAF1"     "RASGRP1"
[169] "RBSN"     "RCE1"     "RHOG"     "RNF4"     "S100A12"  "S100A13"
[175] "S100A9"   "SCG3"     "SERPINA1" "SERPINB2" "SERPINC1" "SERPINE1"
[181] "SERPING1" "SH2B3"    "SIRT6"    "SPOCK2"   "SRC"      "STX4"
[187] "TFPI2"    "TIMP1"    "TIMP2"    "TMPRSS6"  "TNFAIP3"  "USP14"
[193] "USP15"    "USP16"    "USP8"     "VCPIP1"   "WAS"      "XPNPEP1"
[199] "ZEB1"     "ZFPM2"

$HALLMARK_DNA_REPAIR
  [1] "AAAS"    "ADA"     "ADCY6"   "ADRM1"   "AGO4"    "AK1"     "AK3"
  [8] "ALYREF"  "APRT"    "ARL6IP1" "BCAM"    "BCAP31"  "BOLA2"   "BRF2"
 [15] "CANT1"   "CCNO"    "CDA"     "CETN2"   "CLP1"    "CMPK2"   "COX17"
 [22] "CSTF3"   "DAD1"    "DCTN4"   "DDB1"    "DDB2"    "DGCR8"   "DGUOK"
 [29] "DUT"     "EDF1"    "EIF1B"   "ELL"     "ELOA"    "ERCC1"   "ERCC2"
 [36] "ERCC3"   "ERCC4"   "ERCC5"   "ERCC8"   "FEN1"    "GMPR2"   "GPX4"
 [43] "GSDME"   "GTF2A2"  "GTF2B"   "GTF2F1"  "GTF2H1"  "GTF2H3"  "GTF2H5"
 [50] "GTF3C5"  "GUK1"    "HCLS1"   "HPRT1"   "IMPDH2"  "ITPA"    "LIG1"
 [57] "MPC2"    "MPG"     "MRPL40"  "NCBP2"   "NELFB"   "NELFCD"  "NELFE"
 [64] "NFX1"    "NME1"    "NME3"    "NME4"    "NPR2"    "NT5C"    "NT5C3A"
 [71] "NUDT21"  "NUDT9"   "PCNA"    "PDE4B"   "PDE6G"   "PNP"     "POLA1"
 [78] "POLA2"   "POLB"    "POLD1"   "POLD3"   "POLD4"   "POLE4"   "POLH"
 [85] "POLL"    "POLR1C"  "POLR1D"  "POLR1H"  "POLR2A"  "POLR2C"  "POLR2D"
 [92] "POLR2E"  "POLR2F"  "POLR2G"  "POLR2H"  "POLR2I"  "POLR2J"  "POLR2K"
 [99] "POLR3C"  "POLR3GL" "POM121"  "PRIM1"   "RAD51"   "RAD52"   "RAE1"
[106] "RALA"    "RBX1"    "REV3L"   "RFC2"    "RFC3"    "RFC4"    "RFC5"
[113] "RNMT"    "RPA2"    "RPA3"    "RRM2B"   "SAC3D1"  "SDCBP"   "SEC61A1"
[120] "SF3A3"   "SMAD5"   "SNAPC4"  "SNAPC5"  "SRSF6"   "SSRP1"   "STX3"
[127] "SUPT4H1" "SUPT5H"  "SURF1"   "TAF10"   "TAF12"   "TAF13"   "TAF1C"
[134] "TAF6"    "TAF9"    "TARBP2"  "TK2"     "TMED2"   "TP53"    "TSG101"
[141] "TYMS"    "UMPS"    "UPF3B"   "USP11"   "VPS28"   "VPS37B"  "VPS37D"
[148] "XPC"     "ZNF707"  "ZWINT"

$HALLMARK_E2F_TARGETS
  [1] "AK2"      "ANP32E"   "ASF1A"    "ASF1B"    "ATAD2"    "AURKA"
  [7] "AURKB"    "BARD1"    "BIRC5"    "BRCA1"    "BRCA2"    "BRMS1L"
 [13] "BUB1B"    "CBX5"     "CCNB2"    "CCNE1"    "CCP110"   "CDC20"
 [19] "CDC25A"   "CDC25B"   "CDCA3"    "CDCA8"    "CDK1"     "CDK4"
 [25] "CDKN1A"   "CDKN1B"   "CDKN2A"   "CDKN2C"   "CDKN3"    "CENPE"
 [31] "CENPM"    "CHEK1"    "CHEK2"    "CIT"      "CKS1B"    "CKS2"
 [37] "CNOT9"    "CSE1L"    "CTCF"     "CTPS1"    "DCK"      "DCLRE1B"
 [43] "DCTPP1"   "DDX39A"   "DEK"      "DEPDC1"   "DIAPH3"   "DLGAP5"
 [49] "DNMT1"    "DONSON"   "DSCC1"    "DUT"      "E2F8"     "EED"
 [55] "EIF2S1"   "ESPL1"    "EXOSC8"   "EZH2"     "GINS1"    "GINS3"
 [61] "GINS4"    "GSPT1"    "H2AX"     "H2AZ1"    "HELLS"    "HMGA1"
 [67] "HMGB2"    "HMGB3"    "HMMR"     "HNRNPD"   "HUS1"     "ILF3"
 [73] "ING3"     "IPO7"     "JPT1"     "KIF18B"   "KIF22"    "KIF2C"

In [8]:
for (term in names(gset)){
    
pb <- AddModuleScore(
  pb, 
  features = gset[term], 
  name = term, 
  assay = "RNA"
) 
    
}

Warning message:
“The following features are not present in the object: ADIPOQ, CIDEA, FABP4, MTARC2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: AARS1, CARTPT, CCL11, CCL13, DARS1, IL9, MBL2, RARS1, WARS1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: AZGP1, H1-0, KLK3, KRT19, TARP, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: COL3A1, LUM, POSTN, SERPINA5, STC1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: ACTC1, CDH11, CDSN, CLDN18, CLDN8, CX3CL1, DMP1, DSC3, FLNC, KRT31, NHERF4, NRAP, PALS1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CX3CL1, PCSK9, SLC22A12, SLC2A4, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: BGN, DCN, GPX1, H1-0, IFNB1, LUM, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: ABCG4, AGXT, HAO1, HSD3B1, NR1H4, RXRG, SERPINA6, TTR, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: GPX8, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: APOC3, C8A, C8B, F13B, FGA, FGG, HMGCS2, HRG, KLK8, MBL2, MMP10, MMP3, MMP7, MMP8, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: MMP12, MMP13, MMP8, PCSK9, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: POLR1H, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: H2AX, H2AZ1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: BGN, CDH11, COL3A1, CXCL12, DCN, DKK1, FOXC2, LUM, MATN3, MMP3, MXRA5, POSTN, RGS4, SFRP1, SNAI2, WNT5A, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CCN5, CXCL12, CYP26B1, EEIG1, KRT13, KRT15, KRT19, NHERF1, NPY1R, PDLIM3, SLC7A2, SOX3, STC2, TFAP2C, TFF1, TFF3, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: ASCL1, CCN5, CXCL12, CYP26B1, EEIG1, GAL, GFUS, GJB3, HMGCS2, KLK11, KRT13, KRT19, NHERF1, NPY1R, PCP4, PDLIM3, SERPINA3, SERPINA5, SOX3, TFAP2C, TFF1, TFF3, TH, TRIM29, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: ADH1C, ADH7, CIDEA, CYP4A11, CYP4A22, FABP1, FABP2, H2AZ1, HAO2, HMGCS2, MIX23, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: H2AX, H2AZ1, H2AZ2, H2BC12, PTTG3P, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: DCN, GFUS, LHX9, RARS1, SOX9, STC1, STC2, TFF3, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CNTFR, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CROCCP2, H1-0, H4C3, HBBP1, MARCHF2, MARCHF8, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: BGN, BRS3, CCN5, CHST3, DCN, IGFBP1, LALBA, PCK1, PKP1, STC1, STC2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: HYCC2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CNTFR, PLA2G2A, REG1A, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: BDKRB1, CX3CL1, HAS2, NDP, SLC7A2, VIP, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: WARS1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: MARCHF1, RIGI, TMT1B, WARS1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: ABCG4, ACTC1, ADRA2C, AKR1B10, ARHGDIG, ATP4A, ATP6V1B1, CALML5, CLDN8, CLPS, CNTFR, CPA2, CYP11B2, FGF16, FSHB, GDNF, GP2, HTR1B, HTR1D, INSL5, IRS4, KLK7, KLK8, KRT13, KRT15, KRT4, LGALS7, MACROH2A2, MYH7, NGB, NPY4R, NTF3, PAX3, PAX4, PCDHB1, PKP1, SCN10A, SLC6A14, SMPX, SPRR3, SSTR4, TFAP2B, TFF2, TLX1, TSHB, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CFHR2, CIDEA, H2BC3, HOXD11, IGF2, IL33, MMP10, NGF, NR1H4, PCP4, SERPINA3, SOX9, TMEM100, TNNT2, USH1C, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: EPRS1, NHERF1, STC1, WARS1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: EPRS1, H2AZ1, IARS1, KARS1, PHB1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: PHB1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: ACTC1, COL3A1, DENND2B, EFS, GJA5, HSPB2, MYH1, MYH2, MYH4, MYH7, MYL1, MYL11, MYL7, MYOG, SLN, SOD3, STC2, TNNI1, TNNT2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: WNT2, WNT5A, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: CLCA2, H1-2, H2AC25, H2AJ, IRAG2, KLK8, NHLH2, TNNI1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: DCX, FOXA2, G6PC2, GCG, IAPP, INS, ISL1, NEUROD1, NKX2-2, PAX4, PDX1, SCGN, SST, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: HAO2, RXRG, SERPINA6, TTR, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: NGF, PITX2, PRKAA2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: ATP6V1B1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: ADCYAP1, AKAP4, CRISP2, CST8, GPR182, H1-6, HOXB1, HTR5A, MTNR1A, NPY5R, PAPOLB, PDHA2, PGK2, PRM2, SPMAP2, TNP1, TNP2, TSSK2, ZNRF4, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: RIGI, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: H2AX, IARS1, IGFBP1, SKIC3, STC2, TARS1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: COL3A1, EFEMP1, HAS2, RGS4, SNAI2, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: GAL, H2AX, LHX2, NKX2-5, PDLIM3, TARS1, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: DKK1, DKK4, not searching for symbol synonyms”
Warning message:
“The following features are not present in the object: ADH1C, ADH7, CRP, CYP1A2, CYP26A1, CYP4F2, FABP1, FETUB, G6PC1, GSTA3, GSTT2, HRG, IGFBP1, KARS1, MARCHF6, MBL2, REG1A, SERPINA6, TTPA, not searching for symbol synonyms”

In [9]:
meta = read.csv('data/01_meta/meta_pt.csv',row.names=1)
meta

       dataset_name batch viability_pct group race age  diabetes obesity
9-D    Pool137_7    1     95            DCIS  NHW  37.0 N        N
30-D   Pool137_12   1     92            DCIS  NHW  78.0 N        N
36-D   Pool137_18   1     93            DCIS  NHB  39.0 N        N
119-D  Pool137_20   1     95            DCIS  NHB  80.0 N        N
28-D   Pool137_24   1     94            DCIS  NHW  53.0 N        N
53-D   Pool137_27   1     96            DCIS  NHB  45.0 N        N
77-D   Pool137_30   1     90            DCIS  NHW  45.0 N        N
31-D   Pool138_6    2     93            DCIS  NHW  44.0 N        N
6-H    Pool137_6    1     94            HRL   NHW  71.1 N        Y
1-H    Pool137_10   1     88            HRL   NHW  62.3 N        N
43-H   Pool137_14   1     91            HRL   NHW  42.5 N        Y
336-H  Pool137_21   1     91            HRL   NHB  43.8 N        Y
1160-H Pool137_22   1     92            HRL   NHB  69.3 N        N
36-H   Pool137_25   1     90            HRL   NHW  59.6 N        N
42-H   Pool137_26   1     91            HRL   NHW  53.1 N        N
61-H   Pool137_29   1     90            HRL   NHW  59.6 N        N
133-H  Pool137_33   1     87            HRL   NHB  44.5 N        Y
1269-H Pool137_34   1     92            HRL   NHB  62.7 N        N
2207-H Pool137_35   1     94            HRL   NHB  48.2 N        N
24-H   Pool138_4    2     94            HRL   NHW  60.5 N        Y
63-H   Pool138_9    2     98            HRL   NHW  57.7 N        Y
102-H  Pool138_10   2     91            HRL   NHB  63.9 N        Y
568-H  Pool138_14   2     93            HRL   NHW  43.7 N        N
956-H  Pool138_15   2     89            HRL   NHW  42.8 N        N
19-I   Pool137_11   1     92            BC    NHW  48.0 N        N
45-I   Pool137_15   1     91            BC    NHW  67.0 N        N
56-I   Pool137_16   1     92            BC    NHB  60.0 N        Y
64-I   Pool137_17   1     90            BC    NHB  54.0 N        Y
37-I   Pool137_19   1     93            BC    NHW  79.0 N        N
27-I   Pool137_23   1     92            BC    NHW  66.0 N        N
58-I   Pool137_28   1     95            BC    NHW  63.0 N        N
4-I    Pool137_31   1     91            BC    NHB  47.0 N        Y
23-I   Pool138_3    2     96            BC    NHW  46.0 N        Y
26-I   Pool138_5    2     95            BC    NHW  67.0 N        N
36-I   Pool138_7    2     93            BC    NHW  67.0 N        Y
50-I   Pool138_8    2     95            BC    NHW  44.0 N        Y
38-I   Pool138_12   2     93            BC    NHW  69.0 N        N
77-I   Pool138_18   2     84            BC    NHB  60.0 N        N
76-I   Pool138_19   2     93            BC    NHB  45.0 N        Y
66-I   Pool138_21   2     92            BC    NHW  41.0 N        N
71-I   Pool138_22   2     88            BC    NHB  36.0 N        N
57-I   Pool138_23   2     91            BC    NHB  34.0 N        Y
55-I   Pool138_24   2     94            BC    NHW  33.0 N        N
31-I   Pool138_25   2     95            BC    NHB  31.0 N        N
11-I   Pool138_27   2     93            BC    NHB  45.0 N        Y
99-I   Pool138_29   2     80            BC    NHB  69.0 N        N
54-D   Pool137_8    1     87            DCIS  NHB  53.0 Y        N
79-D   Pool137_36   1     90            DCIS  NHW  62.0 Y        N
3145-H Pool137_9    1     84            HRL   NHB  58.9 Y        N
466-H  Pool138_11   2     92            HRL   NHB  63.0 Y        N
170-H  Pool138_13   2     84            HRL   NHB  60.9 Y        N
2176-H Pool138_16   2     94            HRL   NHB  54.7 Y        Y
101-I  Pool138_17   2     84            BC    NHB  74.0 Y        N
73-I   Pool138_20   2     95            BC    NHB  82.0 Y        Y
28-I   Pool138_26   2     94            BC    NHB  86.0 Y        Y
       race.stage
9-D    NHW-DCIS
30-D   NHW-DCIS
36-D   NHB-DCIS
119-D  NHB-DCIS
28-D   NHW-DCIS
53-D   NHB-DCIS
77-D   NHW-DCIS
31-D   NHW-DCIS
6-H    NHW-HRL
1-H    NHW-HRL
43-H   NHW-HRL
336-H  NHB-HRL
1160-H NHB-HRL
36-H   NHW-HRL
42-H   NHW-HRL
61-H   NHW-HRL
133-H  NHB-HRL
1269-H NHB-HRL
2207-H NHB-HRL
24-H   NHW-HRL
63-H   NHW-HRL
102-H  NHB-HRL
568-H  NHW-HRL
956-H  NHW-HRL
19-I   NHW-BC
45-I   NHW-BC
56-I   NHB-BC
64-I   NHB-BC
37-I   NHW-BC
27-I   NHW-BC
58-I   NHW-BC
4-I    NHB-BC
23-I   NHW-BC
26-I   NHW-BC
36-I   NHW-BC
50-I   NHW-BC
38-I   NHW-BC
77-I   NHB-BC
76-I   NHB-BC
66-I   NHW-BC
71-I   NHB-BC
57-I   NHB-BC
55-I   NHW-BC
31-I   NHB-BC
11-I   NHB-BC
99-I   NHB-BC
54-D   NHB-DCIS
79-D   NHW-DCIS
3145-H NHB-HRL
466-H  NHB-HRL
170-H  NHB-HRL
2176-H NHB-HRL
101-I  NHB-BC
73-I   NHB-BC
28-I   NHB-BC

In [10]:
pb@meta.data

                                 orig.ident                       dataset_name
Pool137-10_Naive B               Pool137-10_Naive B               Pool137-10
Pool137-10_Mature B              Pool137-10_Mature B              Pool137-10
Pool137-10_Memory B              Pool137-10_Memory B              Pool137-10
Pool137-10_Plasmablast           Pool137-10_Plasmablast           Pool137-10
Pool137-10_Naive CD4T            Pool137-10_Naive CD4T            Pool137-10
Pool137-10_Central Memory CD4T   Pool137-10_Central Memory CD4T   Pool137-10
Pool137-10_Cytotoxic CD4T        Pool137-10_Cytotoxic CD4T        Pool137-10
Pool137-10_Effector Memory CD4T  Pool137-10_Effector Memory CD4T  Pool137-10
Pool137-10_Treg                  Pool137-10_Treg                  Pool137-10
Pool137-10_Naive CD8T            Pool137-10_Naive CD8T            Pool137-10
Pool137-10_Central Memory CD8T   Pool137-10_Central Memory CD8T   Pool137-10
Pool137-10_Effector Memory CD8T  Pool137-10_Effector Memory CD8T  Pool137-10
Pool137-10_Double Negative T     Pool137-10_Double Negative T     Pool137-10
Pool137-10_γδ T                  Pool137-10_γδ T                  Pool137-10
Pool137-10_MAIT                  Pool137-10_MAIT                  Pool137-10
Pool137-10_cDC1                  Pool137-10_cDC1                  Pool137-10
Pool137-10_cDC2                  Pool137-10_cDC2                  Pool137-10
Pool137-10_pDC                   Pool137-10_pDC                   Pool137-10
Pool137-10_Classical Monocyte    Pool137-10_Classical Monocyte    Pool137-10
Pool137-10_Intermediate Monocyte Pool137-10_Intermediate Monocyte Pool137-10
Pool137-10_Nonclassical Monocyte Pool137-10_Nonclassical Monocyte Pool137-10
Pool137-10_Cytotoxic Monocyte    Pool137-10_Cytotoxic Monocyte    Pool137-10
Pool137-10_CD56-dim NK           Pool137-10_CD56-dim NK           Pool137-10
Pool137-10_CD56-bright NK        Pool137-10_CD56-bright NK        Pool137-10
Pool137-10_Proliferating NK      Pool137-10_Proliferating NK      Pool137-10
Pool137-11_Naive B               Pool137-11_Naive B               Pool137-11
Pool137-11_Mature B              Pool137-11_Mature B              Pool137-11
Pool137-11_Memory B              Pool137-11_Memory B              Pool137-11
Pool137-11_Plasmablast           Pool137-11_Plasmablast           Pool137-11
Pool137-11_Naive CD4T            Pool137-11_Naive CD4T            Pool137-11
⋮                                ⋮                                ⋮
Pool138-8_pDC                    Pool138-8_pDC                    Pool138-8
Pool138-8_Classical Monocyte     Pool138-8_Classical Monocyte     Pool138-8
Pool138-8_Intermediate Monocyte  Pool138-8_Intermediate Monocyte  Pool138-8
Pool138-8_Nonclassical Monocyte  Pool138-8_Nonclassical Monocyte  Pool138-8
Pool138-8_Cytotoxic Monocyte     Pool138-8_Cytotoxic Monocyte     Pool138-8
Pool138-8_CD56-dim NK            Pool138-8_CD56-dim NK            Pool138-8
Pool138-8_CD56-bright NK         Pool138-8_CD56-bright NK         Pool138-8
Pool138-8_Proliferating NK       Pool138-8_Proliferating NK       Pool138-8
Pool138-9_Naive B                Pool138-9_Naive B                Pool138-9
Pool138-9_Mature B               Pool138-9_Mature B               Pool138-9
Pool138-9_Memory B               Pool138-9_Memory B               Pool138-9
Pool138-9_Plasmablast            Pool138-9_Plasmablast            Pool138-9
Pool138-9_Naive CD4T             Pool138-9_Naive CD4T             Pool138-9
Pool138-9_Central Memory CD4T    Pool138-9_Central Memory CD4T    Pool138-9
Pool138-9_Cytotoxic CD4T         Pool138-9_Cytotoxic CD4T         Pool138-9
Pool138-9_Effector Memory CD4T   Pool138-9_Effector Memory CD4T   Pool138-9
Pool138-9_Treg                   Pool138-9_Treg                   Pool138-9
Pool138-9_Naive CD8T             Pool138-9_Naive CD8T             Pool138-9
Pool138-9_Central Memory CD8T    Pool138-9_Central Memory CD8T    Pool138-9
Pool138-9_Effector Memory CD8T   Pool138-9_Effector Memory CD8T   Pool138-9
Pool138-9_cDC1                   Pool138-9_cDC1                   Pool138-9
Pool138-9_cDC2                   Pool138-9_cDC2                   Pool138-9
Pool138-9_pDC                    Pool138-9_pDC                    Pool138-9
Pool138-9_Classical Monocyte     Pool138-9_Classical Monocyte     Pool138-9
Pool138-9_Intermediate Monocyte  Pool138-9_Intermediate Monocyte  Pool138-9
Pool138-9_Nonclassical Monocyte  Pool138-9_Nonclassical Monocyte  Pool138-9
Pool138-9_Cytotoxic Monocyte     Pool138-9_Cytotoxic Monocyte     Pool138-9
Pool138-9_CD56-dim NK            Pool138-9_CD56-dim NK            Pool138-9
Pool138-9_CD56-bright NK         Pool138-9_CD56-bright NK         Pool138-9
Pool138-9_Proliferating NK       Pool138-9_Proliferating NK       Pool138-9
                                 celltype_level3
Pool137-10_Naive B               Naive B
Pool137-10_Mature B              Mature B
Pool137-10_Memory B              Memory B
Pool137-10_Plasmablast           Plasmablast
Pool137-10_Naive CD4T            Naive CD4T
Pool137-10_Central Memory CD4T   Central Memory CD4T
Pool137-10_Cytotoxic CD4T        Cytotoxic CD4T
Pool137-10_Effector Memory CD4T  Effector Memory CD4T
Pool137-10_Treg                  Treg
Pool137-10_Naive CD8T            Naive CD8T
Pool137-10_Central Memory CD8T   Central Memory CD8T
Pool137-10_Effector Memory CD8T  Effector Memory CD8T
Pool137-10_Double Negative T     Double Negative T
Pool137-10_γδ T                  γδ T
Pool137-10_MAIT                  MAIT
Pool137-10_cDC1                  cDC1
Pool137-10_cDC2                  cDC2
Pool137-10_pDC                   pDC
Pool137-10_Classical Monocyte    Classical Monocyte
Pool137-10_Intermediate Monocyte Intermediate Monocyte
Pool137-10_Nonclassical Monocyte Nonclassical Monocyte
Pool137-10_Cytotoxic Monocyte    Cytotoxic Monocyte
Pool137-10_CD56-dim NK           CD56-dim NK
Pool137-10_CD56-bright NK        CD56-bright NK
Pool137-10_Proliferating NK      Proliferating NK
Pool137-11_Naive B               Naive B
Pool137-11_Mature B              Mature B
Pool137-11_Memory B              Memory B
Pool137-11_Plasmablast           Plasmablast
Pool137-11_Naive CD4T            Naive CD4T
⋮                                ⋮
Pool138-8_pDC                    pDC
Pool138-8_Classical Monocyte     Classical Monocyte
Pool138-8_Intermediate Monocyte  Intermediate Monocyte
Pool138-8_Nonclassical Monocyte  Nonclassical Monocyte
Pool138-8_Cytotoxic Monocyte     Cytotoxic Monocyte
Pool138-8_CD56-dim NK            CD56-dim NK
Pool138-8_CD56-bright NK         CD56-bright NK
Pool138-8_Proliferating NK       Proliferating NK
Pool138-9_Naive B                Naive B
Pool138-9_Mature B               Mature B
Pool138-9_Memory B               Memory B
Pool138-9_Plasmablast            Plasmablast
Pool138-9_Naive CD4T             Naive CD4T
Pool138-9_Central Memory CD4T    Central Memory CD4T
Pool138-9_Cytotoxic CD4T         Cytotoxic CD4T
Pool138-9_Effector Memory CD4T   Effector Memory CD4T
Pool138-9_Treg                   Treg
Pool138-9_Naive CD8T             Naive CD8T
Pool138-9_Central Memory CD8T    Central Memory CD8T
Pool138-9_Effector Memory CD8T   Effector Memory CD8T
Pool138-9_cDC1                   cDC1
Pool138-9_cDC2                   cDC2
Pool138-9_pDC                    pDC
Pool138-9_Classical Monocyte     Classical Monocyte
Pool138-9_Intermediate Monocyte  Intermediate Monocyte
Pool138-9_Nonclassical Monocyte  Nonclassical Monocyte
Pool138-9_Cytotoxic Monocyte     Cytotoxic Monocyte
Pool138-9_CD56-dim NK            CD56-dim NK
Pool138-9_CD56-bright NK         CD56-bright NK
Pool138-9_Proliferating NK       Proliferating NK
                                 Activation of innate immune response1
Pool137-10_Naive B               -1.075838e-02
Pool137-10_Mature B              -5.263694e-03
Pool137-10_Memory B              -5.761555e-03
Pool137-10_Plasmablast           -2.260759e-02
Pool137-10_Naive CD4T            -5.052081e-02
Pool137-10_Central Memory CD4T   -4.291899e-02
Pool137-10_Cytotoxic CD4T        -2.633451e-02
Pool137-10_Effector Memory CD4T  -3.675915e-02
Pool137-10_Treg                  -2.517539e-02
Pool137-10_Naive CD8T            -4.890968e-02
Pool137-10_Central Memory CD8T   -1.430164e-02
Pool137-10_Effector Memory CD8T   5.696538e-03
Pool137-10_Double Negative T     -1.970935e-02
Pool137-10_γδ T                   5.514838e-03
Pool137-10_MAIT                  -9.838327e-03
Pool137-10_cDC1                   2.303263e-02
Pool137-10_cDC2                   9.470049e-02
Pool137-10_pDC                    4.038537e-02
Pool137-10_Classical Monocyte     1.905647e-01
Pool137-10_Intermediate Monocyte  1.789626e-01
Pool137-10_Nonclassical Monocyte  1.775705e-01
Pool137-10_Cytotoxic Monocyte     1.311154e-01
Pool137-10_CD56-dim NK            4.112860e-02
Pool137-10_CD56-bright NK         7.479228e-02
Pool137-10_Proliferating NK       5.369164e-03
Pool137-11_Naive B               -2.890859e-05
Pool137-11_Mature B               1.544453e-02
Pool137-11_Memory B               5.612964e-05
Pool137-11_Plasmablast           -2.957439e-02
Pool137-11_Naive CD4T            -4.582471e-02
⋮                                ⋮
Pool138-8_pDC                     0.0339963012
Pool138-8_Classical Monocyte      0.1700515788
Pool138-8_Intermediate Monocyte   0.1678754391
Pool138-8_Nonclassical Monocyte   0.1727007895
Pool138-8_Cytotoxic Monocyte      0.1330921061
Pool138-8_CD56-dim NK             0.0287765032
Pool138-8_CD56-bright NK          0.0080216660
Pool138-8_Proliferating NK        0.0168365803
Pool138-9_Naive B                -0.0001641091
Pool138-9_Mature B                0.0174397384
Pool138-9_Memory B               -0.0005134971
Pool138-9_Plasmablast            -0.0283449349
Pool138-9_Naive CD4T             -0.0467272782
Pool138-9_Central Memory CD4T    -0.0354191677
Pool138-9_Cytotoxic CD4T         -0.0074473115
Pool138-9_Effector Memory CD4T   -0.0236712525
Pool138-9_Treg                   -0.0258388868
Pool138-9_Naive CD8T             -0.0407098849
Pool138-9_Central Memory CD8T    -0.0274935487
Pool138-9_Effector Memory CD8T   -0.0084217076
Pool138-9_cDC1                    0.0366674296
Pool138-9_cDC2                    0.1096316546
Pool138-9_pDC                     0.0454745692
Pool138-9_Classical Monocyte      0.1847697443
Pool138-9_Intermediate Monocyte   0.1867154840
Pool138-9_Nonclassical Monocyte   0.1846711005
Pool138-9_Cytotoxic Monocyte      0.1295559445
Pool138-9_CD56-dim NK             0.0390894412
Pool138-9_CD56-bright NK          0.0670935424
Pool138-9_Proliferating NK        0.0068682118
                                 Adaptive immune memory response1
Pool137-10_Naive B               -0.07685294
Pool137-10_Mature B               0.30343819
Pool137-10_Memory B               0.31473665
Pool137-10_Plasmablast            0.38229631
Pool137-10_Naive CD4T             0.24907229
Pool137-10_Central Memory CD4T    0.20207335
Pool137-10_Cytotoxic CD4T         0.19819686
Pool137-10_Effector Memory CD4T   0.22884993
Pool137-10_Treg                   0.47351288
Pool137-10_Naive CD8T             0.30212873
Pool137-10_Central Memory CD8T    0.22441618
Pool137-10_Effector Memory CD8T   0.14543259
Pool137-10_Double Negative T      0.91221043
Pool137-10_γδ T                  -0.18174403
Pool137-10_MAIT                   0.19203453
Pool137-10_cDC1                  -0.20794470
Pool137-10_cDC2                  -0.21347013
Pool137-10_pDC                   -0.28054034
Pool137-10_Classical Monocyte    -0.27431573
Pool137-10_Intermediate Monocyte -0.25709462
Pool137-10_Nonclassical Monocyte -0.27519953
Pool137-10_Cytotoxic Monocyte    -0.14365940
Pool137-10_CD56-dim NK           -0.25471272
Pool137-10_CD56-bright NK        -0.07698998
Pool137-10_Proliferating NK      -0.21607045
Pool137-11_Naive B               -0.02206285
Pool137-11_Mature B               0.30972992
Pool137-11_Memory B               0.32012465
Pool137-11_Plasmablast            0.43290256
Pool137-11_Naive CD4T             0.28327814
⋮                                ⋮
Pool138-8_pDC                    -0.16361362
Pool138-8_Classical Monocyte     -0.25369555
Pool138-8_Intermediate Monocyte  -0.23109811
Pool138-8_Nonclassical Monocyte  -0.24875719
Pool138-8_Cytotoxic Monocyte     -0.13665025
Pool138-8_CD56-dim NK            -0.25783434
Pool138-8_CD56-bright NK         -0.08494354
Pool138-8_Proliferating NK       -0.17972902
Pool138-9_Naive B                -0.04389490
Pool138-9_Mature B                0.30393079
Pool138-9_Memory B                0.32062502
Pool138-9_Plasmablast             0.51897470
Pool138-9_Naive CD4T              0.29620615
Pool138-9_Central Memory CD4T     0.24397149
Pool138-9_Cytotoxic CD4T          0.30423727
Pool138-9_Effector Memory CD4T    0.28677540
Pool138-9_Treg                    0.44690251
Pool138-9_Naive CD8T              0.37622885
Pool138-9_Central Memory CD8T     0.29012756
Pool138-9_Effector Memory CD8T    0.02395579
Pool138-9_cDC1                   -0.19666484
Pool138-9_cDC2                   -0.18884715
Pool138-9_pDC                    -0.20499479
Pool138-9_Classical Monocyte     -0.26073477
Pool138-9_Intermediate Monocyte  -0.22484152
Pool138-9_Nonclassical Monocyte  -0.23916946
Pool138-9_Cytotoxic Monocyte     -0.07940768
Pool138-9_CD56-dim NK            -0.23548155
Pool138-9_CD56-bright NK         -0.12406812
Pool138-9_Proliferating NK       -0.34556227
                                 Adaptive immune memory response involving T cells and B cells1
Pool137-10_Naive B               -0.07685294
Pool137-10_Mature B               0.30343819
Pool137-10_Memory B               0.31473665
Pool137-10_Plasmablast            0.38229631
Pool137-10_Naive CD4T             0.24907229
Pool137-10_Central Memory CD4T    0.20207335
Pool137-10_Cytotoxic CD4T         0.19819686
Pool137-10_Effector Memory CD4T   0.22884993
Pool137-10_Treg                   0.47351288
Pool137-10_Naive CD8T             0.30212873
Pool137-10_Central Memory CD8T    0.22441618
Pool137-10_Effector Memory CD8T   0.14543259
Pool137-10_Double Negative T      0.91221043
Pool137-10_γδ T                  -0.18174403
Pool137-10_MAIT                   0.19203453
Pool137-10_cDC1                  -0.20794470
Pool137-10_cDC2                  -0.21347013
Pool137-10_pDC                   -0.28054034
Pool137-10_Classical Monocyte    -0.27431573
Pool137-10_Intermediate Monocyte -0.25709462
Pool137-10_Nonclassical Monocyte -0.27519953
Pool137-10_Cytotoxic Monocyte    -0.14365940
Pool137-10_CD56-dim NK           -0.25471272
Pool137-10_CD56-bright NK        -0.07698998
Pool137-10_Proliferating NK      -0.21607045
Pool137-11_Naive B               -0.02206285
Pool137-11_Mature B               0.30972992
Pool137-11_Memory B               0.32012465
Pool137-11_Plasmablast            0.43290256
Pool137-11_Naive CD4T             0.28327814
⋮                                ⋮
Pool138-8_pDC                    -0.16361362
Pool138-8_Classical Monocyte     -0.25369555
Pool138-8_Intermediate Monocyte  -0.23109811
Pool138-8_Nonclassical Monocyte  -0.24875719
Pool138-8_Cytotoxic Monocyte     -0.13665025
Pool138-8_CD56-dim NK            -0.25783434
Pool138-8_CD56-bright NK         -0.08494354
Pool138-8_Proliferating NK       -0.17972902
Pool138-9_Naive B                -0.04389490
Pool138-9_Mature B                0.30393079
Pool138-9_Memory B                0.32062502
Pool138-9_Plasmablast             0.51897470
Pool138-9_Naive CD4T              0.29620615
Pool138-9_Central Memory CD4T     0.24397149
Pool138-9_Cytotoxic CD4T          0.30423727
Pool138-9_Effector Memory CD4T    0.28677540
Pool138-9_Treg                    0.44690251
Pool138-9_Naive CD8T              0.37622885
Pool138-9_Central Memory CD8T     0.29012756
Pool138-9_Effector Memory CD8T    0.02395579
Pool138-9_cDC1                   -0.19666484
Pool138-9_cDC2                   -0.18884715
Pool138-9_pDC                    -0.20499479
Pool138-9_Classical Monocyte     -0.26073477
Pool138-9_Intermediate Monocyte  -0.22484152
Pool138-9_Nonclassical Monocyte  -0.23916946
Pool138-9_Cytotoxic Monocyte     -0.07940768
Pool138-9_CD56-dim NK            -0.23548155
Pool138-9_CD56-bright NK         -0.12406812
Pool138-9_Proliferating NK       -0.34556227
                                 Adaptive immune response based on somatic recombination of immune receptors built from immunoglobulin superfamily domains1
Pool137-10_Naive B                0.245886730
Pool137-10_Mature B               0.195215674
Pool137-10_Memory B               0.167285925
Pool137-10_Plasmablast            0.276752302
Pool137-10_Naive CD4T            -0.033643205
Pool137-10_Central Memory CD4T   -0.028638315
Pool137-10_Cytotoxic CD4T        -0.010847773
Pool137-10_Effector Memory CD4T  -0.017209254
Pool137-10_Treg                  -0.001009156
Pool137-10_Naive CD8T            -0.017625524
Pool137-10_Central Memory CD8T   -0.005471622
Pool137-10_Effector Memory CD8T   0.023434525
Pool137-10_Double Negative T      0.022420350
Pool137-10_γδ T                   0.027744428
Pool137-10_MAIT                   0.023827189
Pool137-10_cDC1                   0.004659307
Pool137-10_cDC2                   0.038854109
Pool137-10_pDC                    0.022242426
Pool137-10_Classical Monocyte     0.013563582
Pool137-10_Intermediate Monocyte  0.036484900
Pool137-10_Nonclassical Monocyte  0.054133272
Pool137-10_Cytotoxic Monocyte     0.018787762
Pool137-10_CD56-dim NK            0.034206421
Pool137-10_CD56-bright NK         0.039808388
Pool137-10_Proliferating NK       0.005177491
Pool137-11_Naive B                0.250791949
Pool137-11_Mature B               0.196645782
Pool137-11_Memory B               0.147011671
Pool137-11_Plasmablast            0.478049467
Pool137-11_Naive CD4T            -0.023951743
⋮                                ⋮
Pool138-8_pDC                     0.035254799
Pool138-8_Classical Monocyte      0.014951326
Pool138-8_Intermediate Monocyte   0.044519450
Pool138-8_Nonclassical Monocyte   0.060638445
Pool138-8_Cytotoxic Monocyte      0.018831649
Pool138-8_CD56-dim NK             0.036494686
Pool138-8_CD56-bright NK          0.049331636
Pool138-8_Proliferating NK        0.053081623
Pool138-9_Naive B                 0.263463216
Pool138-9_Mature B                0.204810006
Pool138-9_Memory B                0.193098267
Pool138-9_Plasmablast             0.294801940
Pool138-9_Naive CD4T             -0.022492302
Pool138-9_Central Memory CD4T    -0.014219797
Pool138-9_Cytotoxic CD4T          0.006705182
Pool138-9_Effector Memory CD4T   -0.009187156
Pool138-9_Treg                    0.012161608
Pool138-9_Naive CD8T             -0.005254020
Pool138-9_Central Memory CD8T     0.001892938
Pool138-9_Effector Memory CD8T    0.038348753
Pool138-9_cDC1                    0.026994256
Pool138-9_cDC2                    0.053429162
Pool138-9_pDC                     0.039884919
Pool138-9_Classical Monocyte      0.025518637
Pool138-9_Intermediate Monocyte   0.056179431
Pool138-9_Nonclassical Monocyte   0.073736506
Pool138-9_Cytotoxic Monocyte      0.027200359
Pool138-9_CD56-dim NK             0.054539956
Pool138-9_CD56-bright NK          0.060526328
Pool138-9_Proliferating NK        0.029218143
                                 Advanced glycosylation endproduct receptor signaling1
Pool137-10_Naive B               -0.077992110
Pool137-10_Mature B              -0.163826029
Pool137-10_Memory B              -0.132062555
Pool137-10_Plasmablast            0.038582523
Pool137-10_Naive CD4T            -0.135398048
Pool137-10_Central Memory CD4T   -0.118342034
Pool137-10_Cytotoxic CD4T        -0.103322596
Pool137-10_Effector Memory CD4T  -0.130602287
Pool137-10_Treg                  -0.115384467
Pool137-10_Naive CD8T            -0.069937353
Pool137-10_Central Memory CD8T    0.001342995
Pool137-10_Effector Memory CD8T  -0.119232981
Pool137-10_Double Negative T     -0.086068498
Pool137-10_γδ T                  -0.171461430
Pool137-10_MAIT                  -0.078367843
Pool137-10_cDC1                   0.047329063
Pool137-10_cDC2                   0.055628062

In [11]:
library(dplyr)

dfp = pb@meta.data

# 1. Fix dataset_name: replace "-" with "_"
dfp <- dfp %>%
  mutate(dataset_name = gsub("-", "_", dataset_name))

# 2. Left join with meta by dataset_name
dfp <- dfp %>%
  left_join(meta, by = "dataset_name")

In [12]:
dfp

     orig.ident                       dataset_name celltype_level3
1    Pool137-10_Naive B               Pool137_10   Naive B
2    Pool137-10_Mature B              Pool137_10   Mature B
3    Pool137-10_Memory B              Pool137_10   Memory B
4    Pool137-10_Plasmablast           Pool137_10   Plasmablast
5    Pool137-10_Naive CD4T            Pool137_10   Naive CD4T
6    Pool137-10_Central Memory CD4T   Pool137_10   Central Memory CD4T
7    Pool137-10_Cytotoxic CD4T        Pool137_10   Cytotoxic CD4T
8    Pool137-10_Effector Memory CD4T  Pool137_10   Effector Memory CD4T
9    Pool137-10_Treg                  Pool137_10   Treg
10   Pool137-10_Naive CD8T            Pool137_10   Naive CD8T
11   Pool137-10_Central Memory CD8T   Pool137_10   Central Memory CD8T
12   Pool137-10_Effector Memory CD8T  Pool137_10   Effector Memory CD8T
13   Pool137-10_Double Negative T     Pool137_10   Double Negative T
14   Pool137-10_γδ T                  Pool137_10   γδ T
15   Pool137-10_MAIT                  Pool137_10   MAIT
16   Pool137-10_cDC1                  Pool137_10   cDC1
17   Pool137-10_cDC2                  Pool137_10   cDC2
18   Pool137-10_pDC                   Pool137_10   pDC
19   Pool137-10_Classical Monocyte    Pool137_10   Classical Monocyte
20   Pool137-10_Intermediate Monocyte Pool137_10   Intermediate Monocyte
21   Pool137-10_Nonclassical Monocyte Pool137_10   Nonclassical Monocyte
22   Pool137-10_Cytotoxic Monocyte    Pool137_10   Cytotoxic Monocyte
23   Pool137-10_CD56-dim NK           Pool137_10   CD56-dim NK
24   Pool137-10_CD56-bright NK        Pool137_10   CD56-bright NK
25   Pool137-10_Proliferating NK      Pool137_10   Proliferating NK
26   Pool137-11_Naive B               Pool137_11   Naive B
27   Pool137-11_Mature B              Pool137_11   Mature B
28   Pool137-11_Memory B              Pool137_11   Memory B
29   Pool137-11_Plasmablast           Pool137_11   Plasmablast
30   Pool137-11_Naive CD4T            Pool137_11   Naive CD4T
⋮    ⋮                                ⋮            ⋮
1312 Pool138-8_pDC                    Pool138_8    pDC
1313 Pool138-8_Classical Monocyte     Pool138_8    Classical Monocyte
1314 Pool138-8_Intermediate Monocyte  Pool138_8    Intermediate Monocyte
1315 Pool138-8_Nonclassical Monocyte  Pool138_8    Nonclassical Monocyte
1316 Pool138-8_Cytotoxic Monocyte     Pool138_8    Cytotoxic Monocyte
1317 Pool138-8_CD56-dim NK            Pool138_8    CD56-dim NK
1318 Pool138-8_CD56-bright NK         Pool138_8    CD56-bright NK
1319 Pool138-8_Proliferating NK       Pool138_8    Proliferating NK
1320 Pool138-9_Naive B                Pool138_9    Naive B
1321 Pool138-9_Mature B               Pool138_9    Mature B
1322 Pool138-9_Memory B               Pool138_9    Memory B
1323 Pool138-9_Plasmablast            Pool138_9    Plasmablast
1324 Pool138-9_Naive CD4T             Pool138_9    Naive CD4T
1325 Pool138-9_Central Memory CD4T    Pool138_9    Central Memory CD4T
1326 Pool138-9_Cytotoxic CD4T         Pool138_9    Cytotoxic CD4T
1327 Pool138-9_Effector Memory CD4T   Pool138_9    Effector Memory CD4T
1328 Pool138-9_Treg                   Pool138_9    Treg
1329 Pool138-9_Naive CD8T             Pool138_9    Naive CD8T
1330 Pool138-9_Central Memory CD8T    Pool138_9    Central Memory CD8T
1331 Pool138-9_Effector Memory CD8T   Pool138_9    Effector Memory CD8T
1332 Pool138-9_cDC1                   Pool138_9    cDC1
1333 Pool138-9_cDC2                   Pool138_9    cDC2
1334 Pool138-9_pDC                    Pool138_9    pDC
1335 Pool138-9_Classical Monocyte     Pool138_9    Classical Monocyte
1336 Pool138-9_Intermediate Monocyte  Pool138_9    Intermediate Monocyte
1337 Pool138-9_Nonclassical Monocyte  Pool138_9    Nonclassical Monocyte
1338 Pool138-9_Cytotoxic Monocyte     Pool138_9    Cytotoxic Monocyte
1339 Pool138-9_CD56-dim NK            Pool138_9    CD56-dim NK
1340 Pool138-9_CD56-bright NK         Pool138_9    CD56-bright NK
1341 Pool138-9_Proliferating NK       Pool138_9    Proliferating NK
     Activation of innate immune response1 Adaptive immune memory response1
1    -1.075838e-02                         -0.07685294
2    -5.263694e-03                          0.30343819
3    -5.761555e-03                          0.31473665
4    -2.260759e-02                          0.38229631
5    -5.052081e-02                          0.24907229
6    -4.291899e-02                          0.20207335
7    -2.633451e-02                          0.19819686
8    -3.675915e-02                          0.22884993
9    -2.517539e-02                          0.47351288
10   -4.890968e-02                          0.30212873
11   -1.430164e-02                          0.22441618
12    5.696538e-03                          0.14543259
13   -1.970935e-02                          0.91221043
14    5.514838e-03                         -0.18174403
15   -9.838327e-03                          0.19203453
16    2.303263e-02                         -0.20794470
17    9.470049e-02                         -0.21347013
18    4.038537e-02                         -0.28054034
19    1.905647e-01                         -0.27431573
20    1.789626e-01                         -0.25709462
21    1.775705e-01                         -0.27519953
22    1.311154e-01                         -0.14365940
23    4.112860e-02                         -0.25471272
24    7.479228e-02                         -0.07698998
25    5.369164e-03                         -0.21607045
26   -2.890859e-05                         -0.02206285
27    1.544453e-02                          0.30972992
28    5.612964e-05                          0.32012465
29   -2.957439e-02                          0.43290256
30   -4.582471e-02                          0.28327814
⋮    ⋮                                     ⋮
1312  0.0339963012                         -0.16361362
1313  0.1700515788                         -0.25369555
1314  0.1678754391                         -0.23109811
1315  0.1727007895                         -0.24875719
1316  0.1330921061                         -0.13665025
1317  0.0287765032                         -0.25783434
1318  0.0080216660                         -0.08494354
1319  0.0168365803                         -0.17972902
1320 -0.0001641091                         -0.04389490
1321  0.0174397384                          0.30393079
1322 -0.0005134971                          0.32062502
1323 -0.0283449349                          0.51897470
1324 -0.0467272782                          0.29620615
1325 -0.0354191677                          0.24397149
1326 -0.0074473115                          0.30423727
1327 -0.0236712525                          0.28677540
1328 -0.0258388868                          0.44690251
1329 -0.0407098849                          0.37622885
1330 -0.0274935487                          0.29012756
1331 -0.0084217076                          0.02395579
1332  0.0366674296                         -0.19666484
1333  0.1096316546                         -0.18884715
1334  0.0454745692                         -0.20499479
1335  0.1847697443                         -0.26073477
1336  0.1867154840                         -0.22484152
1337  0.1846711005                         -0.23916946
1338  0.1295559445                         -0.07940768
1339  0.0390894412                         -0.23548155
1340  0.0670935424                         -0.12406812
1341  0.0068682118                         -0.34556227
     Adaptive immune memory response involving T cells and B cells1
1    -0.07685294
2     0.30343819
3     0.31473665
4     0.38229631
5     0.24907229
6     0.20207335
7     0.19819686
8     0.22884993
9     0.47351288
10    0.30212873
11    0.22441618
12    0.14543259
13    0.91221043
14   -0.18174403
15    0.19203453
16   -0.20794470
17   -0.21347013
18   -0.28054034
19   -0.27431573
20   -0.25709462
21   -0.27519953
22   -0.14365940
23   -0.25471272
24   -0.07698998
25   -0.21607045
26   -0.02206285
27    0.30972992
28    0.32012465
29    0.43290256
30    0.28327814
⋮    ⋮
1312 -0.16361362
1313 -0.25369555
1314 -0.23109811
1315 -0.24875719
1316 -0.13665025
1317 -0.25783434
1318 -0.08494354
1319 -0.17972902
1320 -0.04389490
1321  0.30393079
1322  0.32062502
1323  0.51897470
1324  0.29620615
1325  0.24397149
1326  0.30423727
1327  0.28677540
1328  0.44690251
1329  0.37622885
1330  0.29012756
1331  0.02395579
1332 -0.19666484
1333 -0.18884715
1334 -0.20499479
1335 -0.26073477
1336 -0.22484152
1337 -0.23916946
1338 -0.07940768
1339 -0.23548155
1340 -0.12406812
1341 -0.34556227
     Adaptive immune response based on somatic recombination of immune receptors built from immunoglobulin superfamily domains1
1     0.245886730
2     0.195215674
3     0.167285925
4     0.276752302
5    -0.033643205
6    -0.028638315
7    -0.010847773
8    -0.017209254
9    -0.001009156
10   -0.017625524
11   -0.005471622
12    0.023434525
13    0.022420350
14    0.027744428
15    0.023827189
16    0.004659307
17    0.038854109
18    0.022242426
19    0.013563582
20    0.036484900
21    0.054133272
22    0.018787762
23    0.034206421
24    0.039808388
25    0.005177491
26    0.250791949
27    0.196645782
28    0.147011671
29    0.478049467
30   -0.023951743
⋮    ⋮
1312  0.035254799
1313  0.014951326
1314  0.044519450
1315  0.060638445
1316  0.018831649
1317  0.036494686
1318  0.049331636
1319  0.053081623
1320  0.263463216
1321  0.204810006
1322  0.193098267
1323  0.294801940
1324 -0.022492302
1325 -0.014219797
1326  0.006705182
1327 -0.009187156
1328  0.012161608
1329 -0.005254020
1330  0.001892938
1331  0.038348753
1332  0.026994256
1333  0.053429162
1334  0.039884919
1335  0.025518637
1336  0.056179431
1337  0.073736506
1338  0.027200359
1339  0.054539956
1340  0.060526328
1341  0.029218143
     Advanced glycosylation endproduct receptor signaling1
1    -0.077992110
2    -0.163826029
3    -0.132062555
4     0.038582523
5    -0.135398048
6    -0.118342034
7    -0.103322596
8    -0.130602287
9    -0.115384467
10   -0.069937353
11    0.001342995
12   -0.119232981
13   -0.086068498
14   -0.171461430
15   -0.078367843
16    0.047329063
17    0.055628062
18    0.089967848
19    0.224165770
20    0.096945425
21    0.036474506
22    0.148400517
23   -0.082670130
24   -0.048123070
25   -0.117081339
26   -0.102206464
27   -0.131857680
28   -0.118486710
29    0.027965257
30   -0.152486634
⋮    ⋮
1312  0.120819846
1313  0.234515297
1314  0.055925418
1315  0.050412896
1316  0.136154001
1317 -0.058876479
1318 -0.088463850
1319 -0.006693561
1320 -0.103498982
1321 -0.121204038
1322 -0.090420010
1323 -0.014231626
1324 -0.146018528
1325 -0.106065723
1326 -0.096387548
1327 -0.126990139
1328 -0.102809377
1329 -0.121223354
1330 -0.093310895
1331 -0.124271926
1332  0.180657873
1333  0.075231512
1334  0.077691081
1335  0.265061180
1336  0.080918156
1337  0.049423495
1338  0.084601783
1339 -0.081394919
1340 -0.101593233
1341 -0.008884448
     Alpha-beta T cell activation1 Alpha-protein kinase 1 signaling pathway1 ⋯
1     0.0374202655                 0.5904225                                 ⋯
2     0.0383314991                 0.5797567                                 ⋯
3    -0.0006637313                 0.5810649                                 ⋯
4    -0.0473857579                 0.3834268                                 ⋯
5     0.2007945395                 0.5848252                                 ⋯
6     0.2154237793                 0.5818601                                 ⋯
7     0.2307281391                 0.5504305                                 ⋯
8     0.2142745485                 0.5683757                                 ⋯
9     0.2368215158                 0.5467687                                 ⋯
10    0.1721436033                 0.5391568                                 ⋯
11    0.2213159663                 0.6177621                                 ⋯
12    0.2686570668                 0.5632230                                 ⋯
13    0.2554907234                 0.4964577                                 ⋯
14    0.1039181594                 0.4375836                                 ⋯
15    0.2333343763                 0.5278741                                 ⋯
16    0.0180137290                 0.4982482                                 ⋯
17    0.0133434790                 0.4766504                                 ⋯
18   -0.0245120191                 0.5350652                                 ⋯
19    0.0275194728                 0.4251316                                 ⋯
20    0.0215027164                 0.4409787                                 ⋯
21    0.0231572343                 0.4342355                                 ⋯
22    0.1683288650                 0.4377987                                 ⋯
23    0.2162597422                 0.5225767                                 ⋯
24    0.2096049667                 0.5392573                                 ⋯
25    0.1490873858                 0.4727064                                 ⋯
26    0.0341221372                 0.5749754                                 ⋯
27    0.0138892699                 0.5383954                                 ⋯
28   -0.0033931390                 0.5427944                                 ⋯
29   -0.0157613928                 0.3792495                                 ⋯
30    0.2147299782                 0.5387359                                 ⋯
⋮    ⋮                             ⋮                                         ⋱
1312 -0.0521683506                 0.5333082                                 ⋯
1313 -0.0132626171                 0.4613511                                 ⋯
1314 -0.0186972490                 0.4742595                                 ⋯
1315  0.0003455436                 0.4441811                                 ⋯
1316  0.1490294256                 0.4647612                                 ⋯
1317  0.2402799854                 0.5154737                                 ⋯
1318  0.2384188489                 0.5793572                                 ⋯
1319  0.2407435549                 0.6572234                                 ⋯
1320  0.0122737823                 0.5723411                                 ⋯
1321  0.0105199381                 0.5641419                                 ⋯
1322 -0.0226011780                 0.5631908                                 ⋯
1323 -0.0203238545                 0.5072353                                 ⋯
1324  0.2102027495                 0.5740994                                 ⋯
1325  0.2180042086                 0.5950476                                 ⋯
1326  0.2777241817                 0.5792867                                 ⋯
1327  0.2228411144                 0.6005778                                 ⋯
1328  0.2261344749                 0.5562555                                 ⋯
1329  0.1922491683                 0.5699013                                 ⋯
1330  0.2261455346                 0.5696642                                 ⋯
1331  0.2598527456                 0.5237715                                 ⋯
1332 -0.0116403593                 0.4861915                                 ⋯
1333 -0.0047986846                 0.4739374                                 ⋯
1334 -0.0298705386                 0.5137436                                 ⋯
1335  0.0190997831                 0.4421275                                 ⋯
1336  0.0054146048                 0.4467917                                 ⋯
1337  0.0253411158                 0.4467117                                 ⋯
1338  0.1809890440                 0.5100168                                 ⋯
1339  0.2516831943                 0.4788846                                 ⋯
1340  0.2225247969                 0.5212384                                 ⋯
1341  0.1769451836                 0.4798471                                 ⋯
     HALLMARK_WNT_BETA_CATENIN_SIGNALING1 HALLMARK_XENOBIOTIC_METABOLISM1 batch
1    -0.0764333981                        -0.0399335155                   1
2    -0.0618741085                        -0.0382576272                   1
3    -0.0485953088                        -0.0232917347                   1
4    -0.0429467262                        -0.0003601199                   1
5     0.0249519326                        -0.0378780752                   1
6     0.0095837796                        -0.0348825910                   1
7    -0.0162043032                        -0.0439173172                   1
8    -0.0050757465                        -0.0248334729                   1
9    -0.0203422446                        -0.0224637198                   1
10    0.0278913138                        -0.0364778357                   1
11   -0.0188633039                        -0.0286493946                   1
12   -0.0673347561                        -0.0235586328                   1
13   -0.0355177226                        -0.0276102828                   1
14   -0.0885570666                        -0.0275425859                   1
15   -0.0474612771                         0.0032465171                   1
16   -0.0431418486                         0.0511951700                   1
17   -0.0462904280                         0.0342033708                   1
18   -0.0821361691                         0.0388885605                   1
19   -0.0135488847                         0.0481048479                   1
20   -0.0291534362                         0.0431276308                   1
21   -0.0394188467                         0.0450046314                   1
22    0.0008390497                         0.0145710591                   1
23   -0.0753847715                         0.0058107133                   1
24    0.0092944279                        -0.0177674173                   1
25   -0.0952459894                         0.0120133490                   1
26   -0.0677868440                        -0.0361587859                   1
27   -0.0620545468                        -0.0346490023                   1
28   -0.0422706849                        -0.0229024497                   1
29   -0.0618012807                        -0.0031624242                   1
30    0.0309211753                        -0.0290838753                   1
⋮    ⋮                                    ⋮                               ⋮
1312 -0.0850136545                         0.056983736                    2
1313 -0.0331054300                         0.059444644                    2
1314 -0.0384196265                         0.047924396                    2
1315 -0.0520287087                         0.047528533                    2
1316 -0.0135574254                         0.033791284                    2
1317 -0.0801608536                         0.013863966                    2
1318  0.0061217735                         0.005363549                    2
1319 -0.1654990111                         0.049523043                    2
1320 -0.0750068363                        -0.029757825                    2
1321 -0.0683574596                        -0.026181378                    2
1322 -0.0627818955                        -0.024291377                    2
1323 -0.0750689710                         0.005234933                    2
1324  0.0367201066                        -0.027847642                    2
1325  0.0151238564                        -0.025578390                    2
1326  0.0115159949                        -0.031666840                    2
1327  0.0040210979                        -0.023081373                    2
1328 -0.0181926041                        -0.013928105                    2
1329  0.0383974414                        -0.022892710                    2
1330  0.0092430399                        -0.023667919                    2
1331 -0.0593891021                        -0.006798068                    2
1332 -0.0519761719                         0.056359318                    2
1333 -0.0562096139                         0.052241626                    2
1334 -0.0748679845                         0.045441513                    2

In [13]:
write.csv(
    dfp, 
    'data/06_pb/pb_donor_celltypelevel3_immport_hallmark_modulescores.csv'
)

# ssGSEA

Need to run this in R session
module load gcc/14.2.0 R/4.4.2

```r
library(GSVA)

gex = read.csv('data/06_pb/pb_donor_celltypelevel3_normalizedexpression.csv',
              row.names=1)

# hallmark
gset <- parse_gmt("data/11_genesets/h.all.v2024.1.Hs.symbols.gmt")

param <- ssgseaParam(
  as.matrix(gex),
  gset
)


ssgsea_scores <- gsva(
  param)

write.csv(
  as.data.frame(ssgsea_scores),
  file = "data/06_pb/pb_donor_celltypelevel3_ssgsea_hallmark.csv"
)

# immport
gset <- parse_gmt("data/11_genesets/immport_allgenelist.gmt")

param <- ssgseaParam(
  as.matrix(gex),
  gset
)

ssgsea_scores <- gsva(
  param)

write.csv(
  as.data.frame(ssgsea_scores),
  file = "data/06_pb/pb_donor_celltypelevel3_ssgsea_immport.csv"
)
```