Do leave out one patient for fig 5

# Header

In [1]:
from utils import *

In [2]:
import sys
sys.path.insert(0, '/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src')
import cna

In [3]:
import matplotlib.pyplot as plt
import matplotlib as mpl

In [4]:
os.chdir('../')

In [5]:
sc.settings.set_figure_params(dpi=600, dpi_save=600)  # 600 dpi for publication
sc.settings.figdir = "plots/Figure1"

rcParams.update({
    'font.family': 'Arial',
    'svg.fonttype': 'none',    # Keep SVG text as font
    'font.size': 6,            # Main font size (5–7pt recommended)
    'axes.titlesize': 7,
    'axes.labelsize': 6,
    'xtick.labelsize': 5,
    'ytick.labelsize': 5,
    'legend.fontsize': 6,
    'legend.title_fontsize': 6,
    'figure.dpi': 600,

    # --- Nature Immunology-style axes/ticks ---
    'axes.linewidth': 0.5,          # Axis lines: 0.5 pt
    'xtick.major.width': 0.5,        # Major tick lines
    'ytick.major.width': 0.5,
    'xtick.minor.width': 0.5,
    'ytick.minor.width': 0.5,
    'lines.linewidth': 0.7,          # Plot/data lines
    'axes.grid': False,              # No grid lines

    # --- Ticks on all sides ---
    'xtick.direction': 'out',
    'ytick.direction': 'out',
    'xtick.top': False,
    'xtick.bottom': False,
    'ytick.left': True,
    'ytick.right': False,


    # --- Tick label padding (minimal) ---
    'xtick.major.pad': 0,
    'ytick.major.pad': 0,

    # ---- Thin lines for Nature Immunology style ----
    'lines.linewidth': 0.5,     # General line width (default: 1.5)
    'patch.linewidth': 0.5,     # Outline for violin/bars (default: 1.0)
    
})

# plt.rcParams['axes.grid'] = False      # Extra guarantee, if using seaborn
# sns.set_style("white")                 # Removes upper/right axes and grid

# -- Scanpy vector-friendly mode --
sc.settings._vector_friendly = True

In [6]:
with open('data/Legends/celltypelevel3_palette.pkl','rb') as f:
    palette_all = pkl.load(f)

palette_all

{'Naive B': (0.843137, 0.0, 0.0),
 'Mature B': (0.54902, 0.235294, 1.0),
 'Memory B': (0.007843, 0.533333, 0.0),
 'Plasmablast': (0.0, 0.67451, 0.780392),
 'Naive CD4T': (0.596078, 1.0, 0.0),
 'Central Memory CD4T': (1.0, 0.498039, 0.819608),
 'Effector Memory CD4T': (0.423529, 0.0, 0.309804),
 'Cytotoxic CD4T': (1.0, 0.647059, 0.188235),
 'Treg': (0.345098, 0.231373, 0.0),
 'Naive CD8T': (0.0, 0.341176, 0.34902),
 'Central Memory CD8T': (0.0, 0.0, 0.866667),
 'Effector Memory CD8T': (0.0, 0.992157, 0.811765),
 'Double Negative T': (0.631373, 0.458824, 0.415686),
 'γδ T': (0.737255, 0.717647, 1.0),
 'MAIT': (0.584314, 0.709804, 0.470588),
 'cDC1': (0.752941, 0.015686, 0.72549),
 'cDC2': (0.392157, 0.329412, 0.454902),
 'pDC': (0.47451, 0.0, 0.0),
 'Classical Monocyte': (0.027451, 0.454902, 0.847059),
 'Intermediate Monocyte': (0.996078, 0.960784, 0.564706),
 'Nonclassical Monocyte': (0.0, 0.294118, 0.0),
 'Cytotoxic Monocyte': (0.560784, 0.478431, 0.0),
 'CD56-dim NK': (1.0, 0.447059, 0.4),
 'CD56-bright NK': (0.933333, 0.72549, 0.72549),
 'Proliferating NK': (0.368627, 0.494118, 0.4)}

In [7]:
# major_celltype_palette = {
#     'B':    '#3072C4',   # strong blue
#     'T':    '#EF763F',   # bold orange
#     'DC':   '#35A293',   # teal
#     'Mono': '#B3813E',   # rich brown/gold
#     'NK':   '#7D4C99',   # deep purple
# }

cells_group = {
    'B':['Naive B',
 'Mature B',
 'Memory B',
 'Plasmablast'],
    'T':['Naive CD4T',
 'Central Memory CD4T',
 'Effector Memory CD4T',
 'Cytotoxic CD4T',
 'Treg',
 'Naive CD8T',
 'Central Memory CD8T',
 'Effector Memory CD8T',
 'Double Negative T',
 'γδ T',
 'MAIT'],
    'DC':[
   'cDC1',
 'cDC2',
 'pDC'     
    ],
    'Mono':[
        'Classical Monocyte',
 'Intermediate Monocyte',
 'Nonclassical Monocyte',
 'Cytotoxic Monocyte'
        ],
    'NK':[
        'CD56-dim NK',
 'CD56-bright NK',
 'Proliferating NK'
    ]
}

# Prep data

In [8]:
meta = pd.read_csv('data/01_meta/meta_pt.csv')#, index_col=0)
#meta.index = [x.replace('_','-') for x in meta.index]

meta['race-stage'] = meta['race'].astype(str) + '-' + meta['group'].astype(str)
meta = meta.drop(columns = ['race_stage'])

meta['race-stage'] = pd.Categorical(
    meta['race-stage'],
    categories=['NHW-HRL', 'NHW-DCIS', 'NHW-BC','NHB-HRL', 'NHB-DCIS', 'NHB-BC'],
    ordered=True
    )

meta

,sampleid,dataset_name,batch,viability_pct,group,race,age,diabetes,obesity,race-stage
0,9-D,Pool137_7,1,95,DCIS,NHW,37.0,N,Y,NHW-DCIS
1,30-D,Pool137_12,1,92,DCIS,NHW,78.0,N,N,NHW-DCIS
2,36-D,Pool137_18,1,93,DCIS,NHB,39.0,N,Y,NHB-DCIS
3,119-D,Pool137_20,1,95,DCIS,NHB,80.0,N,Y,NHB-DCIS
4,28-D,Pool137_24,1,94,DCIS,NHW,53.0,N,N,NHW-DCIS
5,53-D,Pool137_27,1,96,DCIS,NHB,45.0,N,N,NHB-DCIS
6,77-D,Pool137_30,1,90,DCIS,NHW,45.0,N,N,NHW-DCIS
7,31-D,Pool138_6,2,93,DCIS,NHW,44.0,N,N,NHW-DCIS
8,6-H,Pool137_6,1,94,HRL,NHW,71.1,N,Y,NHW-HRL
9,1-H,Pool137_10,1,88,HRL,NHW,62.3,N,N,NHW-HRL
10,43-H,Pool137_14,1,91,HRL,NHW,42.5,N,Y,NHW-HRL
11,336-H,Pool137_21,1,91,HRL,NHB,43.8,N,Y,NHB-HRL
12,1160-H,Pool137_22,1,92,HRL,NHB,69.3,N,N,NHB-HRL
13,36-H,Pool137_25,1,90,HRL,NHW,59.6,N,N,NHW-HRL
14,42-H,Pool137_26,1,91,HRL,NHW,53.1,N,N,NHW-HRL
15,61-H,Pool137_29,1,90,HRL,NHW,59.6,N,N,NHW-HRL
16,133-H,Pool137_33,1,87,HRL,NHB,44.5,N,Y,NHB-HRL
17,1269-H,Pool137_34,1,92,HRL,NHB,62.7,N,N,NHB-HRL
18,2207-H,Pool137_35,1,94,HRL,NHB,48.2,N,N,NHB-HRL
19,24-H,Pool138_4,2,94,HRL,NHW,60.5,N,Y,NHW-HRL
20,63-H,Pool138_9,2,98,HRL,NHW,57.7,N,Y,NHW-HRL
21,102-H,Pool138_10,2,91,HRL,NHB,63.9,N,Y,NHB-HRL
22,568-H,Pool138_14,2,93,HRL,NHW,43.7,N,N,NHW-HRL
23,956-H,Pool138_15,2,89,HRL,NHW,42.8,N,N,NHW-HRL
24,19-I,Pool137_11,1,92,BC,NHW,48.0,N,N,NHW-BC
25,45-I,Pool137_15,1,91,BC,NHW,67.0,N,N,NHW-BC
26,56-I,Pool137_16,1,92,BC,NHB,60.0,N,Y,NHB-BC
27,64-I,Pool137_17,1,90,BC,NHB,54.0,N,Y,NHB-BC
28,37-I,Pool137_19,1,93,BC,NHW,79.0,N,N,NHW-BC
29,27-I,Pool137_23,1,92,BC,NHW,66.0,N,N,NHW-BC
30,58-I,Pool137_28,1,95,BC,NHW,63.0,N,N,NHW-BC
31,4-I,Pool137_31,1,91,BC,NHB,47.0,N,Y,NHB-BC
32,23-I,Pool138_3,2,96,BC,NHW,46.0,N,Y,NHW-BC
33,26-I,Pool138_5,2,95,BC,NHW,67.0,N,N,NHW-BC
34,36-I,Pool138_7,2,93,BC,NHW,67.0,N,Y,NHW-BC
35,50-I,Pool138_8,2,95,BC,NHW,44.0,N,Y,NHW-BC
36,38-I,Pool138_12,2,93,BC,NHW,69.0,N,N,NHW-BC
37,77-I,Pool138_18,2,84,BC,NHB,60.0,N,N,NHB-BC
38,76-I,Pool138_19,2,93,BC,NHB,45.0,N,Y,NHB-BC
39,66-I,Pool138_21,2,92,BC,NHW,41.0,N,N,NHW-BC
40,71-I,Pool138_22,2,88,BC,NHB,36.0,N,N,NHB-BC
41,57-I,Pool138_23,2,91,BC,NHB,34.0,N,Y,NHB-BC
42,55-I,Pool138_24,2,94,BC,NHW,33.0,N,N,NHW-BC
43,31-I,Pool138_25,2,95,BC,NHB,31.0,N,N,NHB-BC
44,11-I,Pool138_27,2,93,BC,NHB,45.0,N,Y,NHB-BC
45,99-I,Pool138_29,2,80,BC,NHB,69.0,N,N,NHB-BC
46,54-D,Pool137_8,1,87,DCIS,NHB,53.0,Y,Y,NHB-DCIS
47,79-D,Pool137_36,1,90,DCIS,NHW,62.0,Y,Y,NHW-DCIS
48,3145-H,Pool137_9,1,84,HRL,NHB,58.9,Y,N,NHB-HRL
49,466-H,Pool138_11,2,92,HRL,NHB,63.0,Y,N,NHB-HRL
50,170-H,Pool138_13,2,84,HRL,NHB,60.9,Y,N,NHB-HRL
51,2176-H,Pool138_16,2,94,HRL,NHB,54.7,Y,Y,NHB-HRL
52,101-I,Pool138_17,2,84,BC,NHB,74.0,Y,N,NHB-BC
53,73-I,Pool138_20,2,95,BC,NHB,82.0,Y,Y,NHB-BC
54,28-I,Pool138_26,2,94,BC,NHB,86.0,Y,Y,NHB-BC

In [9]:
dat = sc.read_h5ad(
    'data/03_cleandata/ft_all.h5ad'
)

dat

AnnData object with n_obs × n_vars = 434565 × 27879
    obs: 'nFeaturess_RNA', 'nFeaturess_RNA_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'doublets_score', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'predicted.celltype.l1.score', 'predicted.celltype.l1', 'predicted.celltype.l2.score', 'predicted.celltype.l2', 'predicted.celltype.l3.score', 'predicted.celltype.l3', 'mapping.score', 'RNA_snn_res.0.8', 'seurat_clusters', 'dataset_name', 'RNA_snn_res.0.1', 'S.Score', 'G2M.Score', 'Phase', 'celltype_level3'
    var: 'vf_vst_counts.Pool137_10_mean', 'vf_vst_counts.Pool137_10_variance', 'vf_vst_counts.Pool137_10_variance.expected', 'vf_vst_counts.Pool137_10_variance.standardized', 'vf_vst_counts.Pool137_10_variable', 'vf_vst_counts.Pool137_10_rank', 'vf_vst_counts.Pool137_11_mean', 'vf_vst_counts.Pool137_11_variance', 'vf_vst_counts.Pool137_11_variance.expected', 'vf_vst_counts.Pool137_11_variance.standardized', 'vf_vst_counts.Pool137_11_variable', 'vf_vst_counts.Pool137_11_rank', 'vf_vst_counts.Pool137_12_mean', 'vf_vst_counts.Pool137_12_variance', 'vf_vst_counts.Pool137_12_variance.expected', 'vf_vst_counts.Pool137_12_variance.standardized', 'vf_vst_counts.Pool137_12_variable', 'vf_vst_counts.Pool137_12_rank', 'vf_vst_counts.Pool137_14_mean', 'vf_vst_counts.Pool137_14_variance', 'vf_vst_counts.Pool137_14_variance.expected', 'vf_vst_counts.Pool137_14_variance.standardized', 'vf_vst_counts.Pool137_14_variable', 'vf_vst_counts.Pool137_14_rank', 'vf_vst_counts.Pool137_15_mean', 'vf_vst_counts.Pool137_15_variance', 'vf_vst_counts.Pool137_15_variance.expected', 'vf_vst_counts.Pool137_15_variance.standardized', 'vf_vst_counts.Pool137_15_variable', 'vf_vst_counts.Pool137_15_rank', 'vf_vst_counts.Pool137_16_mean', 'vf_vst_counts.Pool137_16_variance', 'vf_vst_counts.Pool137_16_variance.expected', 'vf_vst_counts.Pool137_16_variance.standardized', 'vf_vst_counts.Pool137_16_variable', 'vf_vst_counts.Pool137_16_rank', 'vf_vst_counts.Pool137_17_mean', 'vf_vst_counts.Pool137_17_variance', 'vf_vst_counts.Pool137_17_variance.expected', 'vf_vst_counts.Pool137_17_variance.standardized', 'vf_vst_counts.Pool137_17_variable', 'vf_vst_counts.Pool137_17_rank', 'vf_vst_counts.Pool137_18_mean', 'vf_vst_counts.Pool137_18_variance', 'vf_vst_counts.Pool137_18_variance.expected', 'vf_vst_counts.Pool137_18_variance.standardized', 'vf_vst_counts.Pool137_18_variable', 'vf_vst_counts.Pool137_18_rank', 'vf_vst_counts.Pool137_19_mean', 'vf_vst_counts.Pool137_19_variance', 'vf_vst_counts.Pool137_19_variance.expected', 'vf_vst_counts.Pool137_19_variance.standardized', 'vf_vst_counts.Pool137_19_variable', 'vf_vst_counts.Pool137_19_rank', 'vf_vst_counts.Pool137_20_mean', 'vf_vst_counts.Pool137_20_variance', 'vf_vst_counts.Pool137_20_variance.expected', 'vf_vst_counts.Pool137_20_variance.standardized', 'vf_vst_counts.Pool137_20_variable', 'vf_vst_counts.Pool137_20_rank', 'vf_vst_counts.Pool137_21_mean', 'vf_vst_counts.Pool137_21_variance', 'vf_vst_counts.Pool137_21_variance.expected', 'vf_vst_counts.Pool137_21_variance.standardized', 'vf_vst_counts.Pool137_21_variable', 'vf_vst_counts.Pool137_21_rank', 'vf_vst_counts.Pool137_22_mean', 'vf_vst_counts.Pool137_22_variance', 'vf_vst_counts.Pool137_22_variance.expected', 'vf_vst_counts.Pool137_22_variance.standardized', 'vf_vst_counts.Pool137_22_variable', 'vf_vst_counts.Pool137_22_rank', 'vf_vst_counts.Pool137_23_mean', 'vf_vst_counts.Pool137_23_variance', 'vf_vst_counts.Pool137_23_variance.expected', 'vf_vst_counts.Pool137_23_variance.standardized', 'vf_vst_counts.Pool137_23_variable', 'vf_vst_counts.Pool137_23_rank', 'vf_vst_counts.Pool137_24_mean', 'vf_vst_counts.Pool137_24_variance', 'vf_vst_counts.Pool137_24_variance.expected', 'vf_vst_counts.Pool137_24_variance.standardized', 'vf_vst_counts.Pool137_24_variable', 'vf_vst_counts.Pool137_24_rank', 'vf_vst_counts.Pool137_25_mean', 'vf_vst_counts.Pool137_25_variance', 'vf_vst_counts.Pool137_25_variance.expected', 'vf_vst_counts.Pool137_25_variance.standardized', 'vf_vst_counts.Pool137_25_variable', 'vf_vst_counts.Pool137_25_rank', 'vf_vst_counts.Pool137_26_mean', 'vf_vst_counts.Pool137_26_variance', 'vf_vst_counts.Pool137_26_variance.expected', 'vf_vst_counts.Pool137_26_variance.standardized', 'vf_vst_counts.Pool137_26_variable', 'vf_vst_counts.Pool137_26_rank', 'vf_vst_counts.Pool137_27_mean', 'vf_vst_counts.Pool137_27_variance', 'vf_vst_counts.Pool137_27_variance.expected', 'vf_vst_counts.Pool137_27_variance.standardized', 'vf_vst_counts.Pool137_27_variable', 'vf_vst_counts.Pool137_27_rank', 'vf_vst_counts.Pool137_28_mean', 'vf_vst_counts.Pool137_28_variance', 'vf_vst_counts.Pool137_28_variance.expected', 'vf_vst_counts.Pool137_28_variance.standardized', 'vf_vst_counts.Pool137_28_variable', 'vf_vst_counts.Pool137_28_rank', 'vf_vst_counts.Pool137_29_mean', 'vf_vst_counts.Pool137_29_variance', 'vf_vst_counts.Pool137_29_variance.expected', 'vf_vst_counts.Pool137_29_variance.standardized', 'vf_vst_counts.Pool137_29_variable', 'vf_vst_counts.Pool137_29_rank', 'vf_vst_counts.Pool137_30_mean', 'vf_vst_counts.Pool137_30_variance', 'vf_vst_counts.Pool137_30_variance.expected', 'vf_vst_counts.Pool137_30_variance.standardized', 'vf_vst_counts.Pool137_30_variable', 'vf_vst_counts.Pool137_30_rank', 'vf_vst_counts.Pool137_31_mean', 'vf_vst_counts.Pool137_31_variance', 'vf_vst_counts.Pool137_31_variance.expected', 'vf_vst_counts.Pool137_31_variance.standardized', 'vf_vst_counts.Pool137_31_variable', 'vf_vst_counts.Pool137_31_rank', 'vf_vst_counts.Pool137_32_mean', 'vf_vst_counts.Pool137_32_variance', 'vf_vst_counts.Pool137_32_variance.expected', 'vf_vst_counts.Pool137_32_variance.standardized', 'vf_vst_counts.Pool137_32_variable', 'vf_vst_counts.Pool137_32_rank', 'vf_vst_counts.Pool137_33_mean', 'vf_vst_counts.Pool137_33_variance', 'vf_vst_counts.Pool137_33_variance.expected', 'vf_vst_counts.Pool137_33_variance.standardized', 'vf_vst_counts.Pool137_33_variable', 'vf_vst_counts.Pool137_33_rank', 'vf_vst_counts.Pool137_34_mean', 'vf_vst_counts.Pool137_34_variance', 'vf_vst_counts.Pool137_34_variance.expected', 'vf_vst_counts.Pool137_34_variance.standardized', 'vf_vst_counts.Pool137_34_variable', 'vf_vst_counts.Pool137_34_rank', 'vf_vst_counts.Pool137_35_mean', 'vf_vst_counts.Pool137_35_variance', 'vf_vst_counts.Pool137_35_variance.expected', 'vf_vst_counts.Pool137_35_variance.standardized', 'vf_vst_counts.Pool137_35_variable', 'vf_vst_counts.Pool137_35_rank', 'vf_vst_counts.Pool137_36_mean', 'vf_vst_counts.Pool137_36_variance', 'vf_vst_counts.Pool137_36_variance.expected', 'vf_vst_counts.Pool137_36_variance.standardized', 'vf_vst_counts.Pool137_36_variable', 'vf_vst_counts.Pool137_36_rank', 'vf_vst_counts.Pool137_6_mean', 'vf_vst_counts.Pool137_6_variance', 'vf_vst_counts.Pool137_6_variance.expected', 'vf_vst_counts.Pool137_6_variance.standardized', 'vf_vst_counts.Pool137_6_variable', 'vf_vst_counts.Pool137_6_rank', 'vf_vst_counts.Pool137_7_mean', 'vf_vst_counts.Pool137_7_variance', 'vf_vst_counts.Pool137_7_variance.expected', 'vf_vst_counts.Pool137_7_variance.standardized', 'vf_vst_counts.Pool137_7_variable', 'vf_vst_counts.Pool137_7_rank', 'vf_vst_counts.Pool137_8_mean', 'vf_vst_counts.Pool137_8_variance', 'vf_vst_counts.Pool137_8_variance.expected', 'vf_vst_counts.Pool137_8_variance.standardized', 'vf_vst_counts.Pool137_8_variable', 'vf_vst_counts.Pool137_8_rank', 'vf_vst_counts.Pool137_9_mean', 'vf_vst_counts.Pool137_9_variance', 'vf_vst_counts.Pool137_9_variance.expected', 'vf_vst_counts.Pool137_9_variance.standardized', 'vf_vst_counts.Pool137_9_variable', 'vf_vst_counts.Pool137_9_rank', 'vf_vst_counts.Pool138_10_mean', 'vf_vst_counts.Pool138_10_variance', 'vf_vst_counts.Pool138_10_variance.expected', 'vf_vst_counts.Pool138_10_variance.standardized', 'vf_vst_counts.Pool138_10_variable', 'vf_vst_counts.Pool138_10_rank', 'vf_vst_counts.Pool138_11_mean', 'vf_vst_counts.Pool138_11_variance', 'vf_vst_counts.Pool138_11_variance.expected', 'vf_vst_counts.Pool138_11_variance.standardized', 'vf_vst_counts.Pool138_11_variable', 'vf_vst_counts.Pool138_11_rank', 'vf_vst_counts.Pool138_12_mean', 'vf_vst_counts.Pool138_12_variance', 'vf_vst_counts.Pool138_12_variance.expected', 'vf_vst_counts.Pool138_12_variance.standardized', 'vf_vst_counts.Pool138_12_variable', 'vf_vst_counts.Pool138_12_rank', 'vf_vst_counts.Pool138_13_mean', 'vf_vst_counts.Pool138_13_variance', 'vf_vst_counts.Pool138_13_variance.expected', 'vf_vst_counts.Pool138_13_variance.standardized', 'vf_vst_counts.Pool138_13_variable', 'vf_vst_counts.Pool138_13_rank', 'vf_vst_counts.Pool138_14_mean', 'vf_vst_counts.Pool138_14_variance', 'vf_vst_counts.Pool138_14_variance.expected', 'vf_vst_counts.Pool138_14_variance.standardized', 'vf_vst_counts.Pool138_14_variable', 'vf_vst_counts.Pool138_14_rank', 'vf_vst_counts.Pool138_15_mean', 'vf_vst_counts.Pool138_15_variance', 'vf_vst_counts.Pool138_15_variance.expected', 'vf_vst_counts.Pool138_15_variance.standardized', 'vf_vst_counts.Pool138_15_variable', 'vf_vst_counts.Pool138_15_rank', 'vf_vst_counts.Pool138_16_mean', 'vf_vst_counts.Pool138_16_variance', 'vf_vst_counts.Pool138_16_variance.expected', 'vf_vst_counts.Pool138_16_variance.standardized', 'vf_vst_counts.Pool138_16_variable', 'vf_vst_counts.Pool138_16_rank', 'vf_vst_counts.Pool138_17_mean', 'vf_vst_counts.Pool138_17_variance', 'vf_vst_counts.Pool138_17_variance.expected', 'vf_vst_counts.Pool138_17_variance.standardized', 'vf_vst_counts.Pool138_17_variable', 'vf_vst_counts.Pool138_17_rank', 'vf_vst_counts.Pool138_18_mean', 'vf_vst_counts.Pool138_18_variance', 'vf_vst_counts.Pool138_18_variance.expected', 'vf_vst_counts.Pool138_18_variance.standardized', 'vf_vst_counts.Pool138_18_variable', 'vf_vst_counts.Pool138_18_rank', 'vf_vst_counts.Pool138_19_mean', 'vf_vst_counts.Pool138_19_variance', 'vf_vst_counts.Pool138_19_variance.expected', 'vf_vst_counts.Pool138_19_variance.standardized', 'vf_vst_counts.Pool138_19_variable', 'vf_vst_counts.Pool138_19_rank', 'vf_vst_counts.Pool138_20_mean', 'vf_vst_counts.Pool138_20_variance', 'vf_vst_counts.Pool138_20_variance.expected', 'vf_vst_counts.Pool138_20_variance.standardized', 'vf_vst_counts.Pool138_20_variable', 'vf_vst_counts.Pool138_20_rank', 'vf_vst_counts.Pool138_21_mean', 'vf_vst_counts.Pool138_21_variance', 'vf_vst_counts.Pool138_21_variance.expected', 'vf_vst_counts.Pool138_21_variance.standardized', 'vf_vst_counts.Pool138_21_variable', 'vf_vst_counts.Pool138_21_rank', 'vf_vst_counts.Pool138_22_mean', 'vf_vst_counts.Pool138_22_variance', 'vf_vst_counts.Pool138_22_variance.expected', 'vf_vst_counts.Pool138_22_variance.standardized', 'vf_vst_counts.Pool138_22_variable', 'vf_vst_counts.Pool138_22_rank', 'vf_vst_counts.Pool138_23_mean', 'vf_vst_counts.Pool138_23_variance', 'vf_vst_counts.Pool138_23_variance.expected', 'vf_vst_counts.Pool138_23_variance.standardized', 'vf_vst_counts.Pool138_23_variable', 'vf_vst_counts.Pool138_23_rank', 'vf_vst_counts.Pool138_24_mean', 'vf_vst_counts.Pool138_24_variance', 'vf_vst_counts.Pool138_24_variance.expected', 'vf_vst_counts.Pool138_24_variance.standardized', 'vf_vst_counts.Pool138_24_variable', 'vf_vst_counts.Pool138_24_rank', 'vf_vst_counts.Pool138_25_mean', 'vf_vst_counts.Pool138_25_variance', 'vf_vst_counts.Pool138_25_variance.expected', 'vf_vst_counts.Pool138_25_variance.standardized', 'vf_vst_counts.Pool138_25_variable', 'vf_vst_counts.Pool138_25_rank', 'vf_vst_counts.Pool138_26_mean', 'vf_vst_counts.Pool138_26_variance', 'vf_vst_counts.Pool138_26_variance.expected', 'vf_vst_counts.Pool138_26_variance.standardized', 'vf_vst_counts.Pool138_26_variable', 'vf_vst_counts.Pool138_26_rank', 'vf_vst_counts.Pool138_27_mean', 'vf_vst_counts.Pool138_27_variance', 'vf_vst_counts.Pool138_27_variance.expected', 'vf_vst_counts.Pool138_27_variance.standardized', 'vf_vst_counts.Pool138_27_variable', 'vf_vst_counts.Pool138_27_rank', 'vf_vst_counts.Pool138_29_mean', 'vf_vst_counts.Pool138_29_variance', 'vf_vst_counts.Pool138_29_variance.expected', 'vf_vst_counts.Pool138_29_variance.standardized', 'vf_vst_counts.Pool138_29_variable', 'vf_vst_counts.Pool138_29_rank', 'vf_vst_counts.Pool138_3_mean', 'vf_vst_counts.Pool138_3_variance', 'vf_vst_counts.Pool138_3_variance.expected', 'vf_vst_counts.Pool138_3_variance.standardized', 'vf_vst_counts.Pool138_3_variable', 'vf_vst_counts.Pool138_3_rank', 'vf_vst_counts.Pool138_4_mean', 'vf_vst_counts.Pool138_4_variance', 'vf_vst_counts.Pool138_4_variance.expected', 'vf_vst_counts.Pool138_4_variance.standardized', 'vf_vst_counts.Pool138_4_variable', 'vf_vst_counts.Pool138_4_rank', 'vf_vst_counts.Pool138_5_mean', 'vf_vst_counts.Pool138_5_variance', 'vf_vst_counts.Pool138_5_variance.expected', 'vf_vst_counts.Pool138_5_variance.standardized', 'vf_vst_counts.Pool138_5_variable', 'vf_vst_counts.Pool138_5_rank', 'vf_vst_counts.Pool138_6_mean', 'vf_vst_counts.Pool138_6_variance', 'vf_vst_counts.Pool138_6_variance.expected', 'vf_vst_counts.Pool138_6_variance.standardized', 'vf_vst_counts.Pool138_6_variable', 'vf_vst_counts.Pool138_6_rank', 'vf_vst_counts.Pool138_7_mean', 'vf_vst_counts.Pool138_7_variance', 'vf_vst_counts.Pool138_7_variance.expected', 'vf_vst_counts.Pool138_7_variance.standardized', 'vf_vst_counts.Pool138_7_variable', 'vf_vst_counts.Pool138_7_rank', 'vf_vst_counts.Pool138_8_mean', 'vf_vst_counts.Pool138_8_variance', 'vf_vst_counts.Pool138_8_variance.expected', 'vf_vst_counts.Pool138_8_variance.standardized', 'vf_vst_counts.Pool138_8_variable', 'vf_vst_counts.Pool138_8_rank', 'vf_vst_counts.Pool138_9_mean', 'vf_vst_counts.Pool138_9_variance', 'vf_vst_counts.Pool138_9_variance.expected', 'vf_vst_counts.Pool138_9_variance.standardized', 'vf_vst_counts.Pool138_9_variable', 'vf_vst_counts.Pool138_9_rank', 'var.features', 'var.features.rank'
    obsm: 'X_harmony', 'X_pca', 'X_umap'

In [10]:
for col in ['sampleid', 'age', 'race-stage', 'race', 'group', 'diabetes', 'obesity']:
    dat.obs[col] = dat.obs['dataset_name'].map(meta.set_index('dataset_name')[col])
    
for xcol in ['diabetes','obesity']:
    dat.obs[xcol] = [1 if x=='Y' else 0 for x in dat.obs[xcol]]

xcol = 'group'
dat.obs[xcol] = [0 if x=='HRL' else 1 if x=='DCIS' else 2 for x in dat.obs[xcol]]

xcol = 'race'
dat.obs[xcol] = [0 if x=='NHW' else 1 if x=='NHB' else None for x in dat.obs[xcol]]

dat.obs.columns

Index(['nFeaturess_RNA', 'nFeaturess_RNA_by_counts', 'total_counts',
       'total_counts_mt', 'pct_counts_mt', 'doublets_score', 'nCount_RNA',
       'nFeature_RNA', 'percent.mt', 'predicted.celltype.l1.score',
       'predicted.celltype.l1', 'predicted.celltype.l2.score',
       'predicted.celltype.l2', 'predicted.celltype.l3.score',
       'predicted.celltype.l3', 'mapping.score', 'RNA_snn_res.0.8',
       'seurat_clusters', 'dataset_name', 'RNA_snn_res.0.1', 'S.Score',
       'G2M.Score', 'Phase', 'celltype_level3', 'sampleid', 'age',
       'race-stage', 'race', 'group', 'diabetes', 'obesity'],
      dtype='object')

In [11]:
dat.obs.head(3)

,nFeaturess_RNA,nFeaturess_RNA_by_counts,total_counts,total_counts_mt,pct_counts_mt,doublets_score,nCount_RNA,nFeature_RNA,percent.mt,predicted.celltype.l1.score,...,G2M.Score,Phase,celltype_level3,sampleid,age,race-stage,race,group,diabetes,obesity
Pool137_10_AAACCTGAGACTCGGA-1,1095.0,1095,2669.0,80.0,2.997377,0.039230,2669.0,1095.0,2.997377,0.987477,...,-0.030749,G1,Naive CD4T,1-H,62.3,NHW-HRL,0,0,0,0
Pool137_10_AAACCTGAGATCTGCT-1,2474.0,2472,6188.0,178.0,2.876535,0.021953,6188.0,2472.0,2.876535,1.000000,...,0.004461,S,Nonclassical Monocyte,1-H,62.3,NHW-HRL,0,0,0,0
Pool137_10_AAACCTGAGATTACCC-1,1436.0,1436,3504.0,100.0,2.853881,0.039230,3504.0,1436.0,2.853881,0.996618,...,-0.066766,S,Naive CD8T,1-H,62.3,NHW-HRL,0,0,0,0

# Analysis

In [12]:
import numpy as np
import pandas as pd
import scanpy as sc
from datetime import datetime
import time
import gc

results = []

celltypes_major = [
    'B', 'CD4 T', 'CD8 T', 'other T',
    'DC', 'Mono', 'NK'
]

patients_loo = dat.obs['dataset_name'].dropna().unique()

n_total = len(celltypes_major) * len(patients_loo)
counter = 0

def now():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


for celltype_major in celltypes_major:

    for pt_loo in patients_loo:

        counter += 1
        t0 = time.time()

        print(
            f"\n[{now()}] Start {counter}/{n_total}: "
            f"celltype={celltype_major}, leave_out={pt_loo}",
            flush=True
        )

        try:
            d = dat[
                (dat.obs['predicted.celltype.l1'] == celltype_major) &
                (dat.obs['dataset_name'] != pt_loo)
            ].copy()

            total_cells_before = d.n_obs

            if d.n_obs < 50:
                print(
                    f"[{now()}] SKIP: too few cells after filtering: {d.n_obs}",
                    flush=True
                )

                results.append({
                    'celltype_major': celltype_major,
                    'pt_loo': pt_loo,
                    'testvar': 'race',
                    'status': 'skipped_too_few_cells',
                    'global_p': np.nan,
                    'totalCells': d.n_obs,
                    'nan%': np.nan,
                    'pos%': np.nan,
                    'neg%': np.nan,
                    'zero%': np.nan,
                    'elapsed_min': (time.time() - t0) / 60
                })

                del d
                gc.collect()
                continue

            print(f"[{now()}] Running neighbors: n_cells={d.n_obs}", flush=True)
            sc.pp.neighbors(d)

            print(f"[{now()}] Building sample metadata", flush=True)

            samplem = cna.ut.obs_to_sample(
                d,
                ['group', 'race', 'age', 'obesity', 'diabetes'],
                'dataset_name'
            )

            samplem['batch'] = [
                'Pool137' if str(x).startswith('Pool137') else 'Pool138'
                for x in samplem.index
            ]

            testvar = 'race'
            covars = ['group', 'age']

            # Add optional covariates only if variable exists and has >1 value after LOO
            for v in ['obesity', 'diabetes']:
                if v in samplem.columns and samplem[v].dropna().nunique() > 1:
                    covars.append(v)

            # Sanity checks after leave-one-out
            if samplem[testvar].dropna().nunique() < 2:
                print(
                    f"[{now()}] SKIP: {testvar} has <2 levels after leaving out {pt_loo}",
                    flush=True
                )

                results.append({
                    'celltype_major': celltype_major,
                    'pt_loo': pt_loo,
                    'testvar': testvar,
                    'status': 'skipped_testvar_one_level',
                    'global_p': np.nan,
                    'totalCells': d.n_obs,
                    'nan%': np.nan,
                    'pos%': np.nan,
                    'neg%': np.nan,
                    'zero%': np.nan,
                    'elapsed_min': (time.time() - t0) / 60
                })

                del d
                gc.collect()
                continue

            # Drop covariates that became constant after LOO
            covars = [
                v for v in covars
                if v in samplem.columns and samplem[v].dropna().nunique() > 1
            ]

            print(
                f"[{now()}] Running CNA association: "
                f"testvar={testvar}, covars={covars}, n_samples={samplem.shape[0]}",
                flush=True
            )

            p = cna.tl.association(
                d,
                samplem[testvar],
                'dataset_name',
                covs=samplem[covars],
                batches=samplem['batch'],
                key_added=f'{testvar}_coef'
            )

            d.uns[f'cnaGlobalPval_{testvar}'] = p

            coef_col = f"{testvar}_coef"
            fdr_col = f"{testvar}_coef_fdr"
            color_col = f"{testvar}_coef_plot"

            if coef_col not in d.obs.columns or fdr_col not in d.obs.columns:
                raise ValueError(
                    f"Expected CNA columns not found. "
                    f"Missing? coef_col={coef_col in d.obs.columns}, "
                    f"fdr_col={fdr_col in d.obs.columns}"
                )

            d.obs[color_col] = np.where(
                d.obs[fdr_col] < 0.1,
                d.obs[coef_col],
                np.nan
            )

            coln = d.obs[color_col]
            total = len(coln)

            n_nan = coln.isna().sum()
            n_pos = ((~coln.isna()) & (coln > 0)).sum()
            n_neg = ((~coln.isna()) & (coln < 0)).sum()
            n_zero = ((~coln.isna()) & (coln == 0)).sum()

            elapsed_min = (time.time() - t0) / 60

            print(
                f"[{now()}] DONE {counter}/{n_total}: "
                f"celltype={celltype_major}, leave_out={pt_loo}, "
                f"global_p={p:.3g}, elapsed={elapsed_min:.2f} min",
                flush=True
            )

            print(
                f"    total={total}, sanity={n_nan + n_pos + n_neg + n_zero}, "
                f"nan={n_nan}, >0={n_pos}, <0={n_neg}, =0={n_zero}",
                flush=True
            )

            results.append({
                'celltype_major': celltype_major,
                'pt_loo': pt_loo,
                'testvar': testvar,
                'covars': ','.join(covars),
                'status': 'ok',
                'global_p': p,
                'totalCells': total,
                'nan%': n_nan / total * 100,
                'pos%': n_pos / total * 100,
                'neg%': n_neg / total * 100,
                'zero%': n_zero / total * 100,
                'elapsed_min': elapsed_min
            })

            del d
            gc.collect()

        except Exception as e:

            elapsed_min = (time.time() - t0) / 60

            print(
                f"[{now()}] ERROR {counter}/{n_total}: "
                f"celltype={celltype_major}, leave_out={pt_loo}, "
                f"elapsed={elapsed_min:.2f} min",
                flush=True
            )
            print(f"    Error: {repr(e)}", flush=True)

            results.append({
                'celltype_major': celltype_major,
                'pt_loo': pt_loo,
                'testvar': 'race',
                'status': 'error',
                'error': repr(e),
                'global_p': np.nan,
                'totalCells': np.nan,
                'nan%': np.nan,
                'pos%': np.nan,
                'neg%': np.nan,
                'zero%': np.nan,
                'elapsed_min': elapsed_min
            })

            try:
                del d
            except NameError:
                pass

            gc.collect()


df_summary = pd.DataFrame(results)
df_summary.to_csv('data/10_cna/LLO_stats.csv')

[2026-06-24 08:32:02] Start 1/385: celltype=B, leave_out=Pool137_10
[2026-06-24 08:32:09] Running neighbors: n_cells=48933
[2026-06-24 08:32:36] Building sample metadata
[2026-06-24 08:32:36] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:32:48] DONE 1/385: celltype=B, leave_out=Pool137_10, global_p=0.000999, elapsed=0.77 min
    total=48933, sanity=48933, nan=46513, >0=34, <0=2386, =0=0

[2026-06-24 08:32:48] Start 2/385: celltype=B, leave_out=Pool137_11
[2026-06-24 08:32:54] Running neighbors: n_cells=48732
[2026-06-24 08:32:59] Building sample metadata
[2026-06-24 08:32:59] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:33:11] DONE 2/385: celltype=B, leave_out=Pool137_11, global_p=0.000999, elapsed=0.37 min
    total=48732, sanity=48732, nan=46661, >0=34, <0=2037, =0=0

[2026-06-24 08:33:11] Start 3/385: celltype=B, leave_out=Pool137_12
[2026-06-24 08:33:16] Running neighbors: n_cells=48943
[2026-06-24 08:33:21] Building sample metadata
[2026-06-24 08:33:21] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:33:33] DONE 3/385: celltype=B, leave_out=Pool137_12, global_p=0.000999, elapsed=0.37 min
    total=48943, sanity=48943, nan=46194, >0=89, <0=2660, =0=0

[2026-06-24 08:33:33] Start 4/385: celltype=B, leave_out=Pool137_14
[2026-06-24 08:33:38] Running neighbors: n_cells=48053
[2026-06-24 08:33:44] Building sample metadata
[2026-06-24 08:33:44] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:33:55] DONE 4/385: celltype=B, leave_out=Pool137_14, global_p=0.000999, elapsed=0.36 min
    total=48053, sanity=48053, nan=45056, >0=72, <0=2925, =0=0

[2026-06-24 08:33:55] Start 5/385: celltype=B, leave_out=Pool137_15
[2026-06-24 08:34:00] Running neighbors: n_cells=48488
[2026-06-24 08:34:05] Building sample metadata
[2026-06-24 08:34:05] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:34:16] DONE 5/385: celltype=B, leave_out=Pool137_15, global_p=0.000999, elapsed=0.35 min
    total=48488, sanity=48488, nan=46428, >0=24, <0=2036, =0=0

[2026-06-24 08:34:16] Start 6/385: celltype=B, leave_out=Pool137_16
[2026-06-24 08:34:21] Running neighbors: n_cells=48262
[2026-06-24 08:34:26] Building sample metadata
[2026-06-24 08:34:26] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:34:37] DONE 6/385: celltype=B, leave_out=Pool137_16, global_p=0.000999, elapsed=0.34 min
    total=48262, sanity=48262, nan=46743, >0=14, <0=1505, =0=0

[2026-06-24 08:34:37] Start 7/385: celltype=B, leave_out=Pool137_17
[2026-06-24 08:34:42] Running neighbors: n_cells=47087
[2026-06-24 08:34:46] Building sample metadata
[2026-06-24 08:34:46] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:34:56] DONE 7/385: celltype=B, leave_out=Pool137_17, global_p=0.000999, elapsed=0.32 min
    total=47087, sanity=47087, nan=44700, >0=58, <0=2329, =0=0

[2026-06-24 08:34:56] Start 8/385: celltype=B, leave_out=Pool137_18
[2026-06-24 08:35:01] Running neighbors: n_cells=48766
[2026-06-24 08:35:06] Building sample metadata
[2026-06-24 08:35:06] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:35:16] DONE 8/385: celltype=B, leave_out=Pool137_18, global_p=0.000999, elapsed=0.33 min
    total=48766, sanity=48766, nan=46259, >0=100, <0=2407, =0=0

[2026-06-24 08:35:16] Start 9/385: celltype=B, leave_out=Pool137_19
[2026-06-24 08:35:20] Running neighbors: n_cells=48304
[2026-06-24 08:35:24] Building sample metadata
[2026-06-24 08:35:24] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:35:34] DONE 9/385: celltype=B, leave_out=Pool137_19, global_p=0.000999, elapsed=0.30 min
    total=48304, sanity=48304, nan=45844, >0=57, <0=2403, =0=0

[2026-06-24 08:35:35] Start 10/385: celltype=B, leave_out=Pool137_20
[2026-06-24 08:35:39] Running neighbors: n_cells=48765
[2026-06-24 08:35:44] Building sample metadata
[2026-06-24 08:35:44] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:35:55] DONE 10/385: celltype=B, leave_out=Pool137_20, global_p=0.003, elapsed=0.33 min
    total=48765, sanity=48765, nan=47668, >0=33, <0=1064, =0=0

[2026-06-24 08:35:55] Start 11/385: celltype=B, leave_out=Pool137_21
[2026-06-24 08:35:58] Running neighbors: n_cells=48369
[2026-06-24 08:36:03] Building sample metadata
[2026-06-24 08:36:03] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:36:13] DONE 11/385: celltype=B, leave_out=Pool137_21, global_p=0.003, elapsed=0.30 min
    total=48369, sanity=48369, nan=47057, >0=1, <0=1311, =0=0

[2026-06-24 08:36:13] Start 12/385: celltype=B, leave_out=Pool137_22
[2026-06-24 08:36:17] Running neighbors: n_cells=48526
[2026-06-24 08:36:22] Building sample metadata
[2026-06-24 08:36:22] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:36:32] DONE 12/385: celltype=B, leave_out=Pool137_22, global_p=0.000999, elapsed=0.31 min
    total=48526, sanity=48526, nan=46962, >0=13, <0=1551, =0=0

[2026-06-24 08:36:32] Start 13/385: celltype=B, leave_out=Pool137_23
[2026-06-24 08:36:35] Running neighbors: n_cells=48209
[2026-06-24 08:36:40] Building sample metadata
[2026-06-24 08:36:40] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:36:50] DONE 13/385: celltype=B, leave_out=Pool137_23, global_p=0.000999, elapsed=0.30 min
    total=48209, sanity=48209, nan=46020, >0=47, <0=2142, =0=0

[2026-06-24 08:36:50] Start 14/385: celltype=B, leave_out=Pool137_24
[2026-06-24 08:36:53] Running neighbors: n_cells=48396
[2026-06-24 08:36:58] Building sample metadata
[2026-06-24 08:36:58] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:37:08] DONE 14/385: celltype=B, leave_out=Pool137_24, global_p=0.000999, elapsed=0.30 min
    total=48396, sanity=48396, nan=45700, >0=106, <0=2590, =0=0

[2026-06-24 08:37:09] Start 15/385: celltype=B, leave_out=Pool137_25
[2026-06-24 08:37:11] Running neighbors: n_cells=48197
[2026-06-24 08:37:16] Building sample metadata
[2026-06-24 08:37:16] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:37:26] DONE 15/385: celltype=B, leave_out=Pool137_25, global_p=0.000999, elapsed=0.29 min
    total=48197, sanity=48197, nan=45851, >0=27, <0=2319, =0=0

[2026-06-24 08:37:26] Start 16/385: celltype=B, leave_out=Pool137_26
[2026-06-24 08:37:32] Running neighbors: n_cells=48281
[2026-06-24 08:37:37] Building sample metadata
[2026-06-24 08:37:37] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:37:47] DONE 16/385: celltype=B, leave_out=Pool137_26, global_p=0.000999, elapsed=0.35 min
    total=48281, sanity=48281, nan=45625, >0=51, <0=2605, =0=0

[2026-06-24 08:37:47] Start 17/385: celltype=B, leave_out=Pool137_27
[2026-06-24 08:37:52] Running neighbors: n_cells=48622
[2026-06-24 08:37:56] Building sample metadata
[2026-06-24 08:37:56] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:38:06] DONE 17/385: celltype=B, leave_out=Pool137_27, global_p=0.000999, elapsed=0.32 min
    total=48622, sanity=48622, nan=47468, >0=1, <0=1153, =0=0

[2026-06-24 08:38:07] Start 18/385: celltype=B, leave_out=Pool137_28
[2026-06-24 08:38:10] Running neighbors: n_cells=48283
[2026-06-24 08:38:15] Building sample metadata
[2026-06-24 08:38:15] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:38:27] DONE 18/385: celltype=B, leave_out=Pool137_28, global_p=0.002, elapsed=0.34 min
    total=48283, sanity=48283, nan=46415, >0=34, <0=1834, =0=0

[2026-06-24 08:38:27] Start 19/385: celltype=B, leave_out=Pool137_29
[2026-06-24 08:38:33] Running neighbors: n_cells=48342
[2026-06-24 08:38:37] Building sample metadata
[2026-06-24 08:38:37] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:38:50] DONE 19/385: celltype=B, leave_out=Pool137_29, global_p=0.000999, elapsed=0.37 min
    total=48342, sanity=48342, nan=46550, >0=10, <0=1782, =0=0

[2026-06-24 08:38:50] Start 20/385: celltype=B, leave_out=Pool137_30
[2026-06-24 08:38:53] Running neighbors: n_cells=48305
[2026-06-24 08:38:57] Building sample metadata
[2026-06-24 08:38:57] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:39:09] DONE 20/385: celltype=B, leave_out=Pool137_30, global_p=0.000999, elapsed=0.32 min
    total=48305, sanity=48305, nan=46706, >0=9, <0=1590, =0=0

[2026-06-24 08:39:09] Start 21/385: celltype=B, leave_out=Pool137_31
[2026-06-24 08:39:12] Running neighbors: n_cells=47558
[2026-06-24 08:39:17] Building sample metadata
[2026-06-24 08:39:17] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:39:28] DONE 21/385: celltype=B, leave_out=Pool137_31, global_p=0.000999, elapsed=0.32 min
    total=47558, sanity=47558, nan=45507, >0=20, <0=2031, =0=0

[2026-06-24 08:39:28] Start 22/385: celltype=B, leave_out=Pool137_33
[2026-06-24 08:39:31] Running neighbors: n_cells=48129
[2026-06-24 08:39:36] Building sample metadata
[2026-06-24 08:39:36] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:39:45] DONE 22/385: celltype=B, leave_out=Pool137_33, global_p=0.000999, elapsed=0.29 min
    total=48129, sanity=48129, nan=46814, >0=2, <0=1313, =0=0

[2026-06-24 08:39:46] Start 23/385: celltype=B, leave_out=Pool137_34
[2026-06-24 08:39:49] Running neighbors: n_cells=47937
[2026-06-24 08:39:53] Building sample metadata
[2026-06-24 08:39:53] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:40:03] DONE 23/385: celltype=B, leave_out=Pool137_34, global_p=0.000999, elapsed=0.29 min
    total=47937, sanity=47937, nan=45853, >0=88, <0=1996, =0=0

[2026-06-24 08:40:04] Start 24/385: celltype=B, leave_out=Pool137_35
[2026-06-24 08:40:06] Running neighbors: n_cells=47411
[2026-06-24 08:40:11] Building sample metadata
[2026-06-24 08:40:11] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:40:21] DONE 24/385: celltype=B, leave_out=Pool137_35, global_p=0.000999, elapsed=0.29 min
    total=47411, sanity=47411, nan=44548, >0=142, <0=2721, =0=0

[2026-06-24 08:40:21] Start 25/385: celltype=B, leave_out=Pool137_36
[2026-06-24 08:40:25] Running neighbors: n_cells=48470
[2026-06-24 08:40:30] Building sample metadata
[2026-06-24 08:40:30] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:40:40] DONE 25/385: celltype=B, leave_out=Pool137_36, global_p=0.000999, elapsed=0.32 min
    total=48470, sanity=48470, nan=48470, >0=0, <0=0, =0=0

[2026-06-24 08:40:41] Start 26/385: celltype=B, leave_out=Pool137_6
[2026-06-24 08:40:43] Running neighbors: n_cells=48506
[2026-06-24 08:40:48] Building sample metadata
[2026-06-24 08:40:48] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:40:58] DONE 26/385: celltype=B, leave_out=Pool137_6, global_p=0.000999, elapsed=0.30 min
    total=48506, sanity=48506, nan=46786, >0=5, <0=1715, =0=0

[2026-06-24 08:40:59] Start 27/385: celltype=B, leave_out=Pool137_7
[2026-06-24 08:41:01] Running neighbors: n_cells=47903
[2026-06-24 08:41:06] Building sample metadata
[2026-06-24 08:41:06] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:41:16] DONE 27/385: celltype=B, leave_out=Pool137_7, global_p=0.005, elapsed=0.29 min
    total=47903, sanity=47903, nan=47028, >0=1, <0=874, =0=0

[2026-06-24 08:41:16] Start 28/385: celltype=B, leave_out=Pool137_8
[2026-06-24 08:41:19] Running neighbors: n_cells=47328
[2026-06-24 08:41:23] Building sample metadata
[2026-06-24 08:41:23] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:41:33] DONE 28/385: celltype=B, leave_out=Pool137_8, global_p=0.002, elapsed=0.29 min
    total=47328, sanity=47328, nan=45151, >0=32, <0=2145, =0=0

[2026-06-24 08:41:33] Start 29/385: celltype=B, leave_out=Pool137_9
[2026-06-24 08:41:36] Running neighbors: n_cells=48381
[2026-06-24 08:41:41] Building sample metadata
[2026-06-24 08:41:41] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:41:51] DONE 29/385: celltype=B, leave_out=Pool137_9, global_p=0.000999, elapsed=0.30 min
    total=48381, sanity=48381, nan=45721, >0=78, <0=2582, =0=0

[2026-06-24 08:41:51] Start 30/385: celltype=B, leave_out=Pool138_10
[2026-06-24 08:41:54] Running neighbors: n_cells=47928
[2026-06-24 08:41:59] Building sample metadata
[2026-06-24 08:41:59] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:42:09] DONE 30/385: celltype=B, leave_out=Pool138_10, global_p=0.000999, elapsed=0.29 min
    total=47928, sanity=47928, nan=44476, >0=312, <0=3140, =0=0

[2026-06-24 08:42:09] Start 31/385: celltype=B, leave_out=Pool138_11
[2026-06-24 08:42:12] Running neighbors: n_cells=48113
[2026-06-24 08:42:17] Building sample metadata
[2026-06-24 08:42:17] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:42:27] DONE 31/385: celltype=B, leave_out=Pool138_11, global_p=0.002, elapsed=0.29 min
    total=48113, sanity=48113, nan=46251, >0=39, <0=1823, =0=0

[2026-06-24 08:42:27] Start 32/385: celltype=B, leave_out=Pool138_12
[2026-06-24 08:42:30] Running neighbors: n_cells=48586
[2026-06-24 08:42:34] Building sample metadata
[2026-06-24 08:42:34] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:42:44] DONE 32/385: celltype=B, leave_out=Pool138_12, global_p=0.000999, elapsed=0.29 min
    total=48586, sanity=48586, nan=46533, >0=22, <0=2031, =0=0

[2026-06-24 08:42:45] Start 33/385: celltype=B, leave_out=Pool138_13
[2026-06-24 08:42:47] Running neighbors: n_cells=47767
[2026-06-24 08:42:52] Building sample metadata
[2026-06-24 08:42:52] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:43:02] DONE 33/385: celltype=B, leave_out=Pool138_13, global_p=0.000999, elapsed=0.29 min
    total=47767, sanity=47767, nan=45508, >0=47, <0=2212, =0=0

[2026-06-24 08:43:02] Start 34/385: celltype=B, leave_out=Pool138_14
[2026-06-24 08:43:05] Running neighbors: n_cells=47915
[2026-06-24 08:43:10] Building sample metadata
[2026-06-24 08:43:10] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:43:21] DONE 34/385: celltype=B, leave_out=Pool138_14, global_p=0.000999, elapsed=0.32 min
    total=47915, sanity=47915, nan=44398, >0=366, <0=3151, =0=0

[2026-06-24 08:43:22] Start 35/385: celltype=B, leave_out=Pool138_15
[2026-06-24 08:43:24] Running neighbors: n_cells=48327
[2026-06-24 08:43:29] Building sample metadata
[2026-06-24 08:43:29] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:43:39] DONE 35/385: celltype=B, leave_out=Pool138_15, global_p=0.002, elapsed=0.30 min
    total=48327, sanity=48327, nan=45589, >0=77, <0=2661, =0=0

[2026-06-24 08:43:40] Start 36/385: celltype=B, leave_out=Pool138_16
[2026-06-24 08:43:44] Running neighbors: n_cells=48340
[2026-06-24 08:43:48] Building sample metadata
[2026-06-24 08:43:48] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:43:59] DONE 36/385: celltype=B, leave_out=Pool138_16, global_p=0.000999, elapsed=0.32 min
    total=48340, sanity=48340, nan=46100, >0=47, <0=2193, =0=0

[2026-06-24 08:43:59] Start 37/385: celltype=B, leave_out=Pool138_17
[2026-06-24 08:44:02] Running neighbors: n_cells=48823
[2026-06-24 08:44:06] Building sample metadata
[2026-06-24 08:44:07] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:44:17] DONE 37/385: celltype=B, leave_out=Pool138_17, global_p=0.000999, elapsed=0.29 min
    total=48823, sanity=48823, nan=45724, >0=156, <0=2943, =0=0

[2026-06-24 08:44:17] Start 38/385: celltype=B, leave_out=Pool138_18
[2026-06-24 08:44:20] Running neighbors: n_cells=48666
[2026-06-24 08:44:24] Building sample metadata
[2026-06-24 08:44:24] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:44:36] DONE 38/385: celltype=B, leave_out=Pool138_18, global_p=0.000999, elapsed=0.32 min
    total=48666, sanity=48666, nan=46522, >0=113, <0=2031, =0=0

[2026-06-24 08:44:37] Start 39/385: celltype=B, leave_out=Pool138_19
[2026-06-24 08:44:41] Running neighbors: n_cells=48314
[2026-06-24 08:44:46] Building sample metadata
[2026-06-24 08:44:46] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:44:56] DONE 39/385: celltype=B, leave_out=Pool138_19, global_p=0.002, elapsed=0.33 min
    total=48314, sanity=48314, nan=46568, >0=52, <0=1694, =0=0

[2026-06-24 08:44:56] Start 40/385: celltype=B, leave_out=Pool138_20
[2026-06-24 08:44:59] Running neighbors: n_cells=48876
[2026-06-24 08:45:04] Building sample metadata
[2026-06-24 08:45:04] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:45:14] DONE 40/385: celltype=B, leave_out=Pool138_20, global_p=0.000999, elapsed=0.29 min
    total=48876, sanity=48876, nan=46540, >0=84, <0=2252, =0=0

[2026-06-24 08:45:14] Start 41/385: celltype=B, leave_out=Pool138_21
[2026-06-24 08:45:17] Running neighbors: n_cells=48486
[2026-06-24 08:45:22] Building sample metadata
[2026-06-24 08:45:22] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:45:32] DONE 41/385: celltype=B, leave_out=Pool138_21, global_p=0.002, elapsed=0.29 min
    total=48486, sanity=48486, nan=45901, >0=40, <0=2545, =0=0

[2026-06-24 08:45:32] Start 42/385: celltype=B, leave_out=Pool138_22
[2026-06-24 08:45:35] Running neighbors: n_cells=48376
[2026-06-24 08:45:40] Building sample metadata
[2026-06-24 08:45:40] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:45:50] DONE 42/385: celltype=B, leave_out=Pool138_22, global_p=0.002, elapsed=0.30 min
    total=48376, sanity=48376, nan=47020, >0=23, <0=1333, =0=0

[2026-06-24 08:45:50] Start 43/385: celltype=B, leave_out=Pool138_23
[2026-06-24 08:45:53] Running neighbors: n_cells=48881
[2026-06-24 08:45:58] Building sample metadata
[2026-06-24 08:45:58] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:46:08] DONE 43/385: celltype=B, leave_out=Pool138_23, global_p=0.000999, elapsed=0.30 min
    total=48881, sanity=48881, nan=47005, >0=43, <0=1833, =0=0

[2026-06-24 08:46:08] Start 44/385: celltype=B, leave_out=Pool138_24
[2026-06-24 08:46:11] Running neighbors: n_cells=48182
[2026-06-24 08:46:16] Building sample metadata
[2026-06-24 08:46:16] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:46:26] DONE 44/385: celltype=B, leave_out=Pool138_24, global_p=0.000999, elapsed=0.29 min
    total=48182, sanity=48182, nan=46533, >0=11, <0=1638, =0=0

[2026-06-24 08:46:26] Start 45/385: celltype=B, leave_out=Pool138_25
[2026-06-24 08:46:29] Running neighbors: n_cells=48556
[2026-06-24 08:46:33] Building sample metadata
[2026-06-24 08:46:33] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:46:44] DONE 45/385: celltype=B, leave_out=Pool138_25, global_p=0.000999, elapsed=0.30 min
    total=48556, sanity=48556, nan=47269, >0=15, <0=1272, =0=0

[2026-06-24 08:46:44] Start 46/385: celltype=B, leave_out=Pool138_26
[2026-06-24 08:46:46] Running neighbors: n_cells=48738
[2026-06-24 08:46:51] Building sample metadata
[2026-06-24 08:46:51] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:47:01] DONE 46/385: celltype=B, leave_out=Pool138_26, global_p=0.000999, elapsed=0.29 min
    total=48738, sanity=48738, nan=46430, >0=62, <0=2246, =0=0

[2026-06-24 08:47:02] Start 47/385: celltype=B, leave_out=Pool138_27
[2026-06-24 08:47:04] Running neighbors: n_cells=48038
[2026-06-24 08:47:09] Building sample metadata
[2026-06-24 08:47:09] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:47:19] DONE 47/385: celltype=B, leave_out=Pool138_27, global_p=0.000999, elapsed=0.29 min
    total=48038, sanity=48038, nan=46864, >0=3, <0=1171, =0=0

[2026-06-24 08:47:19] Start 48/385: celltype=B, leave_out=Pool138_29
[2026-06-24 08:47:22] Running neighbors: n_cells=47461
[2026-06-24 08:47:26] Building sample metadata
[2026-06-24 08:47:27] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:47:36] DONE 48/385: celltype=B, leave_out=Pool138_29, global_p=0.002, elapsed=0.29 min
    total=47461, sanity=47461, nan=46693, >0=0, <0=768, =0=0

[2026-06-24 08:47:37] Start 49/385: celltype=B, leave_out=Pool138_3
[2026-06-24 08:47:39] Running neighbors: n_cells=47875
[2026-06-24 08:47:44] Building sample metadata
[2026-06-24 08:47:44] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:47:55] DONE 49/385: celltype=B, leave_out=Pool138_3, global_p=0.000999, elapsed=0.30 min
    total=47875, sanity=47875, nan=46687, >0=2, <0=1186, =0=0

[2026-06-24 08:47:55] Start 50/385: celltype=B, leave_out=Pool138_4
[2026-06-24 08:47:58] Running neighbors: n_cells=47839
[2026-06-24 08:48:03] Building sample metadata
[2026-06-24 08:48:03] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:48:13] DONE 50/385: celltype=B, leave_out=Pool138_4, global_p=0.000999, elapsed=0.29 min
    total=47839, sanity=47839, nan=45745, >0=6, <0=2088, =0=0

[2026-06-24 08:48:13] Start 51/385: celltype=B, leave_out=Pool138_5
[2026-06-24 08:48:16] Running neighbors: n_cells=48536
[2026-06-24 08:48:20] Building sample metadata
[2026-06-24 08:48:20] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:48:31] DONE 51/385: celltype=B, leave_out=Pool138_5, global_p=0.000999, elapsed=0.29 min
    total=48536, sanity=48536, nan=46663, >0=14, <0=1859, =0=0

[2026-06-24 08:48:31] Start 52/385: celltype=B, leave_out=Pool138_6
[2026-06-24 08:48:34] Running neighbors: n_cells=48346
[2026-06-24 08:48:38] Building sample metadata
[2026-06-24 08:48:38] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:48:49] DONE 52/385: celltype=B, leave_out=Pool138_6, global_p=0.002, elapsed=0.30 min
    total=48346, sanity=48346, nan=46504, >0=18, <0=1824, =0=0

[2026-06-24 08:48:49] Start 53/385: celltype=B, leave_out=Pool138_7
[2026-06-24 08:48:52] Running neighbors: n_cells=48652
[2026-06-24 08:48:57] Building sample metadata
[2026-06-24 08:48:57] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:49:07] DONE 53/385: celltype=B, leave_out=Pool138_7, global_p=0.000999, elapsed=0.30 min
    total=48652, sanity=48652, nan=45825, >0=28, <0=2799, =0=0

[2026-06-24 08:49:08] Start 54/385: celltype=B, leave_out=Pool138_8
[2026-06-24 08:49:10] Running neighbors: n_cells=47356
[2026-06-24 08:49:15] Building sample metadata
[2026-06-24 08:49:15] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:49:26] DONE 54/385: celltype=B, leave_out=Pool138_8, global_p=0.003, elapsed=0.30 min
    total=47356, sanity=47356, nan=47356, >0=0, <0=0, =0=0

[2026-06-24 08:49:26] Start 55/385: celltype=B, leave_out=Pool138_9
[2026-06-24 08:49:29] Running neighbors: n_cells=48069
[2026-06-24 08:49:33] Building sample metadata
[2026-06-24 08:49:33] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 08:49:43] DONE 55/385: celltype=B, leave_out=Pool138_9, global_p=0.000999, elapsed=0.29 min
    total=48069, sanity=48069, nan=46990, >0=0, <0=1079, =0=0

[2026-06-24 08:49:44] Start 56/385: celltype=CD4 T, leave_out=Pool137_10
[2026-06-24 08:49:49] Running neighbors: n_cells=163955
[2026-06-24 08:50:09] Building sample metadata
[2026-06-24 08:50:09] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:50:39] DONE 56/385: celltype=CD4 T, leave_out=Pool137_10, global_p=0.00999, elapsed=0.93 min
    total=163955, sanity=163955, nan=162058, >0=382, <0=1515, =0=0

[2026-06-24 08:50:40] Start 57/385: celltype=CD4 T, leave_out=Pool137_11
[2026-06-24 08:50:45] Running neighbors: n_cells=163264
[2026-06-24 08:51:05] Building sample metadata
[2026-06-24 08:51:05] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:51:36] DONE 57/385: celltype=CD4 T, leave_out=Pool137_11, global_p=0.022, elapsed=0.94 min
    total=163264, sanity=163264, nan=161109, >0=574, <0=1581, =0=0

[2026-06-24 08:51:36] Start 58/385: celltype=CD4 T, leave_out=Pool137_12
[2026-06-24 08:51:42] Running neighbors: n_cells=166393
[2026-06-24 08:52:02] Building sample metadata
[2026-06-24 08:52:02] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:52:33] DONE 58/385: celltype=CD4 T, leave_out=Pool137_12, global_p=0.00699, elapsed=0.95 min
    total=166393, sanity=166393, nan=165084, >0=257, <0=1052, =0=0

[2026-06-24 08:52:33] Start 59/385: celltype=CD4 T, leave_out=Pool137_14
[2026-06-24 08:52:39] Running neighbors: n_cells=163016
[2026-06-24 08:52:58] Building sample metadata
[2026-06-24 08:52:58] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:53:29] DONE 59/385: celltype=CD4 T, leave_out=Pool137_14, global_p=0.00999, elapsed=0.93 min
    total=163016, sanity=163016, nan=160547, >0=317, <0=2152, =0=0

[2026-06-24 08:53:29] Start 60/385: celltype=CD4 T, leave_out=Pool137_15
[2026-06-24 08:53:35] Running neighbors: n_cells=165388
[2026-06-24 08:53:55] Building sample metadata
[2026-06-24 08:53:55] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:54:26] DONE 60/385: celltype=CD4 T, leave_out=Pool137_15, global_p=0.00599, elapsed=0.94 min
    total=165388, sanity=165388, nan=162516, >0=782, <0=2090, =0=0

[2026-06-24 08:54:26] Start 61/385: celltype=CD4 T, leave_out=Pool137_16
[2026-06-24 08:54:33] Running neighbors: n_cells=164459
[2026-06-24 08:54:53] Building sample metadata
[2026-06-24 08:54:53] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:55:27] DONE 61/385: celltype=CD4 T, leave_out=Pool137_16, global_p=0.017, elapsed=1.01 min
    total=164459, sanity=164459, nan=164459, >0=0, <0=0, =0=0

[2026-06-24 08:55:27] Start 62/385: celltype=CD4 T, leave_out=Pool137_17
[2026-06-24 08:55:35] Running neighbors: n_cells=163549
[2026-06-24 08:55:56] Building sample metadata
[2026-06-24 08:55:56] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:56:26] DONE 62/385: celltype=CD4 T, leave_out=Pool137_17, global_p=0.011, elapsed=0.99 min
    total=163549, sanity=163549, nan=163548, >0=0, <0=1, =0=0

[2026-06-24 08:56:27] Start 63/385: celltype=CD4 T, leave_out=Pool137_18
[2026-06-24 08:56:35] Running neighbors: n_cells=164329
[2026-06-24 08:56:55] Building sample metadata
[2026-06-24 08:56:55] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:57:25] DONE 63/385: celltype=CD4 T, leave_out=Pool137_18, global_p=0.011, elapsed=0.98 min
    total=164329, sanity=164329, nan=164329, >0=0, <0=0, =0=0

[2026-06-24 08:57:26] Start 64/385: celltype=CD4 T, leave_out=Pool137_19
[2026-06-24 08:57:33] Running neighbors: n_cells=164169
[2026-06-24 08:57:53] Building sample metadata
[2026-06-24 08:57:53] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:58:24] DONE 64/385: celltype=CD4 T, leave_out=Pool137_19, global_p=0.002, elapsed=0.98 min
    total=164169, sanity=164169, nan=160660, >0=863, <0=2646, =0=0

[2026-06-24 08:58:25] Start 65/385: celltype=CD4 T, leave_out=Pool137_20
[2026-06-24 08:58:31] Running neighbors: n_cells=166394
[2026-06-24 08:58:51] Building sample metadata
[2026-06-24 08:58:51] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 08:59:22] DONE 65/385: celltype=CD4 T, leave_out=Pool137_20, global_p=0.021, elapsed=0.95 min
    total=166394, sanity=166394, nan=166394, >0=0, <0=0, =0=0

[2026-06-24 08:59:22] Start 66/385: celltype=CD4 T, leave_out=Pool137_21
[2026-06-24 08:59:28] Running neighbors: n_cells=161402
[2026-06-24 08:59:47] Building sample metadata
[2026-06-24 08:59:47] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:00:18] DONE 66/385: celltype=CD4 T, leave_out=Pool137_21, global_p=0.021, elapsed=0.93 min
    total=161402, sanity=161402, nan=161402, >0=0, <0=0, =0=0

[2026-06-24 09:00:18] Start 67/385: celltype=CD4 T, leave_out=Pool137_22
[2026-06-24 09:00:24] Running neighbors: n_cells=163014
[2026-06-24 09:00:44] Building sample metadata
[2026-06-24 09:00:44] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:01:14] DONE 67/385: celltype=CD4 T, leave_out=Pool137_22, global_p=0.02, elapsed=0.94 min
    total=163014, sanity=163014, nan=163014, >0=0, <0=0, =0=0

[2026-06-24 09:01:14] Start 68/385: celltype=CD4 T, leave_out=Pool137_23
[2026-06-24 09:01:20] Running neighbors: n_cells=165565
[2026-06-24 09:01:40] Building sample metadata
[2026-06-24 09:01:40] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:02:11] DONE 68/385: celltype=CD4 T, leave_out=Pool137_23, global_p=0.00699, elapsed=0.94 min
    total=165565, sanity=165565, nan=162404, >0=709, <0=2452, =0=0

[2026-06-24 09:02:11] Start 69/385: celltype=CD4 T, leave_out=Pool137_24
[2026-06-24 09:02:17] Running neighbors: n_cells=164278
[2026-06-24 09:02:37] Building sample metadata
[2026-06-24 09:02:37] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:03:08] DONE 69/385: celltype=CD4 T, leave_out=Pool137_24, global_p=0.00699, elapsed=0.94 min
    total=164278, sanity=164278, nan=164278, >0=0, <0=0, =0=0

[2026-06-24 09:03:08] Start 70/385: celltype=CD4 T, leave_out=Pool137_25
[2026-06-24 09:03:13] Running neighbors: n_cells=164897
[2026-06-24 09:03:33] Building sample metadata
[2026-06-24 09:03:33] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:04:04] DONE 70/385: celltype=CD4 T, leave_out=Pool137_25, global_p=0.003, elapsed=0.93 min
    total=164897, sanity=164897, nan=163175, >0=330, <0=1392, =0=0

[2026-06-24 09:04:04] Start 71/385: celltype=CD4 T, leave_out=Pool137_26
[2026-06-24 09:04:10] Running neighbors: n_cells=163713
[2026-06-24 09:04:30] Building sample metadata
[2026-06-24 09:04:30] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:05:00] DONE 71/385: celltype=CD4 T, leave_out=Pool137_26, global_p=0.005, elapsed=0.93 min
    total=163713, sanity=163713, nan=161011, >0=445, <0=2257, =0=0

[2026-06-24 09:05:00] Start 72/385: celltype=CD4 T, leave_out=Pool137_27
[2026-06-24 09:05:06] Running neighbors: n_cells=165212
[2026-06-24 09:05:26] Building sample metadata
[2026-06-24 09:05:26] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:06:02] DONE 72/385: celltype=CD4 T, leave_out=Pool137_27, global_p=0.00999, elapsed=1.02 min
    total=165212, sanity=165212, nan=165212, >0=0, <0=0, =0=0

[2026-06-24 09:06:02] Start 73/385: celltype=CD4 T, leave_out=Pool137_28
[2026-06-24 09:06:08] Running neighbors: n_cells=161532
[2026-06-24 09:06:27] Building sample metadata
[2026-06-24 09:06:27] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:07:02] DONE 73/385: celltype=CD4 T, leave_out=Pool137_28, global_p=0.0519, elapsed=1.01 min
    total=161532, sanity=161532, nan=160262, >0=247, <0=1023, =0=0

[2026-06-24 09:07:03] Start 74/385: celltype=CD4 T, leave_out=Pool137_29
[2026-06-24 09:07:09] Running neighbors: n_cells=165086
[2026-06-24 09:07:29] Building sample metadata
[2026-06-24 09:07:29] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:08:00] DONE 74/385: celltype=CD4 T, leave_out=Pool137_29, global_p=0.018, elapsed=0.96 min
    total=165086, sanity=165086, nan=165086, >0=0, <0=0, =0=0

[2026-06-24 09:08:00] Start 75/385: celltype=CD4 T, leave_out=Pool137_30
[2026-06-24 09:08:06] Running neighbors: n_cells=162859
[2026-06-24 09:08:26] Building sample metadata
[2026-06-24 09:08:26] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:08:58] DONE 75/385: celltype=CD4 T, leave_out=Pool137_30, global_p=0.003, elapsed=0.96 min
    total=162859, sanity=162859, nan=158400, >0=1226, <0=3233, =0=0

[2026-06-24 09:08:58] Start 76/385: celltype=CD4 T, leave_out=Pool137_31
[2026-06-24 09:09:03] Running neighbors: n_cells=164115
[2026-06-24 09:09:23] Building sample metadata
[2026-06-24 09:09:24] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:09:54] DONE 76/385: celltype=CD4 T, leave_out=Pool137_31, global_p=0.012, elapsed=0.94 min
    total=164115, sanity=164115, nan=163613, >0=58, <0=444, =0=0

[2026-06-24 09:09:54] Start 77/385: celltype=CD4 T, leave_out=Pool137_33
[2026-06-24 09:10:00] Running neighbors: n_cells=163930
[2026-06-24 09:10:20] Building sample metadata
[2026-06-24 09:10:20] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:10:50] DONE 77/385: celltype=CD4 T, leave_out=Pool137_33, global_p=0.003, elapsed=0.93 min
    total=163930, sanity=163930, nan=162546, >0=434, <0=950, =0=0

[2026-06-24 09:10:50] Start 78/385: celltype=CD4 T, leave_out=Pool137_34
[2026-06-24 09:10:56] Running neighbors: n_cells=163972
[2026-06-24 09:11:16] Building sample metadata
[2026-06-24 09:11:16] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:11:46] DONE 78/385: celltype=CD4 T, leave_out=Pool137_34, global_p=0.00699, elapsed=0.93 min
    total=163972, sanity=163972, nan=163972, >0=0, <0=0, =0=0

[2026-06-24 09:11:46] Start 79/385: celltype=CD4 T, leave_out=Pool137_35
[2026-06-24 09:11:52] Running neighbors: n_cells=163427
[2026-06-24 09:12:11] Building sample metadata
[2026-06-24 09:12:11] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:12:43] DONE 79/385: celltype=CD4 T, leave_out=Pool137_35, global_p=0.022, elapsed=0.94 min
    total=163427, sanity=163427, nan=163427, >0=0, <0=0, =0=0

[2026-06-24 09:12:43] Start 80/385: celltype=CD4 T, leave_out=Pool137_36
[2026-06-24 09:12:49] Running neighbors: n_cells=162333
[2026-06-24 09:13:09] Building sample metadata
[2026-06-24 09:13:09] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:13:40] DONE 80/385: celltype=CD4 T, leave_out=Pool137_36, global_p=0.003, elapsed=0.95 min
    total=162333, sanity=162333, nan=162333, >0=0, <0=0, =0=0

[2026-06-24 09:13:40] Start 81/385: celltype=CD4 T, leave_out=Pool137_6
[2026-06-24 09:13:46] Running neighbors: n_cells=164971
[2026-06-24 09:14:06] Building sample metadata
[2026-06-24 09:14:06] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:14:37] DONE 81/385: celltype=CD4 T, leave_out=Pool137_6, global_p=0.012, elapsed=0.94 min
    total=164971, sanity=164971, nan=164262, >0=128, <0=581, =0=0

[2026-06-24 09:14:37] Start 82/385: celltype=CD4 T, leave_out=Pool137_7
[2026-06-24 09:14:42] Running neighbors: n_cells=164367
[2026-06-24 09:15:02] Building sample metadata
[2026-06-24 09:15:02] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:15:33] DONE 82/385: celltype=CD4 T, leave_out=Pool137_7, global_p=0.00899, elapsed=0.93 min
    total=164367, sanity=164367, nan=164367, >0=0, <0=0, =0=0

[2026-06-24 09:15:33] Start 83/385: celltype=CD4 T, leave_out=Pool137_8
[2026-06-24 09:15:39] Running neighbors: n_cells=163195
[2026-06-24 09:15:58] Building sample metadata
[2026-06-24 09:15:58] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:16:28] DONE 83/385: celltype=CD4 T, leave_out=Pool137_8, global_p=0.00699, elapsed=0.93 min
    total=163195, sanity=163195, nan=162072, >0=240, <0=883, =0=0

[2026-06-24 09:16:29] Start 84/385: celltype=CD4 T, leave_out=Pool137_9
[2026-06-24 09:16:34] Running neighbors: n_cells=163716
[2026-06-24 09:16:54] Building sample metadata
[2026-06-24 09:16:54] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:17:24] DONE 84/385: celltype=CD4 T, leave_out=Pool137_9, global_p=0.00999, elapsed=0.93 min
    total=163716, sanity=163716, nan=161943, >0=353, <0=1420, =0=0

[2026-06-24 09:17:25] Start 85/385: celltype=CD4 T, leave_out=Pool138_10
[2026-06-24 09:17:30] Running neighbors: n_cells=163428
[2026-06-24 09:17:50] Building sample metadata
[2026-06-24 09:17:50] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:18:20] DONE 85/385: celltype=CD4 T, leave_out=Pool138_10, global_p=0.015, elapsed=0.93 min
    total=163428, sanity=163428, nan=163428, >0=0, <0=0, =0=0

[2026-06-24 09:18:21] Start 86/385: celltype=CD4 T, leave_out=Pool138_11
[2026-06-24 09:18:26] Running neighbors: n_cells=163724
[2026-06-24 09:18:46] Building sample metadata
[2026-06-24 09:18:46] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:19:16] DONE 86/385: celltype=CD4 T, leave_out=Pool138_11, global_p=0.00699, elapsed=0.92 min
    total=163724, sanity=163724, nan=161465, >0=560, <0=1699, =0=0

[2026-06-24 09:19:16] Start 87/385: celltype=CD4 T, leave_out=Pool138_12
[2026-06-24 09:19:21] Running neighbors: n_cells=163968
[2026-06-24 09:19:41] Building sample metadata
[2026-06-24 09:19:41] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:20:11] DONE 87/385: celltype=CD4 T, leave_out=Pool138_12, global_p=0.00699, elapsed=0.92 min
    total=163968, sanity=163968, nan=162634, >0=254, <0=1080, =0=0

[2026-06-24 09:20:11] Start 88/385: celltype=CD4 T, leave_out=Pool138_13
[2026-06-24 09:20:17] Running neighbors: n_cells=162012
[2026-06-24 09:20:36] Building sample metadata
[2026-06-24 09:20:36] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:21:06] DONE 88/385: celltype=CD4 T, leave_out=Pool138_13, global_p=0.003, elapsed=0.91 min
    total=162012, sanity=162012, nan=159095, >0=833, <0=2084, =0=0

[2026-06-24 09:21:07] Start 89/385: celltype=CD4 T, leave_out=Pool138_14
[2026-06-24 09:21:12] Running neighbors: n_cells=163354
[2026-06-24 09:21:32] Building sample metadata
[2026-06-24 09:21:32] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:22:02] DONE 89/385: celltype=CD4 T, leave_out=Pool138_14, global_p=0.00899, elapsed=0.92 min
    total=163354, sanity=163354, nan=160849, >0=469, <0=2036, =0=0

[2026-06-24 09:22:02] Start 90/385: celltype=CD4 T, leave_out=Pool138_15
[2026-06-24 09:22:08] Running neighbors: n_cells=163022
[2026-06-24 09:22:27] Building sample metadata
[2026-06-24 09:22:27] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:23:02] DONE 90/385: celltype=CD4 T, leave_out=Pool138_15, global_p=0.00799, elapsed=0.99 min
    total=163022, sanity=163022, nan=160013, >0=644, <0=2365, =0=0

[2026-06-24 09:23:02] Start 91/385: celltype=CD4 T, leave_out=Pool138_16
[2026-06-24 09:23:08] Running neighbors: n_cells=163129
[2026-06-24 09:23:27] Building sample metadata
[2026-06-24 09:23:27] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:23:58] DONE 91/385: celltype=CD4 T, leave_out=Pool138_16, global_p=0.00899, elapsed=0.93 min
    total=163129, sanity=163129, nan=160799, >0=559, <0=1771, =0=0

[2026-06-24 09:23:58] Start 92/385: celltype=CD4 T, leave_out=Pool138_17
[2026-06-24 09:24:04] Running neighbors: n_cells=164122
[2026-06-24 09:24:24] Building sample metadata
[2026-06-24 09:24:24] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:24:55] DONE 92/385: celltype=CD4 T, leave_out=Pool138_17, global_p=0.00699, elapsed=0.94 min
    total=164122, sanity=164122, nan=161241, >0=696, <0=2185, =0=0

[2026-06-24 09:24:55] Start 93/385: celltype=CD4 T, leave_out=Pool138_18
[2026-06-24 09:25:01] Running neighbors: n_cells=165536
[2026-06-24 09:25:21] Building sample metadata
[2026-06-24 09:25:21] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:25:52] DONE 93/385: celltype=CD4 T, leave_out=Pool138_18, global_p=0.00599, elapsed=0.95 min
    total=165536, sanity=165536, nan=164085, >0=473, <0=978, =0=0

[2026-06-24 09:25:52] Start 94/385: celltype=CD4 T, leave_out=Pool138_19
[2026-06-24 09:25:58] Running neighbors: n_cells=165275
[2026-06-24 09:26:17] Building sample metadata
[2026-06-24 09:26:17] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:26:49] DONE 94/385: celltype=CD4 T, leave_out=Pool138_19, global_p=0.013, elapsed=0.94 min
    total=165275, sanity=165275, nan=164015, >0=433, <0=827, =0=0

[2026-06-24 09:26:49] Start 95/385: celltype=CD4 T, leave_out=Pool138_20
[2026-06-24 09:26:55] Running neighbors: n_cells=164614
[2026-06-24 09:27:15] Building sample metadata
[2026-06-24 09:27:15] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:27:45] DONE 95/385: celltype=CD4 T, leave_out=Pool138_20, global_p=0.005, elapsed=0.94 min
    total=164614, sanity=164614, nan=161640, >0=788, <0=2186, =0=0

[2026-06-24 09:27:45] Start 96/385: celltype=CD4 T, leave_out=Pool138_21
[2026-06-24 09:27:51] Running neighbors: n_cells=164442
[2026-06-24 09:28:11] Building sample metadata
[2026-06-24 09:28:11] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:28:41] DONE 96/385: celltype=CD4 T, leave_out=Pool138_21, global_p=0.019, elapsed=0.93 min
    total=164442, sanity=164442, nan=164442, >0=0, <0=0, =0=0

[2026-06-24 09:28:41] Start 97/385: celltype=CD4 T, leave_out=Pool138_22
[2026-06-24 09:28:47] Running neighbors: n_cells=164667
[2026-06-24 09:29:07] Building sample metadata
[2026-06-24 09:29:07] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:29:37] DONE 97/385: celltype=CD4 T, leave_out=Pool138_22, global_p=0.015, elapsed=0.93 min
    total=164667, sanity=164667, nan=163027, >0=547, <0=1093, =0=0

[2026-06-24 09:29:38] Start 98/385: celltype=CD4 T, leave_out=Pool138_23
[2026-06-24 09:29:43] Running neighbors: n_cells=166189
[2026-06-24 09:30:03] Building sample metadata
[2026-06-24 09:30:03] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:30:34] DONE 98/385: celltype=CD4 T, leave_out=Pool138_23, global_p=0.002, elapsed=0.94 min
    total=166189, sanity=166189, nan=164424, >0=513, <0=1252, =0=0

[2026-06-24 09:30:34] Start 99/385: celltype=CD4 T, leave_out=Pool138_24
[2026-06-24 09:30:40] Running neighbors: n_cells=165001
[2026-06-24 09:31:00] Building sample metadata
[2026-06-24 09:31:00] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:31:30] DONE 99/385: celltype=CD4 T, leave_out=Pool138_24, global_p=0.00799, elapsed=0.93 min
    total=165001, sanity=165001, nan=164242, >0=121, <0=638, =0=0

[2026-06-24 09:31:30] Start 100/385: celltype=CD4 T, leave_out=Pool138_25
[2026-06-24 09:31:36] Running neighbors: n_cells=165248
[2026-06-24 09:31:56] Building sample metadata
[2026-06-24 09:31:56] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:32:26] DONE 100/385: celltype=CD4 T, leave_out=Pool138_25, global_p=0.011, elapsed=0.94 min
    total=165248, sanity=165248, nan=162629, >0=659, <0=1960, =0=0

[2026-06-24 09:32:27] Start 101/385: celltype=CD4 T, leave_out=Pool138_26
[2026-06-24 09:32:32] Running neighbors: n_cells=165316
[2026-06-24 09:32:52] Building sample metadata
[2026-06-24 09:32:52] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:33:23] DONE 101/385: celltype=CD4 T, leave_out=Pool138_26, global_p=0.011, elapsed=0.94 min
    total=165316, sanity=165316, nan=161731, >0=985, <0=2600, =0=0

[2026-06-24 09:33:23] Start 102/385: celltype=CD4 T, leave_out=Pool138_27
[2026-06-24 09:33:29] Running neighbors: n_cells=163778
[2026-06-24 09:33:48] Building sample metadata
[2026-06-24 09:33:48] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:34:19] DONE 102/385: celltype=CD4 T, leave_out=Pool138_27, global_p=0.013, elapsed=0.92 min
    total=163778, sanity=163778, nan=163778, >0=0, <0=0, =0=0

[2026-06-24 09:34:19] Start 103/385: celltype=CD4 T, leave_out=Pool138_29
[2026-06-24 09:34:24] Running neighbors: n_cells=163437
[2026-06-24 09:34:44] Building sample metadata
[2026-06-24 09:34:44] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:35:15] DONE 103/385: celltype=CD4 T, leave_out=Pool138_29, global_p=0.00699, elapsed=0.93 min
    total=163437, sanity=163437, nan=163437, >0=0, <0=0, =0=0

[2026-06-24 09:35:15] Start 104/385: celltype=CD4 T, leave_out=Pool138_3
[2026-06-24 09:35:21] Running neighbors: n_cells=163652
[2026-06-24 09:35:40] Building sample metadata
[2026-06-24 09:35:40] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:36:11] DONE 104/385: celltype=CD4 T, leave_out=Pool138_3, global_p=0.025, elapsed=0.93 min
    total=163652, sanity=163652, nan=163652, >0=0, <0=0, =0=0

[2026-06-24 09:36:11] Start 105/385: celltype=CD4 T, leave_out=Pool138_4
[2026-06-24 09:36:16] Running neighbors: n_cells=161565
[2026-06-24 09:36:36] Building sample metadata
[2026-06-24 09:36:36] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:37:06] DONE 105/385: celltype=CD4 T, leave_out=Pool138_4, global_p=0.034, elapsed=0.92 min
    total=161565, sanity=161565, nan=161565, >0=0, <0=0, =0=0

[2026-06-24 09:37:06] Start 106/385: celltype=CD4 T, leave_out=Pool138_5
[2026-06-24 09:37:12] Running neighbors: n_cells=163923
[2026-06-24 09:37:32] Building sample metadata
[2026-06-24 09:37:32] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:38:02] DONE 106/385: celltype=CD4 T, leave_out=Pool138_5, global_p=0.012, elapsed=0.93 min
    total=163923, sanity=163923, nan=163923, >0=0, <0=0, =0=0

[2026-06-24 09:38:02] Start 107/385: celltype=CD4 T, leave_out=Pool138_6
[2026-06-24 09:38:08] Running neighbors: n_cells=164977
[2026-06-24 09:38:28] Building sample metadata
[2026-06-24 09:38:28] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:38:59] DONE 107/385: celltype=CD4 T, leave_out=Pool138_6, global_p=0.00599, elapsed=0.94 min
    total=164977, sanity=164977, nan=163824, >0=258, <0=895, =0=0

[2026-06-24 09:38:59] Start 108/385: celltype=CD4 T, leave_out=Pool138_7
[2026-06-24 09:39:05] Running neighbors: n_cells=163761
[2026-06-24 09:39:24] Building sample metadata
[2026-06-24 09:39:24] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:39:55] DONE 108/385: celltype=CD4 T, leave_out=Pool138_7, global_p=0.00999, elapsed=0.93 min
    total=163761, sanity=163761, nan=161796, >0=314, <0=1651, =0=0

[2026-06-24 09:39:55] Start 109/385: celltype=CD4 T, leave_out=Pool138_8
[2026-06-24 09:40:01] Running neighbors: n_cells=164041
[2026-06-24 09:40:20] Building sample metadata
[2026-06-24 09:40:20] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:40:51] DONE 109/385: celltype=CD4 T, leave_out=Pool138_8, global_p=0.014, elapsed=0.93 min
    total=164041, sanity=164041, nan=164041, >0=0, <0=0, =0=0

[2026-06-24 09:40:51] Start 110/385: celltype=CD4 T, leave_out=Pool138_9
[2026-06-24 09:40:57] Running neighbors: n_cells=162181
[2026-06-24 09:41:16] Building sample metadata
[2026-06-24 09:41:16] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:41:46] DONE 110/385: celltype=CD4 T, leave_out=Pool138_9, global_p=0.00999, elapsed=0.91 min
    total=162181, sanity=162181, nan=162181, >0=0, <0=0, =0=0

[2026-06-24 09:41:46] Start 111/385: celltype=CD8 T, leave_out=Pool137_10
[2026-06-24 09:41:49] Running neighbors: n_cells=55724
[2026-06-24 09:41:55] Building sample metadata
[2026-06-24 09:41:55] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:42:06] DONE 111/385: celltype=CD8 T, leave_out=Pool137_10, global_p=0.156, elapsed=0.33 min
    total=55724, sanity=55724, nan=55724, >0=0, <0=0, =0=0

[2026-06-24 09:42:06] Start 112/385: celltype=CD8 T, leave_out=Pool137_11
[2026-06-24 09:42:09] Running neighbors: n_cells=54674
[2026-06-24 09:42:15] Building sample metadata
[2026-06-24 09:42:15] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:42:26] DONE 112/385: celltype=CD8 T, leave_out=Pool137_11, global_p=0.105, elapsed=0.33 min
    total=54674, sanity=54674, nan=54674, >0=0, <0=0, =0=0

[2026-06-24 09:42:26] Start 113/385: celltype=CD8 T, leave_out=Pool137_12
[2026-06-24 09:42:29] Running neighbors: n_cells=55659
[2026-06-24 09:42:35] Building sample metadata
[2026-06-24 09:42:35] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:42:46] DONE 113/385: celltype=CD8 T, leave_out=Pool137_12, global_p=0.0759, elapsed=0.34 min
    total=55659, sanity=55659, nan=55659, >0=0, <0=0, =0=0

[2026-06-24 09:42:47] Start 114/385: celltype=CD8 T, leave_out=Pool137_14
[2026-06-24 09:42:50] Running neighbors: n_cells=55329
[2026-06-24 09:42:56] Building sample metadata
[2026-06-24 09:42:56] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:43:08] DONE 114/385: celltype=CD8 T, leave_out=Pool137_14, global_p=0.117, elapsed=0.35 min
    total=55329, sanity=55329, nan=55329, >0=0, <0=0, =0=0

[2026-06-24 09:43:08] Start 115/385: celltype=CD8 T, leave_out=Pool137_15
[2026-06-24 09:43:11] Running neighbors: n_cells=55397
[2026-06-24 09:43:16] Building sample metadata
[2026-06-24 09:43:16] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:43:28] DONE 115/385: celltype=CD8 T, leave_out=Pool137_15, global_p=0.105, elapsed=0.33 min
    total=55397, sanity=55397, nan=55397, >0=0, <0=0, =0=0

[2026-06-24 09:43:28] Start 116/385: celltype=CD8 T, leave_out=Pool137_16
[2026-06-24 09:43:31] Running neighbors: n_cells=55794
[2026-06-24 09:43:37] Building sample metadata
[2026-06-24 09:43:37] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:43:48] DONE 116/385: celltype=CD8 T, leave_out=Pool137_16, global_p=0.174, elapsed=0.33 min
    total=55794, sanity=55794, nan=55794, >0=0, <0=0, =0=0

[2026-06-24 09:43:48] Start 117/385: celltype=CD8 T, leave_out=Pool137_17
[2026-06-24 09:43:51] Running neighbors: n_cells=55498
[2026-06-24 09:43:57] Building sample metadata
[2026-06-24 09:43:57] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:44:08] DONE 117/385: celltype=CD8 T, leave_out=Pool137_17, global_p=0.116, elapsed=0.33 min
    total=55498, sanity=55498, nan=55498, >0=0, <0=0, =0=0

[2026-06-24 09:44:08] Start 118/385: celltype=CD8 T, leave_out=Pool137_18
[2026-06-24 09:44:11] Running neighbors: n_cells=54377
[2026-06-24 09:44:17] Building sample metadata
[2026-06-24 09:44:17] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:44:28] DONE 118/385: celltype=CD8 T, leave_out=Pool137_18, global_p=0.158, elapsed=0.33 min
    total=54377, sanity=54377, nan=54377, >0=0, <0=0, =0=0

[2026-06-24 09:44:28] Start 119/385: celltype=CD8 T, leave_out=Pool137_19
[2026-06-24 09:44:31] Running neighbors: n_cells=54730
[2026-06-24 09:44:37] Building sample metadata
[2026-06-24 09:44:37] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:44:48] DONE 119/385: celltype=CD8 T, leave_out=Pool137_19, global_p=0.125, elapsed=0.33 min
    total=54730, sanity=54730, nan=54730, >0=0, <0=0, =0=0

[2026-06-24 09:44:48] Start 120/385: celltype=CD8 T, leave_out=Pool137_20
[2026-06-24 09:44:51] Running neighbors: n_cells=56179
[2026-06-24 09:44:57] Building sample metadata
[2026-06-24 09:44:57] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:45:08] DONE 120/385: celltype=CD8 T, leave_out=Pool137_20, global_p=0.162, elapsed=0.33 min
    total=56179, sanity=56179, nan=56179, >0=0, <0=0, =0=0

[2026-06-24 09:45:08] Start 121/385: celltype=CD8 T, leave_out=Pool137_21
[2026-06-24 09:45:11] Running neighbors: n_cells=55646
[2026-06-24 09:45:17] Building sample metadata
[2026-06-24 09:45:17] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:45:28] DONE 121/385: celltype=CD8 T, leave_out=Pool137_21, global_p=0.0509, elapsed=0.33 min
    total=55646, sanity=55646, nan=55646, >0=0, <0=0, =0=0

[2026-06-24 09:45:28] Start 122/385: celltype=CD8 T, leave_out=Pool137_22
[2026-06-24 09:45:31] Running neighbors: n_cells=54266
[2026-06-24 09:45:37] Building sample metadata
[2026-06-24 09:45:37] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:45:48] DONE 122/385: celltype=CD8 T, leave_out=Pool137_22, global_p=0.114, elapsed=0.32 min
    total=54266, sanity=54266, nan=54266, >0=0, <0=0, =0=0

[2026-06-24 09:45:48] Start 123/385: celltype=CD8 T, leave_out=Pool137_23
[2026-06-24 09:45:51] Running neighbors: n_cells=56100
[2026-06-24 09:45:56] Building sample metadata
[2026-06-24 09:45:56] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:46:08] DONE 123/385: celltype=CD8 T, leave_out=Pool137_23, global_p=0.0779, elapsed=0.33 min
    total=56100, sanity=56100, nan=56100, >0=0, <0=0, =0=0

[2026-06-24 09:46:08] Start 124/385: celltype=CD8 T, leave_out=Pool137_24
[2026-06-24 09:46:11] Running neighbors: n_cells=55172
[2026-06-24 09:46:16] Building sample metadata
[2026-06-24 09:46:16] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:46:28] DONE 124/385: celltype=CD8 T, leave_out=Pool137_24, global_p=0.115, elapsed=0.33 min
    total=55172, sanity=55172, nan=55172, >0=0, <0=0, =0=0

[2026-06-24 09:46:28] Start 125/385: celltype=CD8 T, leave_out=Pool137_25
[2026-06-24 09:46:31] Running neighbors: n_cells=55987
[2026-06-24 09:46:37] Building sample metadata
[2026-06-24 09:46:37] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:46:48] DONE 125/385: celltype=CD8 T, leave_out=Pool137_25, global_p=0.135, elapsed=0.33 min
    total=55987, sanity=55987, nan=55987, >0=0, <0=0, =0=0

[2026-06-24 09:46:48] Start 126/385: celltype=CD8 T, leave_out=Pool137_26
[2026-06-24 09:46:51] Running neighbors: n_cells=55470
[2026-06-24 09:46:57] Building sample metadata
[2026-06-24 09:46:57] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:47:08] DONE 126/385: celltype=CD8 T, leave_out=Pool137_26, global_p=0.132, elapsed=0.33 min
    total=55470, sanity=55470, nan=55470, >0=0, <0=0, =0=0

[2026-06-24 09:47:08] Start 127/385: celltype=CD8 T, leave_out=Pool137_27
[2026-06-24 09:47:11] Running neighbors: n_cells=55846
[2026-06-24 09:47:17] Building sample metadata
[2026-06-24 09:47:17] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:47:28] DONE 127/385: celltype=CD8 T, leave_out=Pool137_27, global_p=0.147, elapsed=0.33 min
    total=55846, sanity=55846, nan=55846, >0=0, <0=0, =0=0

[2026-06-24 09:47:29] Start 128/385: celltype=CD8 T, leave_out=Pool137_28
[2026-06-24 09:47:31] Running neighbors: n_cells=55904
[2026-06-24 09:47:37] Building sample metadata
[2026-06-24 09:47:37] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:47:48] DONE 128/385: celltype=CD8 T, leave_out=Pool137_28, global_p=0.158, elapsed=0.33 min
    total=55904, sanity=55904, nan=55904, >0=0, <0=0, =0=0

[2026-06-24 09:47:48] Start 129/385: celltype=CD8 T, leave_out=Pool137_29
[2026-06-24 09:47:51] Running neighbors: n_cells=55690
[2026-06-24 09:47:57] Building sample metadata
[2026-06-24 09:47:57] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:48:08] DONE 129/385: celltype=CD8 T, leave_out=Pool137_29, global_p=0.109, elapsed=0.33 min
    total=55690, sanity=55690, nan=55690, >0=0, <0=0, =0=0

[2026-06-24 09:48:08] Start 130/385: celltype=CD8 T, leave_out=Pool137_30
[2026-06-24 09:48:11] Running neighbors: n_cells=54448
[2026-06-24 09:48:16] Building sample metadata
[2026-06-24 09:48:16] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:48:28] DONE 130/385: celltype=CD8 T, leave_out=Pool137_30, global_p=0.0829, elapsed=0.32 min
    total=54448, sanity=54448, nan=54448, >0=0, <0=0, =0=0

[2026-06-24 09:48:28] Start 131/385: celltype=CD8 T, leave_out=Pool137_31
[2026-06-24 09:48:31] Running neighbors: n_cells=55254
[2026-06-24 09:48:36] Building sample metadata
[2026-06-24 09:48:36] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:48:48] DONE 131/385: celltype=CD8 T, leave_out=Pool137_31, global_p=0.181, elapsed=0.33 min
    total=55254, sanity=55254, nan=55254, >0=0, <0=0, =0=0

[2026-06-24 09:48:48] Start 132/385: celltype=CD8 T, leave_out=Pool137_33
[2026-06-24 09:48:52] Running neighbors: n_cells=53152
[2026-06-24 09:48:59] Building sample metadata
[2026-06-24 09:48:59] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:49:11] DONE 132/385: celltype=CD8 T, leave_out=Pool137_33, global_p=0.189, elapsed=0.39 min
    total=53152, sanity=53152, nan=53152, >0=0, <0=0, =0=0

[2026-06-24 09:49:12] Start 133/385: celltype=CD8 T, leave_out=Pool137_34
[2026-06-24 09:49:14] Running neighbors: n_cells=54353
[2026-06-24 09:49:20] Building sample metadata
[2026-06-24 09:49:20] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:49:31] DONE 133/385: celltype=CD8 T, leave_out=Pool137_34, global_p=0.0819, elapsed=0.32 min
    total=54353, sanity=54353, nan=54353, >0=0, <0=0, =0=0

[2026-06-24 09:49:31] Start 134/385: celltype=CD8 T, leave_out=Pool137_35
[2026-06-24 09:49:34] Running neighbors: n_cells=55328
[2026-06-24 09:49:39] Building sample metadata
[2026-06-24 09:49:39] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:49:51] DONE 134/385: celltype=CD8 T, leave_out=Pool137_35, global_p=0.0979, elapsed=0.32 min
    total=55328, sanity=55328, nan=55328, >0=0, <0=0, =0=0

[2026-06-24 09:49:51] Start 135/385: celltype=CD8 T, leave_out=Pool137_36
[2026-06-24 09:49:54] Running neighbors: n_cells=55771
[2026-06-24 09:49:59] Building sample metadata
[2026-06-24 09:49:59] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:50:10] DONE 135/385: celltype=CD8 T, leave_out=Pool137_36, global_p=0.319, elapsed=0.33 min
    total=55771, sanity=55771, nan=55771, >0=0, <0=0, =0=0

[2026-06-24 09:50:11] Start 136/385: celltype=CD8 T, leave_out=Pool137_6
[2026-06-24 09:50:13] Running neighbors: n_cells=55345
[2026-06-24 09:50:19] Building sample metadata
[2026-06-24 09:50:19] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:50:30] DONE 136/385: celltype=CD8 T, leave_out=Pool137_6, global_p=0.151, elapsed=0.32 min
    total=55345, sanity=55345, nan=55345, >0=0, <0=0, =0=0

[2026-06-24 09:50:30] Start 137/385: celltype=CD8 T, leave_out=Pool137_7
[2026-06-24 09:50:33] Running neighbors: n_cells=55057
[2026-06-24 09:50:38] Building sample metadata
[2026-06-24 09:50:38] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:50:50] DONE 137/385: celltype=CD8 T, leave_out=Pool137_7, global_p=0.117, elapsed=0.33 min
    total=55057, sanity=55057, nan=55057, >0=0, <0=0, =0=0

[2026-06-24 09:50:50] Start 138/385: celltype=CD8 T, leave_out=Pool137_8
[2026-06-24 09:50:54] Running neighbors: n_cells=55800
[2026-06-24 09:51:00] Building sample metadata
[2026-06-24 09:51:00] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:51:14] DONE 138/385: celltype=CD8 T, leave_out=Pool137_8, global_p=0.15, elapsed=0.40 min
    total=55800, sanity=55800, nan=55800, >0=0, <0=0, =0=0

[2026-06-24 09:51:14] Start 139/385: celltype=CD8 T, leave_out=Pool137_9
[2026-06-24 09:51:17] Running neighbors: n_cells=55913
[2026-06-24 09:51:23] Building sample metadata
[2026-06-24 09:51:23] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:51:35] DONE 139/385: celltype=CD8 T, leave_out=Pool137_9, global_p=0.108, elapsed=0.35 min
    total=55913, sanity=55913, nan=55913, >0=0, <0=0, =0=0

[2026-06-24 09:51:35] Start 140/385: celltype=CD8 T, leave_out=Pool138_10
[2026-06-24 09:51:38] Running neighbors: n_cells=54201
[2026-06-24 09:51:44] Building sample metadata
[2026-06-24 09:51:44] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:51:55] DONE 140/385: celltype=CD8 T, leave_out=Pool138_10, global_p=0.167, elapsed=0.34 min
    total=54201, sanity=54201, nan=54201, >0=0, <0=0, =0=0

[2026-06-24 09:51:56] Start 141/385: celltype=CD8 T, leave_out=Pool138_11
[2026-06-24 09:51:59] Running neighbors: n_cells=55833
[2026-06-24 09:52:04] Building sample metadata
[2026-06-24 09:52:04] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:52:15] DONE 141/385: celltype=CD8 T, leave_out=Pool138_11, global_p=0.173, elapsed=0.33 min
    total=55833, sanity=55833, nan=55833, >0=0, <0=0, =0=0

[2026-06-24 09:52:15] Start 142/385: celltype=CD8 T, leave_out=Pool138_12
[2026-06-24 09:52:18] Running neighbors: n_cells=55605
[2026-06-24 09:52:24] Building sample metadata
[2026-06-24 09:52:24] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:52:35] DONE 142/385: celltype=CD8 T, leave_out=Pool138_12, global_p=0.0869, elapsed=0.33 min
    total=55605, sanity=55605, nan=55605, >0=0, <0=0, =0=0

[2026-06-24 09:52:35] Start 143/385: celltype=CD8 T, leave_out=Pool138_13
[2026-06-24 09:52:38] Running neighbors: n_cells=55404
[2026-06-24 09:52:44] Building sample metadata
[2026-06-24 09:52:44] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:53:00] DONE 143/385: celltype=CD8 T, leave_out=Pool138_13, global_p=0.154, elapsed=0.41 min
    total=55404, sanity=55404, nan=55404, >0=0, <0=0, =0=0

[2026-06-24 09:53:00] Start 144/385: celltype=CD8 T, leave_out=Pool138_14
[2026-06-24 09:53:06] Running neighbors: n_cells=55036
[2026-06-24 09:53:18] Building sample metadata
[2026-06-24 09:53:18] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:53:41] DONE 144/385: celltype=CD8 T, leave_out=Pool138_14, global_p=0.0699, elapsed=0.67 min
    total=55036, sanity=55036, nan=55036, >0=0, <0=0, =0=0

[2026-06-24 09:53:41] Start 145/385: celltype=CD8 T, leave_out=Pool138_15
[2026-06-24 09:53:47] Running neighbors: n_cells=54817
[2026-06-24 09:53:58] Building sample metadata
[2026-06-24 09:53:58] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:54:21] DONE 145/385: celltype=CD8 T, leave_out=Pool138_15, global_p=0.14, elapsed=0.67 min
    total=54817, sanity=54817, nan=54817, >0=0, <0=0, =0=0

[2026-06-24 09:54:22] Start 146/385: celltype=CD8 T, leave_out=Pool138_16
[2026-06-24 09:54:28] Running neighbors: n_cells=54954
[2026-06-24 09:54:39] Building sample metadata
[2026-06-24 09:54:39] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:54:52] DONE 146/385: celltype=CD8 T, leave_out=Pool138_16, global_p=0.132, elapsed=0.51 min
    total=54954, sanity=54954, nan=54954, >0=0, <0=0, =0=0

[2026-06-24 09:54:52] Start 147/385: celltype=CD8 T, leave_out=Pool138_17
[2026-06-24 09:54:55] Running neighbors: n_cells=55438
[2026-06-24 09:55:01] Building sample metadata
[2026-06-24 09:55:01] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:55:12] DONE 147/385: celltype=CD8 T, leave_out=Pool138_17, global_p=0.0639, elapsed=0.33 min
    total=55438, sanity=55438, nan=55438, >0=0, <0=0, =0=0

[2026-06-24 09:55:12] Start 148/385: celltype=CD8 T, leave_out=Pool138_18
[2026-06-24 09:55:15] Running neighbors: n_cells=55882
[2026-06-24 09:55:21] Building sample metadata
[2026-06-24 09:55:21] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:55:32] DONE 148/385: celltype=CD8 T, leave_out=Pool138_18, global_p=0.103, elapsed=0.33 min
    total=55882, sanity=55882, nan=55882, >0=0, <0=0, =0=0

[2026-06-24 09:55:32] Start 149/385: celltype=CD8 T, leave_out=Pool138_19
[2026-06-24 09:55:35] Running neighbors: n_cells=55446
[2026-06-24 09:55:41] Building sample metadata
[2026-06-24 09:55:41] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:55:52] DONE 149/385: celltype=CD8 T, leave_out=Pool138_19, global_p=0.114, elapsed=0.33 min
    total=55446, sanity=55446, nan=55446, >0=0, <0=0, =0=0

[2026-06-24 09:55:52] Start 150/385: celltype=CD8 T, leave_out=Pool138_20
[2026-06-24 09:55:55] Running neighbors: n_cells=55587
[2026-06-24 09:56:01] Building sample metadata
[2026-06-24 09:56:01] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:56:13] DONE 150/385: celltype=CD8 T, leave_out=Pool138_20, global_p=0.142, elapsed=0.34 min
    total=55587, sanity=55587, nan=55587, >0=0, <0=0, =0=0

[2026-06-24 09:56:13] Start 151/385: celltype=CD8 T, leave_out=Pool138_21
[2026-06-24 09:56:16] Running neighbors: n_cells=54926
[2026-06-24 09:56:22] Building sample metadata
[2026-06-24 09:56:22] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:56:33] DONE 151/385: celltype=CD8 T, leave_out=Pool138_21, global_p=0.181, elapsed=0.33 min
    total=54926, sanity=54926, nan=54926, >0=0, <0=0, =0=0

[2026-06-24 09:56:33] Start 152/385: celltype=CD8 T, leave_out=Pool138_22
[2026-06-24 09:56:36] Running neighbors: n_cells=55036
[2026-06-24 09:56:42] Building sample metadata
[2026-06-24 09:56:42] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:56:53] DONE 152/385: celltype=CD8 T, leave_out=Pool138_22, global_p=0.127, elapsed=0.33 min
    total=55036, sanity=55036, nan=55036, >0=0, <0=0, =0=0

[2026-06-24 09:56:53] Start 153/385: celltype=CD8 T, leave_out=Pool138_23
[2026-06-24 09:56:56] Running neighbors: n_cells=55853
[2026-06-24 09:57:02] Building sample metadata
[2026-06-24 09:57:02] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:57:17] DONE 153/385: celltype=CD8 T, leave_out=Pool138_23, global_p=0.168, elapsed=0.39 min
    total=55853, sanity=55853, nan=55853, >0=0, <0=0, =0=0

[2026-06-24 09:57:17] Start 154/385: celltype=CD8 T, leave_out=Pool138_24
[2026-06-24 09:57:23] Running neighbors: n_cells=54286
[2026-06-24 09:57:35] Building sample metadata
[2026-06-24 09:57:35] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:57:57] DONE 154/385: celltype=CD8 T, leave_out=Pool138_24, global_p=0.212, elapsed=0.67 min
    total=54286, sanity=54286, nan=54286, >0=0, <0=0, =0=0

[2026-06-24 09:57:58] Start 155/385: celltype=CD8 T, leave_out=Pool138_25
[2026-06-24 09:58:04] Running neighbors: n_cells=55430
[2026-06-24 09:58:15] Building sample metadata
[2026-06-24 09:58:15] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 09:58:38] DONE 155/385: celltype=CD8 T, leave_out=Pool138_25, global_p=0.14, elapsed=0.68 min
    total=55430, sanity=55430, nan=55430, >0=0, <0=0, =0=0

[2026-06-24 09:58:39] Start 156/385: celltype=CD8 T, leave_out=Pool138_26
[2026-06-24 09:58:45] Running neighbors: n_cells=55891
[2026-06-24 09:58:56] Building sample metadata
[2026-06-24 09:58:56] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:59:16] DONE 156/385: celltype=CD8 T, leave_out=Pool138_26, global_p=0.121, elapsed=0.63 min
    total=55891, sanity=55891, nan=55891, >0=0, <0=0, =0=0

[2026-06-24 09:59:17] Start 157/385: celltype=CD8 T, leave_out=Pool138_27
[2026-06-24 09:59:20] Running neighbors: n_cells=55605
[2026-06-24 09:59:30] Building sample metadata
[2026-06-24 09:59:30] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 09:59:41] DONE 157/385: celltype=CD8 T, leave_out=Pool138_27, global_p=0.111, elapsed=0.41 min
    total=55605, sanity=55605, nan=55605, >0=0, <0=0, =0=0

[2026-06-24 09:59:41] Start 158/385: celltype=CD8 T, leave_out=Pool138_29
[2026-06-24 09:59:44] Running neighbors: n_cells=55252
[2026-06-24 09:59:50] Building sample metadata
[2026-06-24 09:59:50] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:00:01] DONE 158/385: celltype=CD8 T, leave_out=Pool138_29, global_p=0.139, elapsed=0.33 min
    total=55252, sanity=55252, nan=55252, >0=0, <0=0, =0=0

[2026-06-24 10:00:01] Start 159/385: celltype=CD8 T, leave_out=Pool138_3
[2026-06-24 10:00:04] Running neighbors: n_cells=56021
[2026-06-24 10:00:10] Building sample metadata
[2026-06-24 10:00:10] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:00:21] DONE 159/385: celltype=CD8 T, leave_out=Pool138_3, global_p=0.119, elapsed=0.33 min
    total=56021, sanity=56021, nan=56021, >0=0, <0=0, =0=0

[2026-06-24 10:00:21] Start 160/385: celltype=CD8 T, leave_out=Pool138_4
[2026-06-24 10:00:24] Running neighbors: n_cells=55427
[2026-06-24 10:00:30] Building sample metadata
[2026-06-24 10:00:30] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:00:41] DONE 160/385: celltype=CD8 T, leave_out=Pool138_4, global_p=0.243, elapsed=0.33 min
    total=55427, sanity=55427, nan=55427, >0=0, <0=0, =0=0

[2026-06-24 10:00:41] Start 161/385: celltype=CD8 T, leave_out=Pool138_5
[2026-06-24 10:00:44] Running neighbors: n_cells=55600
[2026-06-24 10:00:50] Building sample metadata
[2026-06-24 10:00:50] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:01:01] DONE 161/385: celltype=CD8 T, leave_out=Pool138_5, global_p=0.167, elapsed=0.34 min
    total=55600, sanity=55600, nan=55600, >0=0, <0=0, =0=0

[2026-06-24 10:01:01] Start 162/385: celltype=CD8 T, leave_out=Pool138_6
[2026-06-24 10:01:04] Running neighbors: n_cells=55294
[2026-06-24 10:01:10] Building sample metadata
[2026-06-24 10:01:10] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:01:21] DONE 162/385: celltype=CD8 T, leave_out=Pool138_6, global_p=0.147, elapsed=0.33 min
    total=55294, sanity=55294, nan=55294, >0=0, <0=0, =0=0

[2026-06-24 10:01:21] Start 163/385: celltype=CD8 T, leave_out=Pool138_7
[2026-06-24 10:01:24] Running neighbors: n_cells=54257
[2026-06-24 10:01:30] Building sample metadata
[2026-06-24 10:01:30] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:01:41] DONE 163/385: celltype=CD8 T, leave_out=Pool138_7, global_p=0.177, elapsed=0.33 min
    total=54257, sanity=54257, nan=54257, >0=0, <0=0, =0=0

[2026-06-24 10:01:41] Start 164/385: celltype=CD8 T, leave_out=Pool138_8
[2026-06-24 10:01:44] Running neighbors: n_cells=55057
[2026-06-24 10:01:49] Building sample metadata
[2026-06-24 10:01:49] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:02:01] DONE 164/385: celltype=CD8 T, leave_out=Pool138_8, global_p=0.275, elapsed=0.33 min
    total=55057, sanity=55057, nan=55057, >0=0, <0=0, =0=0

[2026-06-24 10:02:01] Start 165/385: celltype=CD8 T, leave_out=Pool138_9
[2026-06-24 10:02:04] Running neighbors: n_cells=54037
[2026-06-24 10:02:09] Building sample metadata
[2026-06-24 10:02:09] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:02:20] DONE 165/385: celltype=CD8 T, leave_out=Pool138_9, global_p=0.148, elapsed=0.32 min
    total=54037, sanity=54037, nan=54037, >0=0, <0=0, =0=0

[2026-06-24 10:02:20] Start 166/385: celltype=other T, leave_out=Pool137_10
[2026-06-24 10:02:22] Running neighbors: n_cells=8513
[2026-06-24 10:02:23] Building sample metadata
[2026-06-24 10:02:23] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:02:27] DONE 166/385: celltype=other T, leave_out=Pool137_10, global_p=0.545, elapsed=0.11 min
    total=8513, sanity=8513, nan=8513, >0=0, <0=0, =0=0

[2026-06-24 10:02:27] Start 167/385: celltype=other T, leave_out=Pool137_11
[2026-06-24 10:02:28] Running neighbors: n_cells=8417
[2026-06-24 10:02:30] Building sample metadata
[2026-06-24 10:02:30] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:02:33] DONE 167/385: celltype=other T, leave_out=Pool137_11, global_p=0.674, elapsed=0.11 min
    total=8417, sanity=8417, nan=8417, >0=0, <0=0, =0=0

[2026-06-24 10:02:33] Start 168/385: celltype=other T, leave_out=Pool137_12
[2026-06-24 10:02:35] Running neighbors: n_cells=8551
[2026-06-24 10:02:37] Building sample metadata
[2026-06-24 10:02:37] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:02:40] DONE 168/385: celltype=other T, leave_out=Pool137_12, global_p=0.672, elapsed=0.11 min
    total=8551, sanity=8551, nan=8551, >0=0, <0=0, =0=0

[2026-06-24 10:02:40] Start 169/385: celltype=other T, leave_out=Pool137_14
[2026-06-24 10:02:42] Running neighbors: n_cells=8362
[2026-06-24 10:02:43] Building sample metadata
[2026-06-24 10:02:43] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:02:46] DONE 169/385: celltype=other T, leave_out=Pool137_14, global_p=0.394, elapsed=0.11 min
    total=8362, sanity=8362, nan=8362, >0=0, <0=0, =0=0

[2026-06-24 10:02:47] Start 170/385: celltype=other T, leave_out=Pool137_15
[2026-06-24 10:02:48] Running neighbors: n_cells=8471
[2026-06-24 10:02:50] Building sample metadata
[2026-06-24 10:02:50] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:02:53] DONE 170/385: celltype=other T, leave_out=Pool137_15, global_p=0.692, elapsed=0.11 min
    total=8471, sanity=8471, nan=8471, >0=0, <0=0, =0=0

[2026-06-24 10:02:53] Start 171/385: celltype=other T, leave_out=Pool137_16
[2026-06-24 10:02:55] Running neighbors: n_cells=8507
[2026-06-24 10:02:57] Building sample metadata
[2026-06-24 10:02:57] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:03:00] DONE 171/385: celltype=other T, leave_out=Pool137_16, global_p=0.774, elapsed=0.11 min
    total=8507, sanity=8507, nan=8507, >0=0, <0=0, =0=0

[2026-06-24 10:03:00] Start 172/385: celltype=other T, leave_out=Pool137_17
[2026-06-24 10:03:02] Running neighbors: n_cells=8309
[2026-06-24 10:03:03] Building sample metadata
[2026-06-24 10:03:03] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:03:06] DONE 172/385: celltype=other T, leave_out=Pool137_17, global_p=0.554, elapsed=0.10 min
    total=8309, sanity=8309, nan=8309, >0=0, <0=0, =0=0

[2026-06-24 10:03:06] Start 173/385: celltype=other T, leave_out=Pool137_18
[2026-06-24 10:03:08] Running neighbors: n_cells=8047
[2026-06-24 10:03:09] Building sample metadata
[2026-06-24 10:03:09] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:03:12] DONE 173/385: celltype=other T, leave_out=Pool137_18, global_p=0.345, elapsed=0.10 min
    total=8047, sanity=8047, nan=8047, >0=0, <0=0, =0=0

[2026-06-24 10:03:12] Start 174/385: celltype=other T, leave_out=Pool137_19
[2026-06-24 10:03:14] Running neighbors: n_cells=8394
[2026-06-24 10:03:16] Building sample metadata
[2026-06-24 10:03:16] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:03:19] DONE 174/385: celltype=other T, leave_out=Pool137_19, global_p=0.616, elapsed=0.11 min
    total=8394, sanity=8394, nan=8394, >0=0, <0=0, =0=0

[2026-06-24 10:03:19] Start 175/385: celltype=other T, leave_out=Pool137_20
[2026-06-24 10:03:21] Running neighbors: n_cells=8583
[2026-06-24 10:03:22] Building sample metadata
[2026-06-24 10:03:22] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:03:25] DONE 175/385: celltype=other T, leave_out=Pool137_20, global_p=0.544, elapsed=0.11 min
    total=8583, sanity=8583, nan=8583, >0=0, <0=0, =0=0

[2026-06-24 10:03:26] Start 176/385: celltype=other T, leave_out=Pool137_21
[2026-06-24 10:03:27] Running neighbors: n_cells=8126
[2026-06-24 10:03:28] Building sample metadata
[2026-06-24 10:03:28] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:03:31] DONE 176/385: celltype=other T, leave_out=Pool137_21, global_p=0.724, elapsed=0.09 min
    total=8126, sanity=8126, nan=8126, >0=0, <0=0, =0=0

[2026-06-24 10:03:31] Start 177/385: celltype=other T, leave_out=Pool137_22
[2026-06-24 10:03:33] Running neighbors: n_cells=8334
[2026-06-24 10:03:34] Building sample metadata
[2026-06-24 10:03:34] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:03:38] DONE 177/385: celltype=other T, leave_out=Pool137_22, global_p=0.711, elapsed=0.11 min
    total=8334, sanity=8334, nan=8334, >0=0, <0=0, =0=0

[2026-06-24 10:03:38] Start 178/385: celltype=other T, leave_out=Pool137_23
[2026-06-24 10:03:40] Running neighbors: n_cells=8570
[2026-06-24 10:03:41] Building sample metadata
[2026-06-24 10:03:41] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:03:45] DONE 178/385: celltype=other T, leave_out=Pool137_23, global_p=0.642, elapsed=0.11 min
    total=8570, sanity=8570, nan=8570, >0=0, <0=0, =0=0

[2026-06-24 10:03:45] Start 179/385: celltype=other T, leave_out=Pool137_24
[2026-06-24 10:03:47] Running neighbors: n_cells=8319
[2026-06-24 10:03:48] Building sample metadata
[2026-06-24 10:03:48] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:03:52] DONE 179/385: celltype=other T, leave_out=Pool137_24, global_p=0.591, elapsed=0.11 min
    total=8319, sanity=8319, nan=8319, >0=0, <0=0, =0=0

[2026-06-24 10:03:52] Start 180/385: celltype=other T, leave_out=Pool137_25
[2026-06-24 10:03:54] Running neighbors: n_cells=8555
[2026-06-24 10:03:56] Building sample metadata
[2026-06-24 10:03:56] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:03:59] DONE 180/385: celltype=other T, leave_out=Pool137_25, global_p=0.571, elapsed=0.12 min
    total=8555, sanity=8555, nan=8555, >0=0, <0=0, =0=0

[2026-06-24 10:04:00] Start 181/385: celltype=other T, leave_out=Pool137_26
[2026-06-24 10:04:01] Running neighbors: n_cells=8348
[2026-06-24 10:04:03] Building sample metadata
[2026-06-24 10:04:03] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:04:06] DONE 181/385: celltype=other T, leave_out=Pool137_26, global_p=0.46, elapsed=0.11 min
    total=8348, sanity=8348, nan=8348, >0=0, <0=0, =0=0

[2026-06-24 10:04:07] Start 182/385: celltype=other T, leave_out=Pool137_27
[2026-06-24 10:04:08] Running neighbors: n_cells=8539
[2026-06-24 10:04:10] Building sample metadata
[2026-06-24 10:04:10] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:04:13] DONE 182/385: celltype=other T, leave_out=Pool137_27, global_p=0.694, elapsed=0.11 min
    total=8539, sanity=8539, nan=8539, >0=0, <0=0, =0=0

[2026-06-24 10:04:13] Start 183/385: celltype=other T, leave_out=Pool137_28
[2026-06-24 10:04:15] Running neighbors: n_cells=8518
[2026-06-24 10:04:17] Building sample metadata
[2026-06-24 10:04:17] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:04:20] DONE 183/385: celltype=other T, leave_out=Pool137_28, global_p=0.72, elapsed=0.11 min
    total=8518, sanity=8518, nan=8518, >0=0, <0=0, =0=0

[2026-06-24 10:04:20] Start 184/385: celltype=other T, leave_out=Pool137_29
[2026-06-24 10:04:22] Running neighbors: n_cells=8437
[2026-06-24 10:04:24] Building sample metadata
[2026-06-24 10:04:24] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:04:27] DONE 184/385: celltype=other T, leave_out=Pool137_29, global_p=0.663, elapsed=0.11 min
    total=8437, sanity=8437, nan=8437, >0=0, <0=0, =0=0

[2026-06-24 10:04:27] Start 185/385: celltype=other T, leave_out=Pool137_30
[2026-06-24 10:04:29] Running neighbors: n_cells=8074
[2026-06-24 10:04:29] Building sample metadata
[2026-06-24 10:04:29] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:04:32] DONE 185/385: celltype=other T, leave_out=Pool137_30, global_p=0.771, elapsed=0.09 min
    total=8074, sanity=8074, nan=8074, >0=0, <0=0, =0=0

[2026-06-24 10:04:33] Start 186/385: celltype=other T, leave_out=Pool137_31
[2026-06-24 10:04:34] Running neighbors: n_cells=8548
[2026-06-24 10:04:36] Building sample metadata
[2026-06-24 10:04:36] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:04:39] DONE 186/385: celltype=other T, leave_out=Pool137_31, global_p=0.706, elapsed=0.11 min
    total=8548, sanity=8548, nan=8548, >0=0, <0=0, =0=0

[2026-06-24 10:04:39] Start 187/385: celltype=other T, leave_out=Pool137_33
[2026-06-24 10:04:41] Running neighbors: n_cells=8522
[2026-06-24 10:04:43] Building sample metadata
[2026-06-24 10:04:43] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:04:46] DONE 187/385: celltype=other T, leave_out=Pool137_33, global_p=0.779, elapsed=0.11 min
    total=8522, sanity=8522, nan=8522, >0=0, <0=0, =0=0

[2026-06-24 10:04:46] Start 188/385: celltype=other T, leave_out=Pool137_34
[2026-06-24 10:04:48] Running neighbors: n_cells=8404
[2026-06-24 10:04:50] Building sample metadata
[2026-06-24 10:04:50] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:04:53] DONE 188/385: celltype=other T, leave_out=Pool137_34, global_p=0.517, elapsed=0.11 min
    total=8404, sanity=8404, nan=8404, >0=0, <0=0, =0=0

[2026-06-24 10:04:53] Start 189/385: celltype=other T, leave_out=Pool137_35
[2026-06-24 10:04:55] Running neighbors: n_cells=7772
[2026-06-24 10:04:55] Building sample metadata
[2026-06-24 10:04:55] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:04:58] DONE 189/385: celltype=other T, leave_out=Pool137_35, global_p=0.479, elapsed=0.09 min
    total=7772, sanity=7772, nan=7772, >0=0, <0=0, =0=0

[2026-06-24 10:04:58] Start 190/385: celltype=other T, leave_out=Pool137_36
[2026-06-24 10:05:00] Running neighbors: n_cells=8525
[2026-06-24 10:05:02] Building sample metadata
[2026-06-24 10:05:02] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:05:05] DONE 190/385: celltype=other T, leave_out=Pool137_36, global_p=0.62, elapsed=0.11 min
    total=8525, sanity=8525, nan=8525, >0=0, <0=0, =0=0

[2026-06-24 10:05:05] Start 191/385: celltype=other T, leave_out=Pool137_6
[2026-06-24 10:05:07] Running neighbors: n_cells=8083
[2026-06-24 10:05:07] Building sample metadata
[2026-06-24 10:05:07] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:05:10] DONE 191/385: celltype=other T, leave_out=Pool137_6, global_p=0.807, elapsed=0.09 min
    total=8083, sanity=8083, nan=8083, >0=0, <0=0, =0=0

[2026-06-24 10:05:11] Start 192/385: celltype=other T, leave_out=Pool137_7
[2026-06-24 10:05:12] Running neighbors: n_cells=8189
[2026-06-24 10:05:13] Building sample metadata
[2026-06-24 10:05:13] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:05:16] DONE 192/385: celltype=other T, leave_out=Pool137_7, global_p=0.7, elapsed=0.09 min
    total=8189, sanity=8189, nan=8189, >0=0, <0=0, =0=0

[2026-06-24 10:05:16] Start 193/385: celltype=other T, leave_out=Pool137_8
[2026-06-24 10:05:18] Running neighbors: n_cells=8551
[2026-06-24 10:05:19] Building sample metadata
[2026-06-24 10:05:19] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:05:22] DONE 193/385: celltype=other T, leave_out=Pool137_8, global_p=0.663, elapsed=0.11 min
    total=8551, sanity=8551, nan=8551, >0=0, <0=0, =0=0

[2026-06-24 10:05:23] Start 194/385: celltype=other T, leave_out=Pool137_9
[2026-06-24 10:05:24] Running neighbors: n_cells=8569
[2026-06-24 10:05:26] Building sample metadata
[2026-06-24 10:05:26] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:05:29] DONE 194/385: celltype=other T, leave_out=Pool137_9, global_p=0.727, elapsed=0.11 min
    total=8569, sanity=8569, nan=8569, >0=0, <0=0, =0=0

[2026-06-24 10:05:29] Start 195/385: celltype=other T, leave_out=Pool138_10
[2026-06-24 10:05:31] Running neighbors: n_cells=8575
[2026-06-24 10:05:33] Building sample metadata
[2026-06-24 10:05:33] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:05:36] DONE 195/385: celltype=other T, leave_out=Pool138_10, global_p=0.781, elapsed=0.11 min
    total=8575, sanity=8575, nan=8575, >0=0, <0=0, =0=0

[2026-06-24 10:05:36] Start 196/385: celltype=other T, leave_out=Pool138_11
[2026-06-24 10:05:38] Running neighbors: n_cells=8464
[2026-06-24 10:05:39] Building sample metadata
[2026-06-24 10:05:39] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:05:42] DONE 196/385: celltype=other T, leave_out=Pool138_11, global_p=0.619, elapsed=0.11 min
    total=8464, sanity=8464, nan=8464, >0=0, <0=0, =0=0

[2026-06-24 10:05:43] Start 197/385: celltype=other T, leave_out=Pool138_12
[2026-06-24 10:05:44] Running neighbors: n_cells=8565
[2026-06-24 10:05:46] Building sample metadata
[2026-06-24 10:05:46] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:05:49] DONE 197/385: celltype=other T, leave_out=Pool138_12, global_p=0.73, elapsed=0.11 min
    total=8565, sanity=8565, nan=8565, >0=0, <0=0, =0=0

[2026-06-24 10:05:49] Start 198/385: celltype=other T, leave_out=Pool138_13
[2026-06-24 10:05:51] Running neighbors: n_cells=8511
[2026-06-24 10:05:53] Building sample metadata
[2026-06-24 10:05:53] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:05:56] DONE 198/385: celltype=other T, leave_out=Pool138_13, global_p=0.588, elapsed=0.11 min
    total=8511, sanity=8511, nan=8511, >0=0, <0=0, =0=0

[2026-06-24 10:05:56] Start 199/385: celltype=other T, leave_out=Pool138_14
[2026-06-24 10:05:58] Running neighbors: n_cells=8495
[2026-06-24 10:05:59] Building sample metadata
[2026-06-24 10:05:59] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:06:02] DONE 199/385: celltype=other T, leave_out=Pool138_14, global_p=0.664, elapsed=0.11 min
    total=8495, sanity=8495, nan=8495, >0=0, <0=0, =0=0

[2026-06-24 10:06:03] Start 200/385: celltype=other T, leave_out=Pool138_15
[2026-06-24 10:06:04] Running neighbors: n_cells=8312
[2026-06-24 10:06:06] Building sample metadata
[2026-06-24 10:06:06] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:06:09] DONE 200/385: celltype=other T, leave_out=Pool138_15, global_p=0.68, elapsed=0.11 min
    total=8312, sanity=8312, nan=8312, >0=0, <0=0, =0=0

[2026-06-24 10:06:09] Start 201/385: celltype=other T, leave_out=Pool138_16
[2026-06-24 10:06:11] Running neighbors: n_cells=8500
[2026-06-24 10:06:12] Building sample metadata
[2026-06-24 10:06:12] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:06:16] DONE 201/385: celltype=other T, leave_out=Pool138_16, global_p=0.695, elapsed=0.11 min
    total=8500, sanity=8500, nan=8500, >0=0, <0=0, =0=0

[2026-06-24 10:06:16] Start 202/385: celltype=other T, leave_out=Pool138_17
[2026-06-24 10:06:18] Running neighbors: n_cells=8586
[2026-06-24 10:06:19] Building sample metadata
[2026-06-24 10:06:19] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=52

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:06:22] DONE 202/385: celltype=other T, leave_out=Pool138_17, global_p=0.672, elapsed=0.11 min
    total=8586, sanity=8586, nan=8586, >0=0, <0=0, =0=0

[2026-06-24 10:06:23] Start 203/385: celltype=other T, leave_out=Pool138_18
[2026-06-24 10:06:24] Running neighbors: n_cells=8553
[2026-06-24 10:06:26] Building sample metadata
[2026-06-24 10:06:26] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:06:29] DONE 203/385: celltype=other T, leave_out=Pool138_18, global_p=0.493, elapsed=0.11 min
    total=8553, sanity=8553, nan=8553, >0=0, <0=0, =0=0

[2026-06-24 10:06:29] Start 204/385: celltype=other T, leave_out=Pool138_19
[2026-06-24 10:06:31] Running neighbors: n_cells=8567
[2026-06-24 10:06:33] Building sample metadata
[2026-06-24 10:06:33] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:06:36] DONE 204/385: celltype=other T, leave_out=Pool138_19, global_p=0.716, elapsed=0.11 min
    total=8567, sanity=8567, nan=8567, >0=0, <0=0, =0=0

[2026-06-24 10:06:36] Start 205/385: celltype=other T, leave_out=Pool138_20
[2026-06-24 10:06:38] Running neighbors: n_cells=8586
[2026-06-24 10:06:39] Building sample metadata
[2026-06-24 10:06:39] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=52

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:06:42] DONE 205/385: celltype=other T, leave_out=Pool138_20, global_p=0.674, elapsed=0.11 min
    total=8586, sanity=8586, nan=8586, >0=0, <0=0, =0=0

[2026-06-24 10:06:43] Start 206/385: celltype=other T, leave_out=Pool138_21
[2026-06-24 10:06:44] Running neighbors: n_cells=8356
[2026-06-24 10:06:46] Building sample metadata
[2026-06-24 10:06:46] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:06:49] DONE 206/385: celltype=other T, leave_out=Pool138_21, global_p=0.635, elapsed=0.11 min
    total=8356, sanity=8356, nan=8356, >0=0, <0=0, =0=0

[2026-06-24 10:06:49] Start 207/385: celltype=other T, leave_out=Pool138_22
[2026-06-24 10:06:51] Running neighbors: n_cells=8261
[2026-06-24 10:06:53] Building sample metadata
[2026-06-24 10:06:53] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:06:56] DONE 207/385: celltype=other T, leave_out=Pool138_22, global_p=0.806, elapsed=0.11 min
    total=8261, sanity=8261, nan=8261, >0=0, <0=0, =0=0

[2026-06-24 10:06:56] Start 208/385: celltype=other T, leave_out=Pool138_23
[2026-06-24 10:06:58] Running neighbors: n_cells=8540
[2026-06-24 10:06:59] Building sample metadata
[2026-06-24 10:06:59] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:07:03] DONE 208/385: celltype=other T, leave_out=Pool138_23, global_p=0.67, elapsed=0.11 min
    total=8540, sanity=8540, nan=8540, >0=0, <0=0, =0=0

[2026-06-24 10:07:03] Start 209/385: celltype=other T, leave_out=Pool138_24
[2026-06-24 10:07:05] Running neighbors: n_cells=8181
[2026-06-24 10:07:05] Building sample metadata
[2026-06-24 10:07:05] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:07:08] DONE 209/385: celltype=other T, leave_out=Pool138_24, global_p=0.596, elapsed=0.09 min
    total=8181, sanity=8181, nan=8181, >0=0, <0=0, =0=0

[2026-06-24 10:07:08] Start 210/385: celltype=other T, leave_out=Pool138_25
[2026-06-24 10:07:10] Running neighbors: n_cells=8549
[2026-06-24 10:07:12] Building sample metadata
[2026-06-24 10:07:12] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:07:15] DONE 210/385: celltype=other T, leave_out=Pool138_25, global_p=0.619, elapsed=0.11 min
    total=8549, sanity=8549, nan=8549, >0=0, <0=0, =0=0

[2026-06-24 10:07:15] Start 211/385: celltype=other T, leave_out=Pool138_26
[2026-06-24 10:07:17] Running neighbors: n_cells=8549
[2026-06-24 10:07:19] Building sample metadata
[2026-06-24 10:07:19] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:07:22] DONE 211/385: celltype=other T, leave_out=Pool138_26, global_p=0.702, elapsed=0.11 min
    total=8549, sanity=8549, nan=8549, >0=0, <0=0, =0=0

[2026-06-24 10:07:22] Start 212/385: celltype=other T, leave_out=Pool138_27
[2026-06-24 10:07:24] Running neighbors: n_cells=8496
[2026-06-24 10:07:25] Building sample metadata
[2026-06-24 10:07:25] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:07:29] DONE 212/385: celltype=other T, leave_out=Pool138_27, global_p=0.721, elapsed=0.11 min
    total=8496, sanity=8496, nan=8496, >0=0, <0=0, =0=0

[2026-06-24 10:07:29] Start 213/385: celltype=other T, leave_out=Pool138_29
[2026-06-24 10:07:31] Running neighbors: n_cells=8582
[2026-06-24 10:07:32] Building sample metadata
[2026-06-24 10:07:32] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:07:36] DONE 213/385: celltype=other T, leave_out=Pool138_29, global_p=0.708, elapsed=0.11 min
    total=8582, sanity=8582, nan=8582, >0=0, <0=0, =0=0

[2026-06-24 10:07:36] Start 214/385: celltype=other T, leave_out=Pool138_3
[2026-06-24 10:07:37] Running neighbors: n_cells=8552
[2026-06-24 10:07:39] Building sample metadata
[2026-06-24 10:07:39] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:07:42] DONE 214/385: celltype=other T, leave_out=Pool138_3, global_p=0.523, elapsed=0.11 min
    total=8552, sanity=8552, nan=8552, >0=0, <0=0, =0=0

[2026-06-24 10:07:43] Start 215/385: celltype=other T, leave_out=Pool138_4
[2026-06-24 10:07:44] Running neighbors: n_cells=8486
[2026-06-24 10:07:46] Building sample metadata
[2026-06-24 10:07:46] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:07:49] DONE 215/385: celltype=other T, leave_out=Pool138_4, global_p=0.748, elapsed=0.11 min
    total=8486, sanity=8486, nan=8486, >0=0, <0=0, =0=0

[2026-06-24 10:07:49] Start 216/385: celltype=other T, leave_out=Pool138_5
[2026-06-24 10:07:51] Running neighbors: n_cells=8410
[2026-06-24 10:07:53] Building sample metadata
[2026-06-24 10:07:53] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:07:56] DONE 216/385: celltype=other T, leave_out=Pool138_5, global_p=0.633, elapsed=0.11 min
    total=8410, sanity=8410, nan=8410, >0=0, <0=0, =0=0

[2026-06-24 10:07:56] Start 217/385: celltype=other T, leave_out=Pool138_6
[2026-06-24 10:07:58] Running neighbors: n_cells=8220
[2026-06-24 10:07:59] Building sample metadata
[2026-06-24 10:07:59] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:08:03] DONE 217/385: celltype=other T, leave_out=Pool138_6, global_p=0.656, elapsed=0.11 min
    total=8220, sanity=8220, nan=8220, >0=0, <0=0, =0=0

[2026-06-24 10:08:03] Start 218/385: celltype=other T, leave_out=Pool138_7
[2026-06-24 10:08:05] Running neighbors: n_cells=8568
[2026-06-24 10:08:06] Building sample metadata
[2026-06-24 10:08:06] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:08:09] DONE 218/385: celltype=other T, leave_out=Pool138_7, global_p=0.579, elapsed=0.11 min
    total=8568, sanity=8568, nan=8568, >0=0, <0=0, =0=0

[2026-06-24 10:08:10] Start 219/385: celltype=other T, leave_out=Pool138_8
[2026-06-24 10:08:12] Running neighbors: n_cells=8457
[2026-06-24 10:08:13] Building sample metadata
[2026-06-24 10:08:13] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=51

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:08:16] DONE 219/385: celltype=other T, leave_out=Pool138_8, global_p=0.758, elapsed=0.11 min
    total=8457, sanity=8457, nan=8457, >0=0, <0=0, =0=0

[2026-06-24 10:08:16] Start 220/385: celltype=other T, leave_out=Pool138_9
[2026-06-24 10:08:18] Running neighbors: n_cells=8586
[2026-06-24 10:08:20] Building sample metadata
[2026-06-24 10:08:20] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=52

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:08:23] DONE 220/385: celltype=other T, leave_out=Pool138_9, global_p=0.661, elapsed=0.11 min
    total=8586, sanity=8586, nan=8586, >0=0, <0=0, =0=0

[2026-06-24 10:08:23] Start 221/385: celltype=DC, leave_out=Pool137_10
[2026-06-24 10:08:25] Running neighbors: n_cells=7737
[2026-06-24 10:08:25] Building sample metadata
[2026-06-24 10:08:25] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:08:29] DONE 221/385: celltype=DC, leave_out=Pool137_10, global_p=0.003, elapsed=0.09 min
    total=7737, sanity=7737, nan=7436, >0=55, <0=246, =0=0

[2026-06-24 10:08:29] Start 222/385: celltype=DC, leave_out=Pool137_11
[2026-06-24 10:08:31] Running neighbors: n_cells=7749
[2026-06-24 10:08:31] Building sample metadata
[2026-06-24 10:08:31] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:08:34] DONE 222/385: celltype=DC, leave_out=Pool137_11, global_p=0.002, elapsed=0.09 min
    total=7749, sanity=7749, nan=7381, >0=63, <0=305, =0=0

[2026-06-24 10:08:34] Start 223/385: celltype=DC, leave_out=Pool137_12
[2026-06-24 10:08:36] Running neighbors: n_cells=7828
[2026-06-24 10:08:37] Building sample metadata
[2026-06-24 10:08:37] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:08:40] DONE 223/385: celltype=DC, leave_out=Pool137_12, global_p=0.002, elapsed=0.09 min
    total=7828, sanity=7828, nan=7519, >0=54, <0=255, =0=0

[2026-06-24 10:08:40] Start 224/385: celltype=DC, leave_out=Pool137_14
[2026-06-24 10:08:42] Running neighbors: n_cells=7776
[2026-06-24 10:08:42] Building sample metadata
[2026-06-24 10:08:42] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:08:46] DONE 224/385: celltype=DC, leave_out=Pool137_14, global_p=0.000999, elapsed=0.09 min
    total=7776, sanity=7776, nan=7394, >0=51, <0=331, =0=0

[2026-06-24 10:08:46] Start 225/385: celltype=DC, leave_out=Pool137_15
[2026-06-24 10:08:48] Running neighbors: n_cells=7846
[2026-06-24 10:08:48] Building sample metadata
[2026-06-24 10:08:48] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:08:51] DONE 225/385: celltype=DC, leave_out=Pool137_15, global_p=0.00699, elapsed=0.09 min
    total=7846, sanity=7846, nan=7573, >0=52, <0=221, =0=0

[2026-06-24 10:08:52] Start 226/385: celltype=DC, leave_out=Pool137_16
[2026-06-24 10:08:54] Running neighbors: n_cells=7816
[2026-06-24 10:08:54] Building sample metadata
[2026-06-24 10:08:54] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:08:57] DONE 226/385: celltype=DC, leave_out=Pool137_16, global_p=0.003, elapsed=0.09 min
    total=7816, sanity=7816, nan=7513, >0=64, <0=239, =0=0

[2026-06-24 10:08:57] Start 227/385: celltype=DC, leave_out=Pool137_17
[2026-06-24 10:08:59] Running neighbors: n_cells=7793
[2026-06-24 10:09:00] Building sample metadata
[2026-06-24 10:09:00] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:09:03] DONE 227/385: celltype=DC, leave_out=Pool137_17, global_p=0.004, elapsed=0.09 min
    total=7793, sanity=7793, nan=7625, >0=38, <0=130, =0=0

[2026-06-24 10:09:03] Start 228/385: celltype=DC, leave_out=Pool137_18
[2026-06-24 10:09:05] Running neighbors: n_cells=7795
[2026-06-24 10:09:05] Building sample metadata
[2026-06-24 10:09:05] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:09:08] DONE 228/385: celltype=DC, leave_out=Pool137_18, global_p=0.002, elapsed=0.09 min
    total=7795, sanity=7795, nan=7480, >0=48, <0=267, =0=0

[2026-06-24 10:09:09] Start 229/385: celltype=DC, leave_out=Pool137_19
[2026-06-24 10:09:11] Running neighbors: n_cells=7748
[2026-06-24 10:09:11] Building sample metadata
[2026-06-24 10:09:11] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:09:14] DONE 229/385: celltype=DC, leave_out=Pool137_19, global_p=0.003, elapsed=0.09 min
    total=7748, sanity=7748, nan=7407, >0=59, <0=282, =0=0

[2026-06-24 10:09:14] Start 230/385: celltype=DC, leave_out=Pool137_20
[2026-06-24 10:09:16] Running neighbors: n_cells=7916
[2026-06-24 10:09:17] Building sample metadata
[2026-06-24 10:09:17] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:09:20] DONE 230/385: celltype=DC, leave_out=Pool137_20, global_p=0.000999, elapsed=0.09 min
    total=7916, sanity=7916, nan=7846, >0=24, <0=46, =0=0

[2026-06-24 10:09:20] Start 231/385: celltype=DC, leave_out=Pool137_21
[2026-06-24 10:09:22] Running neighbors: n_cells=7783
[2026-06-24 10:09:22] Building sample metadata
[2026-06-24 10:09:22] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:09:25] DONE 231/385: celltype=DC, leave_out=Pool137_21, global_p=0.002, elapsed=0.09 min
    total=7783, sanity=7783, nan=7609, >0=41, <0=133, =0=0

[2026-06-24 10:09:26] Start 232/385: celltype=DC, leave_out=Pool137_22
[2026-06-24 10:09:28] Running neighbors: n_cells=7720
[2026-06-24 10:09:28] Building sample metadata
[2026-06-24 10:09:28] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:09:31] DONE 232/385: celltype=DC, leave_out=Pool137_22, global_p=0.002, elapsed=0.09 min
    total=7720, sanity=7720, nan=7535, >0=35, <0=150, =0=0

[2026-06-24 10:09:31] Start 233/385: celltype=DC, leave_out=Pool137_23
[2026-06-24 10:09:33] Running neighbors: n_cells=7888
[2026-06-24 10:09:34] Building sample metadata
[2026-06-24 10:09:34] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:09:37] DONE 233/385: celltype=DC, leave_out=Pool137_23, global_p=0.000999, elapsed=0.09 min
    total=7888, sanity=7888, nan=7499, >0=68, <0=321, =0=0

[2026-06-24 10:09:37] Start 234/385: celltype=DC, leave_out=Pool137_24
[2026-06-24 10:09:39] Running neighbors: n_cells=7763
[2026-06-24 10:09:39] Building sample metadata
[2026-06-24 10:09:39] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:09:42] DONE 234/385: celltype=DC, leave_out=Pool137_24, global_p=0.002, elapsed=0.09 min
    total=7763, sanity=7763, nan=7343, >0=68, <0=352, =0=0

[2026-06-24 10:09:43] Start 235/385: celltype=DC, leave_out=Pool137_25
[2026-06-24 10:09:45] Running neighbors: n_cells=7690
[2026-06-24 10:09:45] Building sample metadata
[2026-06-24 10:09:45] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:09:48] DONE 235/385: celltype=DC, leave_out=Pool137_25, global_p=0.00599, elapsed=0.09 min
    total=7690, sanity=7690, nan=7372, >0=54, <0=264, =0=0

[2026-06-24 10:09:48] Start 236/385: celltype=DC, leave_out=Pool137_26
[2026-06-24 10:09:50] Running neighbors: n_cells=7730
[2026-06-24 10:09:51] Building sample metadata
[2026-06-24 10:09:51] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:09:54] DONE 236/385: celltype=DC, leave_out=Pool137_26, global_p=0.000999, elapsed=0.09 min
    total=7730, sanity=7730, nan=7333, >0=56, <0=341, =0=0

[2026-06-24 10:09:54] Start 237/385: celltype=DC, leave_out=Pool137_27
[2026-06-24 10:09:56] Running neighbors: n_cells=7893
[2026-06-24 10:09:56] Building sample metadata
[2026-06-24 10:09:56] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:10:00] DONE 237/385: celltype=DC, leave_out=Pool137_27, global_p=0.002, elapsed=0.09 min
    total=7893, sanity=7893, nan=7633, >0=50, <0=210, =0=0

[2026-06-24 10:10:00] Start 238/385: celltype=DC, leave_out=Pool137_28
[2026-06-24 10:10:02] Running neighbors: n_cells=7804
[2026-06-24 10:10:02] Building sample metadata
[2026-06-24 10:10:02] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:10:05] DONE 238/385: celltype=DC, leave_out=Pool137_28, global_p=0.004, elapsed=0.09 min
    total=7804, sanity=7804, nan=7471, >0=55, <0=278, =0=0

[2026-06-24 10:10:05] Start 239/385: celltype=DC, leave_out=Pool137_29
[2026-06-24 10:10:07] Running neighbors: n_cells=7608
[2026-06-24 10:10:08] Building sample metadata
[2026-06-24 10:10:08] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:10:11] DONE 239/385: celltype=DC, leave_out=Pool137_29, global_p=0.002, elapsed=0.09 min
    total=7608, sanity=7608, nan=7404, >0=44, <0=160, =0=0

[2026-06-24 10:10:11] Start 240/385: celltype=DC, leave_out=Pool137_30
[2026-06-24 10:10:13] Running neighbors: n_cells=7753
[2026-06-24 10:10:14] Building sample metadata
[2026-06-24 10:10:14] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:10:17] DONE 240/385: celltype=DC, leave_out=Pool137_30, global_p=0.002, elapsed=0.09 min
    total=7753, sanity=7753, nan=7465, >0=60, <0=228, =0=0

[2026-06-24 10:10:17] Start 241/385: celltype=DC, leave_out=Pool137_31
[2026-06-24 10:10:19] Running neighbors: n_cells=7836
[2026-06-24 10:10:19] Building sample metadata
[2026-06-24 10:10:19] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:10:22] DONE 241/385: celltype=DC, leave_out=Pool137_31, global_p=0.004, elapsed=0.09 min
    total=7836, sanity=7836, nan=7548, >0=45, <0=243, =0=0

[2026-06-24 10:10:23] Start 242/385: celltype=DC, leave_out=Pool137_33
[2026-06-24 10:10:25] Running neighbors: n_cells=7878
[2026-06-24 10:10:25] Building sample metadata
[2026-06-24 10:10:25] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:10:28] DONE 242/385: celltype=DC, leave_out=Pool137_33, global_p=0.002, elapsed=0.09 min
    total=7878, sanity=7878, nan=7690, >0=44, <0=144, =0=0

[2026-06-24 10:10:28] Start 243/385: celltype=DC, leave_out=Pool137_34
[2026-06-24 10:10:30] Running neighbors: n_cells=7676
[2026-06-24 10:10:31] Building sample metadata
[2026-06-24 10:10:31] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:10:34] DONE 243/385: celltype=DC, leave_out=Pool137_34, global_p=0.000999, elapsed=0.09 min
    total=7676, sanity=7676, nan=7302, >0=70, <0=304, =0=0

[2026-06-24 10:10:34] Start 244/385: celltype=DC, leave_out=Pool137_35
[2026-06-24 10:10:36] Running neighbors: n_cells=7619
[2026-06-24 10:10:36] Building sample metadata
[2026-06-24 10:10:36] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:10:39] DONE 244/385: celltype=DC, leave_out=Pool137_35, global_p=0.002, elapsed=0.09 min
    total=7619, sanity=7619, nan=7379, >0=44, <0=196, =0=0

[2026-06-24 10:10:39] Start 245/385: celltype=DC, leave_out=Pool137_36
[2026-06-24 10:10:41] Running neighbors: n_cells=7876
[2026-06-24 10:10:42] Building sample metadata
[2026-06-24 10:10:42] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:10:45] DONE 245/385: celltype=DC, leave_out=Pool137_36, global_p=0.00599, elapsed=0.09 min
    total=7876, sanity=7876, nan=7876, >0=0, <0=0, =0=0

[2026-06-24 10:10:45] Start 246/385: celltype=DC, leave_out=Pool137_6
[2026-06-24 10:10:47] Running neighbors: n_cells=7825
[2026-06-24 10:10:47] Building sample metadata
[2026-06-24 10:10:47] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:10:51] DONE 246/385: celltype=DC, leave_out=Pool137_6, global_p=0.000999, elapsed=0.09 min
    total=7825, sanity=7825, nan=7538, >0=46, <0=241, =0=0

[2026-06-24 10:10:51] Start 247/385: celltype=DC, leave_out=Pool137_7
[2026-06-24 10:10:53] Running neighbors: n_cells=7824
[2026-06-24 10:10:53] Building sample metadata
[2026-06-24 10:10:53] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:10:56] DONE 247/385: celltype=DC, leave_out=Pool137_7, global_p=0.000999, elapsed=0.09 min
    total=7824, sanity=7824, nan=7534, >0=47, <0=243, =0=0

[2026-06-24 10:10:57] Start 248/385: celltype=DC, leave_out=Pool137_8
[2026-06-24 10:10:59] Running neighbors: n_cells=7847
[2026-06-24 10:10:59] Building sample metadata
[2026-06-24 10:10:59] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:11:02] DONE 248/385: celltype=DC, leave_out=Pool137_8, global_p=0.003, elapsed=0.09 min
    total=7847, sanity=7847, nan=7557, >0=55, <0=235, =0=0

[2026-06-24 10:11:02] Start 249/385: celltype=DC, leave_out=Pool137_9
[2026-06-24 10:11:04] Running neighbors: n_cells=7856
[2026-06-24 10:11:05] Building sample metadata
[2026-06-24 10:11:05] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:11:08] DONE 249/385: celltype=DC, leave_out=Pool137_9, global_p=0.002, elapsed=0.09 min
    total=7856, sanity=7856, nan=7567, >0=55, <0=234, =0=0

[2026-06-24 10:11:08] Start 250/385: celltype=DC, leave_out=Pool138_10
[2026-06-24 10:11:10] Running neighbors: n_cells=7780
[2026-06-24 10:11:10] Building sample metadata
[2026-06-24 10:11:10] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:11:13] DONE 250/385: celltype=DC, leave_out=Pool138_10, global_p=0.003, elapsed=0.09 min
    total=7780, sanity=7780, nan=7573, >0=37, <0=170, =0=0

[2026-06-24 10:11:14] Start 251/385: celltype=DC, leave_out=Pool138_11
[2026-06-24 10:11:16] Running neighbors: n_cells=7773
[2026-06-24 10:11:16] Building sample metadata
[2026-06-24 10:11:16] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:11:19] DONE 251/385: celltype=DC, leave_out=Pool138_11, global_p=0.003, elapsed=0.09 min
    total=7773, sanity=7773, nan=7572, >0=42, <0=159, =0=0

[2026-06-24 10:11:19] Start 252/385: celltype=DC, leave_out=Pool138_12
[2026-06-24 10:11:21] Running neighbors: n_cells=7798
[2026-06-24 10:11:21] Building sample metadata
[2026-06-24 10:11:21] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:11:25] DONE 252/385: celltype=DC, leave_out=Pool138_12, global_p=0.005, elapsed=0.09 min
    total=7798, sanity=7798, nan=7510, >0=52, <0=236, =0=0

[2026-06-24 10:11:25] Start 253/385: celltype=DC, leave_out=Pool138_13
[2026-06-24 10:11:27] Running neighbors: n_cells=7846
[2026-06-24 10:11:27] Building sample metadata
[2026-06-24 10:11:27] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:11:30] DONE 253/385: celltype=DC, leave_out=Pool138_13, global_p=0.002, elapsed=0.09 min
    total=7846, sanity=7846, nan=7525, >0=55, <0=266, =0=0

[2026-06-24 10:11:30] Start 254/385: celltype=DC, leave_out=Pool138_14
[2026-06-24 10:11:32] Running neighbors: n_cells=7812
[2026-06-24 10:11:33] Building sample metadata
[2026-06-24 10:11:33] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:11:36] DONE 254/385: celltype=DC, leave_out=Pool138_14, global_p=0.003, elapsed=0.09 min
    total=7812, sanity=7812, nan=7457, >0=54, <0=301, =0=0

[2026-06-24 10:11:36] Start 255/385: celltype=DC, leave_out=Pool138_15
[2026-06-24 10:11:38] Running neighbors: n_cells=7707
[2026-06-24 10:11:38] Building sample metadata
[2026-06-24 10:11:38] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:11:42] DONE 255/385: celltype=DC, leave_out=Pool138_15, global_p=0.000999, elapsed=0.09 min
    total=7707, sanity=7707, nan=7363, >0=65, <0=279, =0=0

[2026-06-24 10:11:42] Start 256/385: celltype=DC, leave_out=Pool138_16
[2026-06-24 10:11:44] Running neighbors: n_cells=7855
[2026-06-24 10:11:44] Building sample metadata
[2026-06-24 10:11:44] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:11:47] DONE 256/385: celltype=DC, leave_out=Pool138_16, global_p=0.00599, elapsed=0.09 min
    total=7855, sanity=7855, nan=7549, >0=57, <0=249, =0=0

[2026-06-24 10:11:47] Start 257/385: celltype=DC, leave_out=Pool138_17
[2026-06-24 10:11:50] Running neighbors: n_cells=7910
[2026-06-24 10:11:50] Building sample metadata
[2026-06-24 10:11:50] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:11:53] DONE 257/385: celltype=DC, leave_out=Pool138_17, global_p=0.005, elapsed=0.09 min
    total=7910, sanity=7910, nan=7641, >0=53, <0=216, =0=0

[2026-06-24 10:11:53] Start 258/385: celltype=DC, leave_out=Pool138_18
[2026-06-24 10:11:55] Running neighbors: n_cells=7824
[2026-06-24 10:11:56] Building sample metadata
[2026-06-24 10:11:56] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:11:59] DONE 258/385: celltype=DC, leave_out=Pool138_18, global_p=0.00899, elapsed=0.09 min
    total=7824, sanity=7824, nan=7704, >0=42, <0=78, =0=0

[2026-06-24 10:11:59] Start 259/385: celltype=DC, leave_out=Pool138_19
[2026-06-24 10:12:01] Running neighbors: n_cells=7789
[2026-06-24 10:12:01] Building sample metadata
[2026-06-24 10:12:01] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:12:04] DONE 259/385: celltype=DC, leave_out=Pool138_19, global_p=0.002, elapsed=0.09 min
    total=7789, sanity=7789, nan=7454, >0=64, <0=271, =0=0

[2026-06-24 10:12:05] Start 260/385: celltype=DC, leave_out=Pool138_20
[2026-06-24 10:12:07] Running neighbors: n_cells=7807
[2026-06-24 10:12:07] Building sample metadata
[2026-06-24 10:12:07] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:12:10] DONE 260/385: celltype=DC, leave_out=Pool138_20, global_p=0.002, elapsed=0.09 min
    total=7807, sanity=7807, nan=7450, >0=64, <0=293, =0=0

[2026-06-24 10:12:10] Start 261/385: celltype=DC, leave_out=Pool138_21
[2026-06-24 10:12:12] Running neighbors: n_cells=7759
[2026-06-24 10:12:13] Building sample metadata
[2026-06-24 10:12:13] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:12:16] DONE 261/385: celltype=DC, leave_out=Pool138_21, global_p=0.002, elapsed=0.09 min
    total=7759, sanity=7759, nan=7456, >0=55, <0=248, =0=0

[2026-06-24 10:12:16] Start 262/385: celltype=DC, leave_out=Pool138_22
[2026-06-24 10:12:18] Running neighbors: n_cells=7841
[2026-06-24 10:12:18] Building sample metadata
[2026-06-24 10:12:18] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:12:21] DONE 262/385: celltype=DC, leave_out=Pool138_22, global_p=0.00599, elapsed=0.09 min
    total=7841, sanity=7841, nan=7724, >0=37, <0=80, =0=0

[2026-06-24 10:12:22] Start 263/385: celltype=DC, leave_out=Pool138_23
[2026-06-24 10:12:24] Running neighbors: n_cells=7779
[2026-06-24 10:12:24] Building sample metadata
[2026-06-24 10:12:24] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:12:27] DONE 263/385: celltype=DC, leave_out=Pool138_23, global_p=0.002, elapsed=0.09 min
    total=7779, sanity=7779, nan=7512, >0=59, <0=208, =0=0

[2026-06-24 10:12:27] Start 264/385: celltype=DC, leave_out=Pool138_24
[2026-06-24 10:12:29] Running neighbors: n_cells=7832
[2026-06-24 10:12:30] Building sample metadata
[2026-06-24 10:12:30] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:12:33] DONE 264/385: celltype=DC, leave_out=Pool138_24, global_p=0.004, elapsed=0.09 min
    total=7832, sanity=7832, nan=7598, >0=53, <0=181, =0=0

[2026-06-24 10:12:33] Start 265/385: celltype=DC, leave_out=Pool138_25
[2026-06-24 10:12:35] Running neighbors: n_cells=7832
[2026-06-24 10:12:35] Building sample metadata
[2026-06-24 10:12:35] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:12:38] DONE 265/385: celltype=DC, leave_out=Pool138_25, global_p=0.003, elapsed=0.09 min
    total=7832, sanity=7832, nan=7668, >0=41, <0=123, =0=0

[2026-06-24 10:12:39] Start 266/385: celltype=DC, leave_out=Pool138_26
[2026-06-24 10:12:41] Running neighbors: n_cells=7843
[2026-06-24 10:12:41] Building sample metadata
[2026-06-24 10:12:41] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:12:44] DONE 266/385: celltype=DC, leave_out=Pool138_26, global_p=0.003, elapsed=0.09 min
    total=7843, sanity=7843, nan=7546, >0=58, <0=239, =0=0

[2026-06-24 10:12:44] Start 267/385: celltype=DC, leave_out=Pool138_27
[2026-06-24 10:12:46] Running neighbors: n_cells=7797
[2026-06-24 10:12:47] Building sample metadata
[2026-06-24 10:12:47] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:12:50] DONE 267/385: celltype=DC, leave_out=Pool138_27, global_p=0.000999, elapsed=0.09 min
    total=7797, sanity=7797, nan=7635, >0=39, <0=123, =0=0

[2026-06-24 10:12:50] Start 268/385: celltype=DC, leave_out=Pool138_29
[2026-06-24 10:12:52] Running neighbors: n_cells=7813
[2026-06-24 10:12:52] Building sample metadata
[2026-06-24 10:12:52] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:12:55] DONE 268/385: celltype=DC, leave_out=Pool138_29, global_p=0.002, elapsed=0.09 min
    total=7813, sanity=7813, nan=7361, >0=54, <0=398, =0=0

[2026-06-24 10:12:56] Start 269/385: celltype=DC, leave_out=Pool138_3
[2026-06-24 10:12:58] Running neighbors: n_cells=7834
[2026-06-24 10:12:58] Building sample metadata
[2026-06-24 10:12:58] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:13:01] DONE 269/385: celltype=DC, leave_out=Pool138_3, global_p=0.005, elapsed=0.09 min
    total=7834, sanity=7834, nan=7680, >0=39, <0=115, =0=0

[2026-06-24 10:13:01] Start 270/385: celltype=DC, leave_out=Pool138_4
[2026-06-24 10:13:03] Running neighbors: n_cells=7694
[2026-06-24 10:13:04] Building sample metadata
[2026-06-24 10:13:04] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:13:07] DONE 270/385: celltype=DC, leave_out=Pool138_4, global_p=0.005, elapsed=0.09 min
    total=7694, sanity=7694, nan=7694, >0=0, <0=0, =0=0

[2026-06-24 10:13:07] Start 271/385: celltype=DC, leave_out=Pool138_5
[2026-06-24 10:13:09] Running neighbors: n_cells=7720
[2026-06-24 10:13:09] Building sample metadata
[2026-06-24 10:13:09] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:13:12] DONE 271/385: celltype=DC, leave_out=Pool138_5, global_p=0.005, elapsed=0.09 min
    total=7720, sanity=7720, nan=7449, >0=51, <0=220, =0=0

[2026-06-24 10:13:13] Start 272/385: celltype=DC, leave_out=Pool138_6
[2026-06-24 10:13:15] Running neighbors: n_cells=7814
[2026-06-24 10:13:15] Building sample metadata
[2026-06-24 10:13:15] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:13:18] DONE 272/385: celltype=DC, leave_out=Pool138_6, global_p=0.00599, elapsed=0.09 min
    total=7814, sanity=7814, nan=7648, >0=41, <0=125, =0=0

[2026-06-24 10:13:18] Start 273/385: celltype=DC, leave_out=Pool138_7
[2026-06-24 10:13:20] Running neighbors: n_cells=7611
[2026-06-24 10:13:20] Building sample metadata
[2026-06-24 10:13:20] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:13:24] DONE 273/385: celltype=DC, leave_out=Pool138_7, global_p=0.005, elapsed=0.09 min
    total=7611, sanity=7611, nan=7232, >0=53, <0=326, =0=0

[2026-06-24 10:13:24] Start 274/385: celltype=DC, leave_out=Pool138_8
[2026-06-24 10:13:26] Running neighbors: n_cells=7806
[2026-06-24 10:13:26] Building sample metadata
[2026-06-24 10:13:26] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:13:29] DONE 274/385: celltype=DC, leave_out=Pool138_8, global_p=0.005, elapsed=0.09 min
    total=7806, sanity=7806, nan=7755, >0=17, <0=34, =0=0

[2026-06-24 10:13:29] Start 275/385: celltype=DC, leave_out=Pool138_9
[2026-06-24 10:13:31] Running neighbors: n_cells=7795
[2026-06-24 10:13:32] Building sample metadata
[2026-06-24 10:13:32] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\

[2026-06-24 10:13:35] DONE 275/385: celltype=DC, leave_out=Pool138_9, global_p=0.004, elapsed=0.09 min
    total=7795, sanity=7795, nan=7620, >0=40, <0=135, =0=0

[2026-06-24 10:13:35] Start 276/385: celltype=Mono, leave_out=Pool137_10
[2026-06-24 10:13:40] Running neighbors: n_cells=106659
[2026-06-24 10:13:51] Building sample metadata
[2026-06-24 10:13:51] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:14:11] DONE 276/385: celltype=Mono, leave_out=Pool137_10, global_p=0.000999, elapsed=0.59 min
    total=106659, sanity=106659, nan=84643, >0=6051, <0=15965, =0=0

[2026-06-24 10:14:11] Start 277/385: celltype=Mono, leave_out=Pool137_11
[2026-06-24 10:14:34] Running neighbors: n_cells=106842
[2026-06-24 10:14:45] Building sample metadata
[2026-06-24 10:14:45] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:15:06] DONE 277/385: celltype=Mono, leave_out=Pool137_11, global_p=0.000999, elapsed=0.91 min
    total=106842, sanity=106842, nan=85761, >0=5963, <0=15118, =0=0

[2026-06-24 10:15:06] Start 278/385: celltype=Mono, leave_out=Pool137_12
[2026-06-24 10:15:11] Running neighbors: n_cells=107011
[2026-06-24 10:15:22] Building sample metadata
[2026-06-24 10:15:22] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:15:43] DONE 278/385: celltype=Mono, leave_out=Pool137_12, global_p=0.000999, elapsed=0.61 min
    total=107011, sanity=107011, nan=83942, >0=6678, <0=16391, =0=0

[2026-06-24 10:15:43] Start 279/385: celltype=Mono, leave_out=Pool137_14
[2026-06-24 10:15:48] Running neighbors: n_cells=107350
[2026-06-24 10:15:59] Building sample metadata
[2026-06-24 10:15:59] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:16:20] DONE 279/385: celltype=Mono, leave_out=Pool137_14, global_p=0.000999, elapsed=0.61 min
    total=107350, sanity=107350, nan=85429, >0=5671, <0=16250, =0=0

[2026-06-24 10:16:20] Start 280/385: celltype=Mono, leave_out=Pool137_15
[2026-06-24 10:16:25] Running neighbors: n_cells=107784
[2026-06-24 10:16:36] Building sample metadata
[2026-06-24 10:16:36] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:16:56] DONE 280/385: celltype=Mono, leave_out=Pool137_15, global_p=0.000999, elapsed=0.61 min
    total=107784, sanity=107784, nan=84919, >0=6383, <0=16482, =0=0

[2026-06-24 10:16:56] Start 281/385: celltype=Mono, leave_out=Pool137_16
[2026-06-24 10:17:03] Running neighbors: n_cells=107181
[2026-06-24 10:17:13] Building sample metadata
[2026-06-24 10:17:13] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:17:34] DONE 281/385: celltype=Mono, leave_out=Pool137_16, global_p=0.000999, elapsed=0.62 min
    total=107181, sanity=107181, nan=86277, >0=5930, <0=14974, =0=0

[2026-06-24 10:17:34] Start 282/385: celltype=Mono, leave_out=Pool137_17
[2026-06-24 10:17:39] Running neighbors: n_cells=105688
[2026-06-24 10:17:50] Building sample metadata
[2026-06-24 10:17:50] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:18:10] DONE 282/385: celltype=Mono, leave_out=Pool137_17, global_p=0.000999, elapsed=0.60 min
    total=105688, sanity=105688, nan=86263, >0=4925, <0=14500, =0=0

[2026-06-24 10:18:10] Start 283/385: celltype=Mono, leave_out=Pool137_18
[2026-06-24 10:18:15] Running neighbors: n_cells=106253
[2026-06-24 10:18:26] Building sample metadata
[2026-06-24 10:18:26] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:18:46] DONE 283/385: celltype=Mono, leave_out=Pool137_18, global_p=0.000999, elapsed=0.60 min
    total=106253, sanity=106253, nan=81774, >0=6624, <0=17855, =0=0

[2026-06-24 10:18:46] Start 284/385: celltype=Mono, leave_out=Pool137_19
[2026-06-24 10:18:51] Running neighbors: n_cells=106735
[2026-06-24 10:19:02] Building sample metadata
[2026-06-24 10:19:02] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:19:23] DONE 284/385: celltype=Mono, leave_out=Pool137_19, global_p=0.000999, elapsed=0.61 min
    total=106735, sanity=106735, nan=83701, >0=6210, <0=16824, =0=0

[2026-06-24 10:19:23] Start 285/385: celltype=Mono, leave_out=Pool137_20
[2026-06-24 10:19:28] Running neighbors: n_cells=108592
[2026-06-24 10:19:39] Building sample metadata
[2026-06-24 10:19:39] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:19:59] DONE 285/385: celltype=Mono, leave_out=Pool137_20, global_p=0.000999, elapsed=0.61 min
    total=108592, sanity=108592, nan=89379, >0=5281, <0=13932, =0=0

[2026-06-24 10:19:59] Start 286/385: celltype=Mono, leave_out=Pool137_21
[2026-06-24 10:20:04] Running neighbors: n_cells=105906
[2026-06-24 10:20:15] Building sample metadata
[2026-06-24 10:20:15] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:20:35] DONE 286/385: celltype=Mono, leave_out=Pool137_21, global_p=0.000999, elapsed=0.59 min
    total=105906, sanity=105906, nan=85719, >0=5688, <0=14499, =0=0

[2026-06-24 10:20:35] Start 287/385: celltype=Mono, leave_out=Pool137_22
[2026-06-24 10:20:41] Running neighbors: n_cells=106318
[2026-06-24 10:20:52] Building sample metadata
[2026-06-24 10:20:52] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:21:12] DONE 287/385: celltype=Mono, leave_out=Pool137_22, global_p=0.000999, elapsed=0.62 min
    total=106318, sanity=106318, nan=88842, >0=4240, <0=13236, =0=0

[2026-06-24 10:21:13] Start 288/385: celltype=Mono, leave_out=Pool137_23
[2026-06-24 10:21:17] Running neighbors: n_cells=106499
[2026-06-24 10:21:28] Building sample metadata
[2026-06-24 10:21:28] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:21:48] DONE 288/385: celltype=Mono, leave_out=Pool137_23, global_p=0.000999, elapsed=0.60 min
    total=106499, sanity=106499, nan=83509, >0=6294, <0=16696, =0=0

[2026-06-24 10:21:49] Start 289/385: celltype=Mono, leave_out=Pool137_24
[2026-06-24 10:21:54] Running neighbors: n_cells=106507
[2026-06-24 10:22:04] Building sample metadata
[2026-06-24 10:22:04] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:22:25] DONE 289/385: celltype=Mono, leave_out=Pool137_24, global_p=0.000999, elapsed=0.60 min
    total=106507, sanity=106507, nan=84420, >0=5841, <0=16246, =0=0

[2026-06-24 10:22:25] Start 290/385: celltype=Mono, leave_out=Pool137_25
[2026-06-24 10:22:30] Running neighbors: n_cells=106510
[2026-06-24 10:22:41] Building sample metadata
[2026-06-24 10:22:41] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:23:01] DONE 290/385: celltype=Mono, leave_out=Pool137_25, global_p=0.000999, elapsed=0.60 min
    total=106510, sanity=106510, nan=84881, >0=5910, <0=15719, =0=0

[2026-06-24 10:23:01] Start 291/385: celltype=Mono, leave_out=Pool137_26
[2026-06-24 10:23:33] Running neighbors: n_cells=105552
[2026-06-24 10:23:44] Building sample metadata
[2026-06-24 10:23:44] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:24:23] DONE 291/385: celltype=Mono, leave_out=Pool137_26, global_p=0.000999, elapsed=1.36 min
    total=105552, sanity=105552, nan=81753, >0=6045, <0=17754, =0=0

[2026-06-24 10:24:23] Start 292/385: celltype=Mono, leave_out=Pool137_27
[2026-06-24 10:24:46] Running neighbors: n_cells=107609
[2026-06-24 10:24:57] Building sample metadata
[2026-06-24 10:24:57] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:25:28] DONE 292/385: celltype=Mono, leave_out=Pool137_27, global_p=0.000999, elapsed=1.08 min
    total=107609, sanity=107609, nan=83630, >0=6151, <0=17828, =0=0

[2026-06-24 10:25:28] Start 293/385: celltype=Mono, leave_out=Pool137_28
[2026-06-24 10:25:50] Running neighbors: n_cells=107026
[2026-06-24 10:26:01] Building sample metadata
[2026-06-24 10:26:01] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:26:24] DONE 293/385: celltype=Mono, leave_out=Pool137_28, global_p=0.000999, elapsed=0.94 min
    total=107026, sanity=107026, nan=85388, >0=6025, <0=15613, =0=0

[2026-06-24 10:26:25] Start 294/385: celltype=Mono, leave_out=Pool137_29
[2026-06-24 10:26:43] Running neighbors: n_cells=105646
[2026-06-24 10:26:54] Building sample metadata
[2026-06-24 10:26:54] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:27:16] DONE 294/385: celltype=Mono, leave_out=Pool137_29, global_p=0.000999, elapsed=0.85 min
    total=105646, sanity=105646, nan=83651, >0=6065, <0=15930, =0=0

[2026-06-24 10:27:16] Start 295/385: celltype=Mono, leave_out=Pool137_30
[2026-06-24 10:27:34] Running neighbors: n_cells=107789
[2026-06-24 10:27:45] Building sample metadata
[2026-06-24 10:27:45] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:28:06] DONE 295/385: celltype=Mono, leave_out=Pool137_30, global_p=0.000999, elapsed=0.83 min
    total=107789, sanity=107789, nan=84514, >0=6613, <0=16662, =0=0

[2026-06-24 10:28:06] Start 296/385: celltype=Mono, leave_out=Pool137_31
[2026-06-24 10:28:21] Running neighbors: n_cells=106084
[2026-06-24 10:28:32] Building sample metadata
[2026-06-24 10:28:32] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:28:52] DONE 296/385: celltype=Mono, leave_out=Pool137_31, global_p=0.000999, elapsed=0.76 min
    total=106084, sanity=106084, nan=85605, >0=5297, <0=15182, =0=0

[2026-06-24 10:28:53] Start 297/385: celltype=Mono, leave_out=Pool137_33
[2026-06-24 10:29:08] Running neighbors: n_cells=107721
[2026-06-24 10:29:20] Building sample metadata
[2026-06-24 10:29:20] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:29:40] DONE 297/385: celltype=Mono, leave_out=Pool137_33, global_p=0.000999, elapsed=0.80 min
    total=107721, sanity=107721, nan=85437, >0=7146, <0=15138, =0=0

[2026-06-24 10:29:41] Start 298/385: celltype=Mono, leave_out=Pool137_34
[2026-06-24 10:29:54] Running neighbors: n_cells=106967
[2026-06-24 10:30:05] Building sample metadata
[2026-06-24 10:30:05] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:30:25] DONE 298/385: celltype=Mono, leave_out=Pool137_34, global_p=0.000999, elapsed=0.74 min
    total=106967, sanity=106967, nan=85516, >0=5243, <0=16208, =0=0

[2026-06-24 10:30:26] Start 299/385: celltype=Mono, leave_out=Pool137_35
[2026-06-24 10:30:36] Running neighbors: n_cells=105997
[2026-06-24 10:30:47] Building sample metadata
[2026-06-24 10:30:47] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:31:08] DONE 299/385: celltype=Mono, leave_out=Pool137_35, global_p=0.000999, elapsed=0.70 min
    total=105997, sanity=105997, nan=87200, >0=4009, <0=14788, =0=0

[2026-06-24 10:31:08] Start 300/385: celltype=Mono, leave_out=Pool137_36
[2026-06-24 10:31:19] Running neighbors: n_cells=106995
[2026-06-24 10:31:30] Building sample metadata
[2026-06-24 10:31:30] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:31:51] DONE 300/385: celltype=Mono, leave_out=Pool137_36, global_p=0.000999, elapsed=0.71 min
    total=106995, sanity=106995, nan=91277, >0=3843, <0=11875, =0=0

[2026-06-24 10:31:51] Start 301/385: celltype=Mono, leave_out=Pool137_6
[2026-06-24 10:32:02] Running neighbors: n_cells=107055
[2026-06-24 10:32:13] Building sample metadata
[2026-06-24 10:32:13] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:32:34] DONE 301/385: celltype=Mono, leave_out=Pool137_6, global_p=0.000999, elapsed=0.71 min
    total=107055, sanity=107055, nan=84852, >0=6023, <0=16180, =0=0

[2026-06-24 10:32:34] Start 302/385: celltype=Mono, leave_out=Pool137_7
[2026-06-24 10:32:45] Running neighbors: n_cells=107410
[2026-06-24 10:32:56] Building sample metadata
[2026-06-24 10:32:56] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:33:16] DONE 302/385: celltype=Mono, leave_out=Pool137_7, global_p=0.000999, elapsed=0.71 min
    total=107410, sanity=107410, nan=84912, >0=6562, <0=15936, =0=0

[2026-06-24 10:33:17] Start 303/385: celltype=Mono, leave_out=Pool137_8
[2026-06-24 10:33:22] Running neighbors: n_cells=107735
[2026-06-24 10:33:33] Building sample metadata
[2026-06-24 10:33:33] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:33:54] DONE 303/385: celltype=Mono, leave_out=Pool137_8, global_p=0.000999, elapsed=0.62 min
    total=107735, sanity=107735, nan=84709, >0=6613, <0=16413, =0=0

[2026-06-24 10:33:54] Start 304/385: celltype=Mono, leave_out=Pool137_9
[2026-06-24 10:33:59] Running neighbors: n_cells=107697
[2026-06-24 10:34:11] Building sample metadata
[2026-06-24 10:34:11] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:34:35] DONE 304/385: celltype=Mono, leave_out=Pool137_9, global_p=0.000999, elapsed=0.69 min
    total=107697, sanity=107697, nan=85370, >0=6062, <0=16265, =0=0

[2026-06-24 10:34:36] Start 305/385: celltype=Mono, leave_out=Pool138_10
[2026-06-24 10:34:41] Running neighbors: n_cells=106706
[2026-06-24 10:34:51] Building sample metadata
[2026-06-24 10:34:51] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:35:12] DONE 305/385: celltype=Mono, leave_out=Pool138_10, global_p=0.000999, elapsed=0.61 min
    total=106706, sanity=106706, nan=84873, >0=5917, <0=15916, =0=0

[2026-06-24 10:35:12] Start 306/385: celltype=Mono, leave_out=Pool138_11
[2026-06-24 10:35:17] Running neighbors: n_cells=106920
[2026-06-24 10:35:29] Building sample metadata
[2026-06-24 10:35:29] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:35:49] DONE 306/385: celltype=Mono, leave_out=Pool138_11, global_p=0.000999, elapsed=0.61 min
    total=106920, sanity=106920, nan=84284, >0=6584, <0=16052, =0=0

[2026-06-24 10:35:50] Start 307/385: celltype=Mono, leave_out=Pool138_12
[2026-06-24 10:35:54] Running neighbors: n_cells=105567
[2026-06-24 10:36:05] Building sample metadata
[2026-06-24 10:36:05] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:36:26] DONE 307/385: celltype=Mono, leave_out=Pool138_12, global_p=0.000999, elapsed=0.61 min
    total=105567, sanity=105567, nan=84227, >0=5883, <0=15457, =0=0

[2026-06-24 10:36:26] Start 308/385: celltype=Mono, leave_out=Pool138_13
[2026-06-24 10:36:31] Running neighbors: n_cells=106344
[2026-06-24 10:36:43] Building sample metadata
[2026-06-24 10:36:43] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:37:03] DONE 308/385: celltype=Mono, leave_out=Pool138_13, global_p=0.000999, elapsed=0.61 min
    total=106344, sanity=106344, nan=83182, >0=6802, <0=16360, =0=0

[2026-06-24 10:37:03] Start 309/385: celltype=Mono, leave_out=Pool138_14
[2026-06-24 10:37:08] Running neighbors: n_cells=106263
[2026-06-24 10:37:19] Building sample metadata
[2026-06-24 10:37:19] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:37:40] DONE 309/385: celltype=Mono, leave_out=Pool138_14, global_p=0.000999, elapsed=0.61 min
    total=106263, sanity=106263, nan=83234, >0=5709, <0=17320, =0=0

[2026-06-24 10:37:40] Start 310/385: celltype=Mono, leave_out=Pool138_15
[2026-06-24 10:37:45] Running neighbors: n_cells=105206
[2026-06-24 10:37:56] Building sample metadata
[2026-06-24 10:37:56] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:38:17] DONE 310/385: celltype=Mono, leave_out=Pool138_15, global_p=0.000999, elapsed=0.62 min
    total=105206, sanity=105206, nan=82340, >0=6311, <0=16555, =0=0

[2026-06-24 10:38:18] Start 311/385: celltype=Mono, leave_out=Pool138_16
[2026-06-24 10:38:23] Running neighbors: n_cells=106902
[2026-06-24 10:38:34] Building sample metadata
[2026-06-24 10:38:34] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:38:54] DONE 311/385: celltype=Mono, leave_out=Pool138_16, global_p=0.000999, elapsed=0.61 min
    total=106902, sanity=106902, nan=83917, >0=6401, <0=16584, =0=0

[2026-06-24 10:38:54] Start 312/385: celltype=Mono, leave_out=Pool138_17
[2026-06-24 10:38:59] Running neighbors: n_cells=108595
[2026-06-24 10:39:10] Building sample metadata
[2026-06-24 10:39:10] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:39:31] DONE 312/385: celltype=Mono, leave_out=Pool138_17, global_p=0.000999, elapsed=0.62 min
    total=108595, sanity=108595, nan=85244, >0=6666, <0=16685, =0=0

[2026-06-24 10:39:32] Start 313/385: celltype=Mono, leave_out=Pool138_18
[2026-06-24 10:39:37] Running neighbors: n_cells=108076
[2026-06-24 10:39:47] Building sample metadata
[2026-06-24 10:39:47] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:40:08] DONE 313/385: celltype=Mono, leave_out=Pool138_18, global_p=0.000999, elapsed=0.60 min
    total=108076, sanity=108076, nan=87145, >0=6483, <0=14448, =0=0

[2026-06-24 10:40:08] Start 314/385: celltype=Mono, leave_out=Pool138_19
[2026-06-24 10:40:13] Running neighbors: n_cells=107263
[2026-06-24 10:40:23] Building sample metadata
[2026-06-24 10:40:23] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:40:44] DONE 314/385: celltype=Mono, leave_out=Pool138_19, global_p=0.000999, elapsed=0.60 min
    total=107263, sanity=107263, nan=82494, >0=7353, <0=17416, =0=0

[2026-06-24 10:40:44] Start 315/385: celltype=Mono, leave_out=Pool138_20
[2026-06-24 10:40:49] Running neighbors: n_cells=107034
[2026-06-24 10:41:00] Building sample metadata
[2026-06-24 10:41:00] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:41:20] DONE 315/385: celltype=Mono, leave_out=Pool138_20, global_p=0.000999, elapsed=0.60 min
    total=107034, sanity=107034, nan=83508, >0=6718, <0=16808, =0=0

[2026-06-24 10:41:20] Start 316/385: celltype=Mono, leave_out=Pool138_21
[2026-06-24 10:41:25] Running neighbors: n_cells=107476
[2026-06-24 10:41:36] Building sample metadata
[2026-06-24 10:41:36] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:41:56] DONE 316/385: celltype=Mono, leave_out=Pool138_21, global_p=0.000999, elapsed=0.60 min
    total=107476, sanity=107476, nan=84510, >0=6121, <0=16845, =0=0

[2026-06-24 10:41:57] Start 317/385: celltype=Mono, leave_out=Pool138_22
[2026-06-24 10:42:01] Running neighbors: n_cells=107940
[2026-06-24 10:42:12] Building sample metadata
[2026-06-24 10:42:12] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:42:33] DONE 317/385: celltype=Mono, leave_out=Pool138_22, global_p=0.000999, elapsed=0.60 min
    total=107940, sanity=107940, nan=87278, >0=5969, <0=14693, =0=0

[2026-06-24 10:42:33] Start 318/385: celltype=Mono, leave_out=Pool138_23
[2026-06-24 10:42:38] Running neighbors: n_cells=107138
[2026-06-24 10:42:48] Building sample metadata
[2026-06-24 10:42:48] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:43:09] DONE 318/385: celltype=Mono, leave_out=Pool138_23, global_p=0.000999, elapsed=0.60 min
    total=107138, sanity=107138, nan=86073, >0=5871, <0=15194, =0=0

[2026-06-24 10:43:09] Start 319/385: celltype=Mono, leave_out=Pool138_24
[2026-06-24 10:43:14] Running neighbors: n_cells=107718
[2026-06-24 10:43:25] Building sample metadata
[2026-06-24 10:43:25] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:43:45] DONE 319/385: celltype=Mono, leave_out=Pool138_24, global_p=0.000999, elapsed=0.60 min
    total=107718, sanity=107718, nan=85959, >0=5783, <0=15976, =0=0

[2026-06-24 10:43:45] Start 320/385: celltype=Mono, leave_out=Pool138_25
[2026-06-24 10:43:50] Running neighbors: n_cells=106616
[2026-06-24 10:44:01] Building sample metadata
[2026-06-24 10:44:01] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:44:22] DONE 320/385: celltype=Mono, leave_out=Pool138_25, global_p=0.000999, elapsed=0.61 min
    total=106616, sanity=106616, nan=85535, >0=6413, <0=14668, =0=0

[2026-06-24 10:44:22] Start 321/385: celltype=Mono, leave_out=Pool138_26
[2026-06-24 10:44:27] Running neighbors: n_cells=106173
[2026-06-24 10:44:37] Building sample metadata
[2026-06-24 10:44:37] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:44:58] DONE 321/385: celltype=Mono, leave_out=Pool138_26, global_p=0.000999, elapsed=0.60 min
    total=106173, sanity=106173, nan=83097, >0=6607, <0=16469, =0=0

[2026-06-24 10:44:58] Start 322/385: celltype=Mono, leave_out=Pool138_27
[2026-06-24 10:45:03] Running neighbors: n_cells=106843
[2026-06-24 10:45:13] Building sample metadata
[2026-06-24 10:45:13] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:45:34] DONE 322/385: celltype=Mono, leave_out=Pool138_27, global_p=0.000999, elapsed=0.60 min
    total=106843, sanity=106843, nan=85659, >0=6261, <0=14923, =0=0

[2026-06-24 10:45:34] Start 323/385: celltype=Mono, leave_out=Pool138_29
[2026-06-24 10:45:39] Running neighbors: n_cells=108257
[2026-06-24 10:45:50] Building sample metadata
[2026-06-24 10:45:50] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:46:10] DONE 323/385: celltype=Mono, leave_out=Pool138_29, global_p=0.000999, elapsed=0.60 min
    total=108257, sanity=108257, nan=87981, >0=5580, <0=14696, =0=0

[2026-06-24 10:46:11] Start 324/385: celltype=Mono, leave_out=Pool138_3
[2026-06-24 10:46:16] Running neighbors: n_cells=107219
[2026-06-24 10:46:26] Building sample metadata
[2026-06-24 10:46:26] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:46:46] DONE 324/385: celltype=Mono, leave_out=Pool138_3, global_p=0.000999, elapsed=0.60 min
    total=107219, sanity=107219, nan=88959, >0=5030, <0=13230, =0=0

[2026-06-24 10:46:47] Start 325/385: celltype=Mono, leave_out=Pool138_4
[2026-06-24 10:47:07] Running neighbors: n_cells=106610
[2026-06-24 10:47:18] Building sample metadata
[2026-06-24 10:47:18] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:47:38] DONE 325/385: celltype=Mono, leave_out=Pool138_4, global_p=0.000999, elapsed=0.86 min
    total=106610, sanity=106610, nan=87744, >0=4931, <0=13935, =0=0

[2026-06-24 10:47:38] Start 326/385: celltype=Mono, leave_out=Pool138_5
[2026-06-24 10:47:45] Running neighbors: n_cells=106525
[2026-06-24 10:47:56] Building sample metadata
[2026-06-24 10:47:56] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:48:16] DONE 326/385: celltype=Mono, leave_out=Pool138_5, global_p=0.000999, elapsed=0.62 min
    total=106525, sanity=106525, nan=84247, >0=6141, <0=16137, =0=0

[2026-06-24 10:48:16] Start 327/385: celltype=Mono, leave_out=Pool138_6
[2026-06-24 10:48:21] Running neighbors: n_cells=106771
[2026-06-24 10:48:32] Building sample metadata
[2026-06-24 10:48:32] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:48:52] DONE 327/385: celltype=Mono, leave_out=Pool138_6, global_p=0.000999, elapsed=0.60 min
    total=106771, sanity=106771, nan=86096, >0=5658, <0=15017, =0=0

[2026-06-24 10:48:52] Start 328/385: celltype=Mono, leave_out=Pool138_7
[2026-06-24 10:49:08] Running neighbors: n_cells=105673
[2026-06-24 10:49:18] Building sample metadata
[2026-06-24 10:49:18] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:49:38] DONE 328/385: celltype=Mono, leave_out=Pool138_7, global_p=0.000999, elapsed=0.77 min
    total=105673, sanity=105673, nan=85760, >0=4897, <0=15016, =0=0

[2026-06-24 10:49:39] Start 329/385: celltype=Mono, leave_out=Pool138_8
[2026-06-24 10:49:44] Running neighbors: n_cells=106260
[2026-06-24 10:49:55] Building sample metadata
[2026-06-24 10:49:55] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:50:15] DONE 329/385: celltype=Mono, leave_out=Pool138_8, global_p=0.000999, elapsed=0.61 min
    total=106260, sanity=106260, nan=86378, >0=5889, <0=13993, =0=0

[2026-06-24 10:50:16] Start 330/385: celltype=Mono, leave_out=Pool138_9
[2026-06-24 10:50:22] Running neighbors: n_cells=107443
[2026-06-24 10:50:33] Building sample metadata
[2026-06-24 10:50:33] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:66: UserWarning: data supported use of 4 NAM PCs, which is the maximum considered. Consider allowing more PCs by using the "ks" argument.
  warnings.warn(('data supported use of {} NAM PCs, which is the maximum considered. '+\
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_association.py:87: UserWarning: global association p-value attained minimal possible value. Consider increasing Nnull
  warnings.warn('global association p-value attained minimal possible value. '+\

[2026-06-24 10:50:58] DONE 330/385: celltype=Mono, leave_out=Pool138_9, global_p=0.000999, elapsed=0.70 min
    total=107443, sanity=107443, nan=89047, >0=4783, <0=13613, =0=0

[2026-06-24 10:50:58] Start 331/385: celltype=NK, leave_out=Pool137_10
[2026-06-24 10:51:00] Running neighbors: n_cells=35641
[2026-06-24 10:51:04] Building sample metadata
[2026-06-24 10:51:04] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:51:12] DONE 331/385: celltype=NK, leave_out=Pool137_10, global_p=0.385, elapsed=0.24 min
    total=35641, sanity=35641, nan=35641, >0=0, <0=0, =0=0

[2026-06-24 10:51:12] Start 332/385: celltype=NK, leave_out=Pool137_11
[2026-06-24 10:51:15] Running neighbors: n_cells=36223
[2026-06-24 10:51:19] Building sample metadata
[2026-06-24 10:51:19] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([

[2026-06-24 10:51:27] DONE 332/385: celltype=NK, leave_out=Pool137_11, global_p=0.268, elapsed=0.24 min
    total=36223, sanity=36223, nan=36223, >0=0, <0=0, =0=0

[2026-06-24 10:51:27] Start 333/385: celltype=NK, leave_out=Pool137_12
[2026-06-24 10:51:29] Running neighbors: n_cells=36293
[2026-06-24 10:51:33] Building sample metadata
[2026-06-24 10:51:33] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:51:41] DONE 333/385: celltype=NK, leave_out=Pool137_12, global_p=0.364, elapsed=0.24 min
    total=36293, sanity=36293, nan=36293, >0=0, <0=0, =0=0

[2026-06-24 10:51:41] Start 334/385: celltype=NK, leave_out=Pool137_14
[2026-06-24 10:51:44] Running neighbors: n_cells=35513
[2026-06-24 10:51:48] Building sample metadata
[2026-06-24 10:51:48] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:51:56] DONE 334/385: celltype=NK, leave_out=Pool137_14, global_p=0.363, elapsed=0.24 min
    total=35513, sanity=35513, nan=35511, >0=0, <0=2, =0=0

[2026-06-24 10:51:56] Start 335/385: celltype=NK, leave_out=Pool137_15
[2026-06-24 10:51:58] Running neighbors: n_cells=36436
[2026-06-24 10:52:02] Building sample metadata
[2026-06-24 10:52:02] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:52:10] DONE 335/385: celltype=NK, leave_out=Pool137_15, global_p=0.345, elapsed=0.24 min
    total=36436, sanity=36436, nan=36436, >0=0, <0=0, =0=0

[2026-06-24 10:52:10] Start 336/385: celltype=NK, leave_out=Pool137_16
[2026-06-24 10:52:13] Running neighbors: n_cells=36280
[2026-06-24 10:52:16] Building sample metadata
[2026-06-24 10:52:16] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:52:24] DONE 336/385: celltype=NK, leave_out=Pool137_16, global_p=0.362, elapsed=0.24 min
    total=36280, sanity=36280, nan=36280, >0=0, <0=0, =0=0

[2026-06-24 10:52:25] Start 337/385: celltype=NK, leave_out=Pool137_17
[2026-06-24 10:52:27] Running neighbors: n_cells=35827
[2026-06-24 10:52:31] Building sample metadata
[2026-06-24 10:52:31] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:52:39] DONE 337/385: celltype=NK, leave_out=Pool137_17, global_p=0.315, elapsed=0.24 min
    total=35827, sanity=35827, nan=35827, >0=0, <0=0, =0=0

[2026-06-24 10:52:39] Start 338/385: celltype=NK, leave_out=Pool137_18
[2026-06-24 10:52:41] Running neighbors: n_cells=35519
[2026-06-24 10:52:45] Building sample metadata
[2026-06-24 10:52:45] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([

[2026-06-24 10:52:53] DONE 338/385: celltype=NK, leave_out=Pool137_18, global_p=0.333, elapsed=0.23 min
    total=35519, sanity=35519, nan=35519, >0=0, <0=0, =0=0

[2026-06-24 10:52:53] Start 339/385: celltype=NK, leave_out=Pool137_19
[2026-06-24 10:52:56] Running neighbors: n_cells=34642
[2026-06-24 10:52:59] Building sample metadata
[2026-06-24 10:52:59] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:53:07] DONE 339/385: celltype=NK, leave_out=Pool137_19, global_p=0.315, elapsed=0.23 min
    total=34642, sanity=34642, nan=34642, >0=0, <0=0, =0=0

[2026-06-24 10:53:07] Start 340/385: celltype=NK, leave_out=Pool137_20
[2026-06-24 10:53:10] Running neighbors: n_cells=36625
[2026-06-24 10:53:14] Building sample metadata
[2026-06-24 10:53:14] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:53:22] DONE 340/385: celltype=NK, leave_out=Pool137_20, global_p=0.574, elapsed=0.24 min
    total=36625, sanity=36625, nan=36625, >0=0, <0=0, =0=0

[2026-06-24 10:53:22] Start 341/385: celltype=NK, leave_out=Pool137_21
[2026-06-24 10:53:24] Running neighbors: n_cells=35532
[2026-06-24 10:53:28] Building sample metadata
[2026-06-24 10:53:28] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([

[2026-06-24 10:53:36] DONE 341/385: celltype=NK, leave_out=Pool137_21, global_p=0.431, elapsed=0.23 min
    total=35532, sanity=35532, nan=35532, >0=0, <0=0, =0=0

[2026-06-24 10:53:36] Start 342/385: celltype=NK, leave_out=Pool137_22
[2026-06-24 10:53:39] Running neighbors: n_cells=35353
[2026-06-24 10:53:42] Building sample metadata
[2026-06-24 10:53:42] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:53:50] DONE 342/385: celltype=NK, leave_out=Pool137_22, global_p=0.266, elapsed=0.23 min
    total=35353, sanity=35353, nan=35353, >0=0, <0=0, =0=0

[2026-06-24 10:53:50] Start 343/385: celltype=NK, leave_out=Pool137_23
[2026-06-24 10:53:53] Running neighbors: n_cells=36595
[2026-06-24 10:53:57] Building sample metadata
[2026-06-24 10:53:57] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:54:05] DONE 343/385: celltype=NK, leave_out=Pool137_23, global_p=0.334, elapsed=0.24 min
    total=36595, sanity=36595, nan=36595, >0=0, <0=0, =0=0

[2026-06-24 10:54:05] Start 344/385: celltype=NK, leave_out=Pool137_24
[2026-06-24 10:54:07] Running neighbors: n_cells=35796
[2026-06-24 10:54:11] Building sample metadata
[2026-06-24 10:54:11] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:54:19] DONE 344/385: celltype=NK, leave_out=Pool137_24, global_p=0.344, elapsed=0.24 min
    total=35796, sanity=35796, nan=35796, >0=0, <0=0, =0=0

[2026-06-24 10:54:19] Start 345/385: celltype=NK, leave_out=Pool137_25
[2026-06-24 10:54:22] Running neighbors: n_cells=36469
[2026-06-24 10:54:26] Building sample metadata
[2026-06-24 10:54:26] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:54:34] DONE 345/385: celltype=NK, leave_out=Pool137_25, global_p=0.333, elapsed=0.24 min
    total=36469, sanity=36469, nan=36469, >0=0, <0=0, =0=0

[2026-06-24 10:54:34] Start 346/385: celltype=NK, leave_out=Pool137_26
[2026-06-24 10:54:37] Running neighbors: n_cells=36005
[2026-06-24 10:54:40] Building sample metadata
[2026-06-24 10:54:40] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:54:48] DONE 346/385: celltype=NK, leave_out=Pool137_26, global_p=0.312, elapsed=0.24 min
    total=36005, sanity=36005, nan=36005, >0=0, <0=0, =0=0

[2026-06-24 10:54:48] Start 347/385: celltype=NK, leave_out=Pool137_27
[2026-06-24 10:54:51] Running neighbors: n_cells=36429
[2026-06-24 10:54:55] Building sample metadata
[2026-06-24 10:54:55] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:55:03] DONE 347/385: celltype=NK, leave_out=Pool137_27, global_p=0.416, elapsed=0.24 min
    total=36429, sanity=36429, nan=36429, >0=0, <0=0, =0=0

[2026-06-24 10:55:03] Start 348/385: celltype=NK, leave_out=Pool137_28
[2026-06-24 10:55:06] Running neighbors: n_cells=36008
[2026-06-24 10:55:09] Building sample metadata
[2026-06-24 10:55:09] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([

[2026-06-24 10:55:17] DONE 348/385: celltype=NK, leave_out=Pool137_28, global_p=0.333, elapsed=0.24 min
    total=36008, sanity=36008, nan=36008, >0=0, <0=0, =0=0

[2026-06-24 10:55:17] Start 349/385: celltype=NK, leave_out=Pool137_29
[2026-06-24 10:55:20] Running neighbors: n_cells=36315
[2026-06-24 10:55:24] Building sample metadata
[2026-06-24 10:55:24] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:55:32] DONE 349/385: celltype=NK, leave_out=Pool137_29, global_p=0.361, elapsed=0.24 min
    total=36315, sanity=36315, nan=36315, >0=0, <0=0, =0=0

[2026-06-24 10:55:32] Start 350/385: celltype=NK, leave_out=Pool137_30
[2026-06-24 10:55:35] Running neighbors: n_cells=35622
[2026-06-24 10:55:38] Building sample metadata
[2026-06-24 10:55:38] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:55:46] DONE 350/385: celltype=NK, leave_out=Pool137_30, global_p=0.325, elapsed=0.23 min
    total=35622, sanity=35622, nan=35622, >0=0, <0=0, =0=0

[2026-06-24 10:55:46] Start 351/385: celltype=NK, leave_out=Pool137_31
[2026-06-24 10:55:49] Running neighbors: n_cells=36311
[2026-06-24 10:55:53] Building sample metadata
[2026-06-24 10:55:53] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([

[2026-06-24 10:56:01] DONE 351/385: celltype=NK, leave_out=Pool137_31, global_p=0.372, elapsed=0.24 min
    total=36311, sanity=36311, nan=36311, >0=0, <0=0, =0=0

[2026-06-24 10:56:01] Start 352/385: celltype=NK, leave_out=Pool137_33
[2026-06-24 10:56:03] Running neighbors: n_cells=35623
[2026-06-24 10:56:07] Building sample metadata
[2026-06-24 10:56:07] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:56:15] DONE 352/385: celltype=NK, leave_out=Pool137_33, global_p=0.352, elapsed=0.23 min
    total=35623, sanity=35623, nan=35623, >0=0, <0=0, =0=0

[2026-06-24 10:56:15] Start 353/385: celltype=NK, leave_out=Pool137_34
[2026-06-24 10:56:18] Running neighbors: n_cells=35876
[2026-06-24 10:56:21] Building sample metadata
[2026-06-24 10:56:21] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:56:29] DONE 353/385: celltype=NK, leave_out=Pool137_34, global_p=0.204, elapsed=0.24 min
    total=35876, sanity=35876, nan=35876, >0=0, <0=0, =0=0

[2026-06-24 10:56:30] Start 354/385: celltype=NK, leave_out=Pool137_35
[2026-06-24 10:56:32] Running neighbors: n_cells=35831
[2026-06-24 10:56:36] Building sample metadata
[2026-06-24 10:56:36] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:56:44] DONE 354/385: celltype=NK, leave_out=Pool137_35, global_p=0.352, elapsed=0.24 min
    total=35831, sanity=35831, nan=35831, >0=0, <0=0, =0=0

[2026-06-24 10:56:44] Start 355/385: celltype=NK, leave_out=Pool137_36
[2026-06-24 10:56:47] Running neighbors: n_cells=35843
[2026-06-24 10:56:50] Building sample metadata
[2026-06-24 10:56:50] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:56:58] DONE 355/385: celltype=NK, leave_out=Pool137_36, global_p=0.301, elapsed=0.24 min
    total=35843, sanity=35843, nan=35843, >0=0, <0=0, =0=0

[2026-06-24 10:56:58] Start 356/385: celltype=NK, leave_out=Pool137_6
[2026-06-24 10:57:01] Running neighbors: n_cells=36123
[2026-06-24 10:57:05] Building sample metadata
[2026-06-24 10:57:05] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:57:13] DONE 356/385: celltype=NK, leave_out=Pool137_6, global_p=0.364, elapsed=0.24 min
    total=36123, sanity=36123, nan=36123, >0=0, <0=0, =0=0

[2026-06-24 10:57:13] Start 357/385: celltype=NK, leave_out=Pool137_7
[2026-06-24 10:57:15] Running neighbors: n_cells=35908
[2026-06-24 10:57:19] Building sample metadata
[2026-06-24 10:57:19] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:57:27] DONE 357/385: celltype=NK, leave_out=Pool137_7, global_p=0.308, elapsed=0.24 min
    total=35908, sanity=35908, nan=35908, >0=0, <0=0, =0=0

[2026-06-24 10:57:27] Start 358/385: celltype=NK, leave_out=Pool137_8
[2026-06-24 10:57:30] Running neighbors: n_cells=36290
[2026-06-24 10:57:34] Building sample metadata
[2026-06-24 10:57:34] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:57:42] DONE 358/385: celltype=NK, leave_out=Pool137_8, global_p=0.354, elapsed=0.24 min
    total=36290, sanity=36290, nan=36290, >0=0, <0=0, =0=0

[2026-06-24 10:57:42] Start 359/385: celltype=NK, leave_out=Pool137_9
[2026-06-24 10:57:44] Running neighbors: n_cells=35972
[2026-06-24 10:57:48] Building sample metadata
[2026-06-24 10:57:48] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:57:56] DONE 359/385: celltype=NK, leave_out=Pool137_9, global_p=0.373, elapsed=0.24 min
    total=35972, sanity=35972, nan=35972, >0=0, <0=0, =0=0

[2026-06-24 10:57:56] Start 360/385: celltype=NK, leave_out=Pool138_10
[2026-06-24 10:57:59] Running neighbors: n_cells=36149
[2026-06-24 10:58:03] Building sample metadata
[2026-06-24 10:58:03] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:58:11] DONE 360/385: celltype=NK, leave_out=Pool138_10, global_p=0.26, elapsed=0.24 min
    total=36149, sanity=36149, nan=36149, >0=0, <0=0, =0=0

[2026-06-24 10:58:11] Start 361/385: celltype=NK, leave_out=Pool138_11
[2026-06-24 10:58:13] Running neighbors: n_cells=35959
[2026-06-24 10:58:17] Building sample metadata
[2026-06-24 10:58:17] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:58:25] DONE 361/385: celltype=NK, leave_out=Pool138_11, global_p=0.388, elapsed=0.24 min
    total=35959, sanity=35959, nan=35959, >0=0, <0=0, =0=0

[2026-06-24 10:58:25] Start 362/385: celltype=NK, leave_out=Pool138_12
[2026-06-24 10:58:28] Running neighbors: n_cells=35727
[2026-06-24 10:58:31] Building sample metadata
[2026-06-24 10:58:31] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:58:39] DONE 362/385: celltype=NK, leave_out=Pool138_12, global_p=0.404, elapsed=0.24 min
    total=35727, sanity=35727, nan=35727, >0=0, <0=0, =0=0

[2026-06-24 10:58:40] Start 363/385: celltype=NK, leave_out=Pool138_13
[2026-06-24 10:58:42] Running neighbors: n_cells=36217
[2026-06-24 10:58:46] Building sample metadata
[2026-06-24 10:58:46] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([

[2026-06-24 10:58:54] DONE 363/385: celltype=NK, leave_out=Pool138_13, global_p=0.387, elapsed=0.24 min
    total=36217, sanity=36217, nan=36217, >0=0, <0=0, =0=0

[2026-06-24 10:58:54] Start 364/385: celltype=NK, leave_out=Pool138_14
[2026-06-24 10:58:57] Running neighbors: n_cells=36000
[2026-06-24 10:59:00] Building sample metadata
[2026-06-24 10:59:00] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:59:08] DONE 364/385: celltype=NK, leave_out=Pool138_14, global_p=0.273, elapsed=0.24 min
    total=36000, sanity=36000, nan=36000, >0=0, <0=0, =0=0

[2026-06-24 10:59:09] Start 365/385: celltype=NK, leave_out=Pool138_15
[2026-06-24 10:59:11] Running neighbors: n_cells=36096
[2026-06-24 10:59:15] Building sample metadata
[2026-06-24 10:59:15] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:59:23] DONE 365/385: celltype=NK, leave_out=Pool138_15, global_p=0.233, elapsed=0.24 min
    total=36096, sanity=36096, nan=36096, >0=0, <0=0, =0=0

[2026-06-24 10:59:23] Start 366/385: celltype=NK, leave_out=Pool138_16
[2026-06-24 10:59:26] Running neighbors: n_cells=36309
[2026-06-24 10:59:29] Building sample metadata
[2026-06-24 10:59:29] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:59:37] DONE 366/385: celltype=NK, leave_out=Pool138_16, global_p=0.365, elapsed=0.24 min
    total=36309, sanity=36309, nan=36309, >0=0, <0=0, =0=0

[2026-06-24 10:59:38] Start 367/385: celltype=NK, leave_out=Pool138_17
[2026-06-24 10:59:40] Running neighbors: n_cells=36365
[2026-06-24 10:59:44] Building sample metadata
[2026-06-24 10:59:44] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 10:59:52] DONE 367/385: celltype=NK, leave_out=Pool138_17, global_p=0.226, elapsed=0.24 min
    total=36365, sanity=36365, nan=36365, >0=0, <0=0, =0=0

[2026-06-24 10:59:52] Start 368/385: celltype=NK, leave_out=Pool138_18
[2026-06-24 10:59:55] Running neighbors: n_cells=36257
[2026-06-24 10:59:58] Building sample metadata
[2026-06-24 10:59:58] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:00:06] DONE 368/385: celltype=NK, leave_out=Pool138_18, global_p=0.169, elapsed=0.24 min
    total=36257, sanity=36257, nan=36257, >0=0, <0=0, =0=0

[2026-06-24 11:00:07] Start 369/385: celltype=NK, leave_out=Pool138_19
[2026-06-24 11:00:09] Running neighbors: n_cells=36407
[2026-06-24 11:00:13] Building sample metadata
[2026-06-24 11:00:13] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:00:21] DONE 369/385: celltype=NK, leave_out=Pool138_19, global_p=0.27, elapsed=0.24 min
    total=36407, sanity=36407, nan=36407, >0=0, <0=0, =0=0

[2026-06-24 11:00:21] Start 370/385: celltype=NK, leave_out=Pool138_20
[2026-06-24 11:00:24] Running neighbors: n_cells=35541
[2026-06-24 11:00:27] Building sample metadata
[2026-06-24 11:00:27] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:00:35] DONE 370/385: celltype=NK, leave_out=Pool138_20, global_p=0.321, elapsed=0.23 min
    total=35541, sanity=35541, nan=35541, >0=0, <0=0, =0=0

[2026-06-24 11:00:36] Start 371/385: celltype=NK, leave_out=Pool138_21
[2026-06-24 11:00:38] Running neighbors: n_cells=36297
[2026-06-24 11:00:42] Building sample metadata
[2026-06-24 11:00:42] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:00:50] DONE 371/385: celltype=NK, leave_out=Pool138_21, global_p=0.408, elapsed=0.24 min
    total=36297, sanity=36297, nan=36297, >0=0, <0=0, =0=0

[2026-06-24 11:00:50] Start 372/385: celltype=NK, leave_out=Pool138_22
[2026-06-24 11:00:52] Running neighbors: n_cells=35757
[2026-06-24 11:00:56] Building sample metadata
[2026-06-24 11:00:56] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)
/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/tools/_nam.py:79: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  return st.kurtosis(np.array([

[2026-06-24 11:01:04] DONE 372/385: celltype=NK, leave_out=Pool138_22, global_p=0.293, elapsed=0.24 min
    total=35757, sanity=35757, nan=35757, >0=0, <0=0, =0=0

[2026-06-24 11:01:04] Start 373/385: celltype=NK, leave_out=Pool138_23
[2026-06-24 11:01:07] Running neighbors: n_cells=36462
[2026-06-24 11:01:10] Building sample metadata
[2026-06-24 11:01:10] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:01:19] DONE 373/385: celltype=NK, leave_out=Pool138_23, global_p=0.328, elapsed=0.24 min
    total=36462, sanity=36462, nan=36462, >0=0, <0=0, =0=0

[2026-06-24 11:01:19] Start 374/385: celltype=NK, leave_out=Pool138_24
[2026-06-24 11:01:21] Running neighbors: n_cells=35950
[2026-06-24 11:01:25] Building sample metadata
[2026-06-24 11:01:25] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:01:33] DONE 374/385: celltype=NK, leave_out=Pool138_24, global_p=0.385, elapsed=0.24 min
    total=35950, sanity=35950, nan=35950, >0=0, <0=0, =0=0

[2026-06-24 11:01:33] Start 375/385: celltype=NK, leave_out=Pool138_25
[2026-06-24 11:01:36] Running neighbors: n_cells=36472
[2026-06-24 11:01:39] Building sample metadata
[2026-06-24 11:01:39] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:01:48] DONE 375/385: celltype=NK, leave_out=Pool138_25, global_p=0.355, elapsed=0.24 min
    total=36472, sanity=36472, nan=36472, >0=0, <0=0, =0=0

[2026-06-24 11:01:48] Start 376/385: celltype=NK, leave_out=Pool138_26
[2026-06-24 11:01:50] Running neighbors: n_cells=35681
[2026-06-24 11:01:54] Building sample metadata
[2026-06-24 11:01:54] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:02:02] DONE 376/385: celltype=NK, leave_out=Pool138_26, global_p=0.35, elapsed=0.24 min
    total=35681, sanity=35681, nan=35681, >0=0, <0=0, =0=0

[2026-06-24 11:02:02] Start 377/385: celltype=NK, leave_out=Pool138_27
[2026-06-24 11:02:05] Running neighbors: n_cells=35188
[2026-06-24 11:02:08] Building sample metadata
[2026-06-24 11:02:08] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:02:16] DONE 377/385: celltype=NK, leave_out=Pool138_27, global_p=0.486, elapsed=0.23 min
    total=35188, sanity=35188, nan=35188, >0=0, <0=0, =0=0

[2026-06-24 11:02:16] Start 378/385: celltype=NK, leave_out=Pool138_29
[2026-06-24 11:02:19] Running neighbors: n_cells=36184
[2026-06-24 11:02:23] Building sample metadata
[2026-06-24 11:02:23] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:02:30] DONE 378/385: celltype=NK, leave_out=Pool138_29, global_p=0.629, elapsed=0.23 min
    total=36184, sanity=36184, nan=36184, >0=0, <0=0, =0=0

[2026-06-24 11:02:31] Start 379/385: celltype=NK, leave_out=Pool138_3
[2026-06-24 11:02:33] Running neighbors: n_cells=36294
[2026-06-24 11:02:37] Building sample metadata
[2026-06-24 11:02:37] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:02:45] DONE 379/385: celltype=NK, leave_out=Pool138_3, global_p=0.381, elapsed=0.24 min
    total=36294, sanity=36294, nan=36294, >0=0, <0=0, =0=0

[2026-06-24 11:02:45] Start 380/385: celltype=NK, leave_out=Pool138_4
[2026-06-24 11:02:47] Running neighbors: n_cells=35904
[2026-06-24 11:02:51] Building sample metadata
[2026-06-24 11:02:51] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:02:59] DONE 380/385: celltype=NK, leave_out=Pool138_4, global_p=0.425, elapsed=0.23 min
    total=35904, sanity=35904, nan=35904, >0=0, <0=0, =0=0

[2026-06-24 11:02:59] Start 381/385: celltype=NK, leave_out=Pool138_5
[2026-06-24 11:03:02] Running neighbors: n_cells=35288
[2026-06-24 11:03:05] Building sample metadata
[2026-06-24 11:03:05] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:03:13] DONE 381/385: celltype=NK, leave_out=Pool138_5, global_p=0.383, elapsed=0.23 min
    total=35288, sanity=35288, nan=35288, >0=0, <0=0, =0=0

[2026-06-24 11:03:13] Start 382/385: celltype=NK, leave_out=Pool138_6
[2026-06-24 11:03:16] Running neighbors: n_cells=36535
[2026-06-24 11:03:20] Building sample metadata
[2026-06-24 11:03:20] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:03:28] DONE 382/385: celltype=NK, leave_out=Pool138_6, global_p=0.376, elapsed=0.24 min
    total=36535, sanity=36535, nan=36535, >0=0, <0=0, =0=0

[2026-06-24 11:03:28] Start 383/385: celltype=NK, leave_out=Pool138_7
[2026-06-24 11:03:30] Running neighbors: n_cells=35782
[2026-06-24 11:03:34] Building sample metadata
[2026-06-24 11:03:34] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:03:42] DONE 383/385: celltype=NK, leave_out=Pool138_7, global_p=0.299, elapsed=0.24 min
    total=35782, sanity=35782, nan=35782, >0=0, <0=0, =0=0

[2026-06-24 11:03:42] Start 384/385: celltype=NK, leave_out=Pool138_8
[2026-06-24 11:03:45] Running neighbors: n_cells=36370
[2026-06-24 11:03:48] Building sample metadata
[2026-06-24 11:03:48] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:03:56] DONE 384/385: celltype=NK, leave_out=Pool138_8, global_p=0.427, elapsed=0.24 min
    total=36370, sanity=36370, nan=36370, >0=0, <0=0, =0=0

[2026-06-24 11:03:57] Start 385/385: celltype=NK, leave_out=Pool138_9
[2026-06-24 11:03:59] Running neighbors: n_cells=36143
[2026-06-24 11:04:03] Building sample metadata
[2026-06-24 11:04:03] Running CNA association: testvar=race, covars=['group', 'age', 'obesity', 'diabetes'], n_samples=54

/n/data1/dfci/surgonc/mittendorf/lab/chelsea/iw/scRNA_v2/codes/packages/cna-master/src/cna/utils/multisample.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  d.obs.groupby(by=sid_name)[columns].aggregate(aggregate)

[2026-06-24 11:04:11] DONE 385/385: celltype=NK, leave_out=Pool138_9, global_p=0.499, elapsed=0.24 min
    total=36143, sanity=36143, nan=36143, >0=0, <0=0, =0=0

In [13]:
df_summary

,celltype_major,pt_loo,testvar,covars,status,global_p,totalCells,nan%,pos%,neg%,zero%,elapsed_min
0,B,Pool137_10,race,"group,age,obesity,diabetes",ok,0.000999,48933,95.054462,0.069483,4.876055,0.0,0.771649
1,B,Pool137_11,race,"group,age,obesity,diabetes",ok,0.000999,48732,95.750226,0.069769,4.180005,0.0,0.372564
2,B,Pool137_12,race,"group,age,obesity,diabetes",ok,0.000999,48943,94.383262,0.181844,5.434894,0.0,0.369978
3,B,Pool137_14,race,"group,age,obesity,diabetes",ok,0.000999,48053,93.763137,0.149835,6.087029,0.0,0.356233
4,B,Pool137_15,race,"group,age,obesity,diabetes",ok,0.000999,48488,95.751526,0.049497,4.198977,0.0,0.348831
...,...,...,...,...,...,...,...,...,...,...,...,...
380,NK,Pool138_5,race,"group,age,obesity,diabetes",ok,0.382617,35288,100.000000,0.000000,0.000000,0.0,0.231721
381,NK,Pool138_6,race,"group,age,obesity,diabetes",ok,0.375624,36535,100.000000,0.000000,0.000000,0.0,0.237158
382,NK,Pool138_7,race,"group,age,obesity,diabetes",ok,0.298701,35782,100.000000,0.000000,0.000000,0.0,0.236237
383,NK,Pool138_8,race,"group,age,obesity,diabetes",ok,0.426573,36370,100.000000,0.000000,0.000000,0.0,0.236201
384,NK,Pool138_9,race,"group,age,obesity,diabetes",ok,0.498501,36143,100.000000,0.000000,0.000000,0.0,0.239169

In [18]:
import pandas as pd
import numpy as np

def median_range(x):
    x = pd.to_numeric(x, errors="coerce").dropna()
    return f"{x.median():.3g} ({x.min():.3g}-{x.max():.3g})"

def n_pct_condition(mask):
    mask = mask.dropna()
    n = mask.sum()
    denom = len(mask)
    pct = n / denom * 100 if denom > 0 else np.nan
    return f"{n}/{denom} ({pct:.1f}%)"

summary_by_celltype = (
    df_summary
    .groupby("celltype_major")
    .agg(
        global_p_median_range=("global_p", median_range),
        global_p_lt_0_05_n_pct=(
            "global_p",
            lambda x: n_pct_condition(pd.to_numeric(x, errors="coerce") < 0.05)
        ),
        pos_gt0_n_pct=(
            "pos%",
            lambda x: n_pct_condition(pd.to_numeric(x, errors="coerce") > 0)
        ),
        neg_gt0_n_pct=(
            "neg%",
            lambda x: n_pct_condition(pd.to_numeric(x, errors="coerce") > 0)
        ),
    )
    .reset_index()
)

combined = (
    df_summary
    .groupby("celltype_major")
    .apply(
        lambda d: n_pct_condition(
            (pd.to_numeric(d["global_p"], errors="coerce") < 0.05)
            & (pd.to_numeric(d["pos%"], errors="coerce") > 0)
            & (pd.to_numeric(d["neg%"], errors="coerce") > 0)
        )
    )
    .reset_index(name="global_p_lt_0_05_pos_gt0_neg_gt0_n_pct")
)

summary_by_celltype = summary_by_celltype.merge(combined, on="celltype_major")

summary_by_celltype

/tmp/ipykernel_3770805/3198807504.py:39: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

,celltype_major,global_p_median_range,global_p_lt_0_05_n_pct,pos_gt0_n_pct,neg_gt0_n_pct,global_p_lt_0_05_pos_gt0_neg_gt0_n_pct
0,B,0.000999 (0.000999-0.005),55/55 (100.0%),51/55 (92.7%),53/55 (96.4%),51/55 (92.7%)
1,CD4 T,0.00999 (0.002-0.0519),54/55 (98.2%),33/55 (60.0%),34/55 (61.8%),32/55 (58.2%)
2,CD8 T,0.135 (0.0509-0.319),0/55 (0.0%),0/55 (0.0%),0/55 (0.0%),0/55 (0.0%)
3,DC,0.003 (0.000999-0.00899),55/55 (100.0%),53/55 (96.4%),53/55 (96.4%),53/55 (96.4%)
4,Mono,0.000999 (0.000999-0.000999),55/55 (100.0%),55/55 (100.0%),55/55 (100.0%),55/55 (100.0%)
5,NK,0.352 (0.169-0.629),0/55 (0.0%),0/55 (0.0%),1/55 (1.8%),0/55 (0.0%)
6,other T,0.67 (0.345-0.807),0/55 (0.0%),0/55 (0.0%),0/55 (0.0%),0/55 (0.0%)

In [20]:
dft = summary_by_celltype.iloc[:,:5]

dft.columns = [
   'Cell lineage',
   'Global association P value, median (range)',
   'Global association P <0.05, n (%) LOO runs',
   'Positive local association cell state% >0, n (%) LOO runs',
   'Negative local association cell state% >0, n (%) LOO runs'
   ]

dft

,Cell lineage,"Global association P value, median (range)","Global association P <0.05, n (%) LOO runs","Positive local association cell state% >0, n (%) LOO runs","Negative local association cell state% >0, n (%) LOO runs"
0,B,0.000999 (0.000999-0.005),55/55 (100.0%),51/55 (92.7%),53/55 (96.4%)
1,CD4 T,0.00999 (0.002-0.0519),54/55 (98.2%),33/55 (60.0%),34/55 (61.8%)
2,CD8 T,0.135 (0.0509-0.319),0/55 (0.0%),0/55 (0.0%),0/55 (0.0%)
3,DC,0.003 (0.000999-0.00899),55/55 (100.0%),53/55 (96.4%),53/55 (96.4%)
4,Mono,0.000999 (0.000999-0.000999),55/55 (100.0%),55/55 (100.0%),55/55 (100.0%)
5,NK,0.352 (0.169-0.629),0/55 (0.0%),0/55 (0.0%),1/55 (1.8%)
6,other T,0.67 (0.345-0.807),0/55 (0.0%),0/55 (0.0%),0/55 (0.0%)

In [22]:
dft.to_csv(
    'data/Tables/supp_loo.csv'
)